### ISSUE TITLE
Add job that fires APNS notifications automatically if there are commands queued

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#100]
Need a worker which will 
a) ask the device to check in if a new commands was queued or a delayed one in case of NotNow. 
b) ask the device to check in every x hours (24 by default?)

**Comment by jessepeterson** [comment]
@groob: what did you think of this note in #122 to address your concerns for _not_ wanting to send push notifications in some scenarios (which I agree with):

> One thing I was thinking was an attribute or some signal on each queued command that tells whether to send a push or not. In this way its up to the command-sender to decide when pushes get sent out (including some way to trigger an arbitrary push say at the end of queuing a bunch of commands).

This would allow _not_ sending pushs for queued commands when they land. Basically add a `PushRequested` to each command (defaulted to true). If this is done there may need to be a generic method to send a push notification (e.g. at the end of a group of queued commands).

Also: you'd said a device doesn't need push requests sent until after enrollment: if that's true we'll need to be able to queue new commands/behavior the moment a device enrolls (before the end of their first command) such that when the current command is done there are already more queued commands. Perhaps another event on a message bus to signal this? Not sure.

**Comment by groob** [comment]
@jessepeterson I think the `PushRequested` idea merits some experimentation, but will need refinement. We'll definitely have to have something like it implemented in the long run though. 

Here's a somewhat hairy (but I expect very common) scenario to think through. 

* Device Enrolls, and we have a blueprint for the device which includes:
    - profileX
    - profileY
    - ApplicationA
    - UserAccount

* Device went through checkin process, and we queued all the commands to get that stuff from the blueprint. Now this device goes to `/connect` in a loop until we've replied with every single one of the queued commands. 
The device starts responding to use immediately with statuses:
ProfileX - Acknowledged 
ProfileY - Acknowledged
ApplicationA - NotNow - (we keep this in the queue for later)
UserAccount - Acknowledged
We respond with 200 OK and the device is done talking to us. 

... moments, minutes, hours etc later:
The user logs in. We somehow have to check in with the device and still deliver that InstallApplication command. At this point we need to start using the Push API to do it, because the device is not connecting on it's own.

The key here is that we want InstallApplication to be sent right after a user session started, but not just before, where we'll get a `NotNow`. 

Here's a log that matches the above scenario fairly closely:

<img width="1266" alt="screenshot 2017-03-21 11 07 56" src="https://cloud.githubusercontent.com/assets/1526945/24316758/1a81f2c4-10c7-11e7-97fe-93ab393bd629.png">

**Comment by groob** [comment]
Closing this round because #122 is good enough. We'll figure out what needs to be refined later.

**Comment by jessepeterson** [comment]
@groob: since we know we can't `InstallApplication` before the DeviceConfigured state, we should probably not send those at that time. If the NotNow command is sent last the device will re-check-in itself after a NotNow.

**Comment by groob** [comment]
InstallApplication now works with AwaitDeviceConfigured state in 10.12.4
Tested yesterday.

**Comment by jessepeterson** [comment]
10.12.4 also came out two days ago :) I think we need to support the case where folks aren't running bleed-edge versions of OSes :)

**Comment by jessepeterson** [comment]
In any case the logic seems clear: if there's a NotNow that we reply to commands with we need . NotNow<->APNS bouncer - perhaps with some sort of back-off algorithm.

As well we'll still need to consider a good mechanism to trigger APNS notifications from within the API. I think aggregating commands in CommandSets (or something similar) might be a good way to approach that. Just noting here for posterity.

**Comment by groob** [comment]
Generally I agree, but the current scenario is you get a NotNow, and you get a push notification soon after. IMO it's preferable to send the IAP command as early as possible.

Of course I'm not opposed to improved handling here. The command queue still needs a lot of work.

**Comment by groob** [comment]
@jessepeterson I added some fields to the Command struct here https://github.com/micromdm/micromdm/blob/master/queue/device_command.go#L16-22 to improve handling of commands on a queue, but they're not really used yet.

We definitely need to at least open an issue and make use of the fields to improve the handling of the queue.
