### ISSUE TITLE
mdmcert.download 500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by z3ky** [micromdm/micromdm#1010]
### What version of `micromdm` are you using?
v1.12.1
### What `micromdm` command did you run?
mdmctl mdmcert.download -new -email=xxx
### What did you expect to see?
Request successfully sent to mdmcert.download ...
### What did you see instead?
error sending http request: received bad status from mdmcert.download. status="500 INTERNAL SERVER ERROR"

**Comment by jessepeterson** [comment]
Thanks for your report @z3ky but the micromdm.download is not an official MicroMDM project. The responsible parties are aware and working on the issue, though.

**Comment by jessepeterson** [comment]
@z3ky you may want to try again now. thanks!

**Comment by z3ky** [comment]
Works, thanks!!
