### ISSUE TITLE
Install App with micromdm 

### ISSUE THREAD

**Issue by zcy382725** [micromdm/micromdm#1020]
I was able to push the pkg "FileZilla_Server_1.8.1_macos-x86.pkg" downloaded form internet and pulled it to a mac client with micromdm. 

But i encountered problems pulling "munkitools-6.5.1.4661.pkg"  downloaded from Github.

First, i signed the pkg "munkitools-6.5.1.4661.pkg" with "3rd Party Mac Developer Installer: xxxx" identity.

Then, i was able to apply this pkg app and push to mac client.

I've checked the log from client and it shows the pkg was fully downloaded and failed at installing process, and the log shows like 
![image](https://github.com/user-attachments/assets/96b01f95-7aca-4e6f-bff8-6db06e696296)

What's the problem cause the difference between this two pkg?
The sign process or the package process ?
What is the proper way to pull a unsigned pkg like "munki"?

**Comment by jessepeterson** [comment]
Packages must be distribution packages and signed by a trusted Apple certificate. Some docs here: 

https://github.com/micromdm/micromdm/wiki/distributing-packages-with-InstallApplication

Notably:

> Note that only distribution style packages are supported. Use productbuild to turn a component flat pkg into a distribution one.

Hope this helps!

**Comment by korylprince** [comment]
Also, there are munki builds signed by MacAdmins Open Source [here](https://github.com/macadmins/munki-builds/releases) (and these are Distribution pkgs).

**Comment by zcy382725** [comment]
> Packages must be distribution packages and signed by a trusted Apple certificate. Some docs here:
> 
> https://github.com/micromdm/micromdm/wiki/distributing-packages-with-InstallApplication
> 
> Notably:
> 
> > Note that only distribution style packages are supported. Use productbuild to turn a component flat pkg into a distribution one.
> 
> Hope this helps!

thanks for your help, that's exactly what i need.
