### ISSUE TITLE
push token lose iss

### ISSUE THREAD

**Issue by xujimu** [micromdm/micromdm#1025]
The MDM device token is used by APNs (Apple Push Notification Service) to send notifications. If this token is lost, is there a way to retrieve it? When does the device trigger a TokenUpdate to provide a new token?

**Comment by jessepeterson** [comment]
If you lose the MDM push tokens then you will not be able to send MDM APNs pushes to devices.

It is not documented when or how TokenUpdate messages are re-sent to the device. There isn't a way to "trigger" a TokenUpdate (other than a re-enroll, of course). My understanding is that TokenUpdates are initiated from the APNs service (i.e. Apple server-side) to the device. The new tokens are then passed to the MDM server from the device.

Hope that helps!
