### ISSUE TITLE
enroll device automaticly

### ISSUE THREAD

**Issue by end-former-LAH** [micromdm/micromdm#1028]
### What version of `micromdm` are you using?
1.12.1
### What did you expect to see?
What can I do for enrolling device automaticly?

**Comment by jessepeterson** [comment]
@end-former-LAH what do you mean by 'automatically?' Apple, of course has [ADE](https://support.apple.com/en-us/102300) instructions for which are mentioned in the [MicroMDM docs](https://github.com/micromdm/micromdm/blob/main/docs/user-guide/enrolling-devices.md#dep-device-assignment).

For any general questions or guidance on how to use this or configure it I suggest joining the [MacAdmins Slack](https://www.macadmins.org) in the #micromdm channel.

**Comment by end-former-LAH** [comment]
I would like to implement a one-click registration device feature when the server is open.

**Comment by jessepeterson** [comment]
If you're not doing ADE/DEP enrollment then Apple forces the end-user to open Settings to approve any profile installs (such as enrollment profiles). This is to prevent automated enrollment (again, outside of ADE/DEP).

I suspect this was done for security to prevent malware from "one-click" enrolling devices.

Other enrollment alternatives are ADDE and ADUE. Try looking here:

https://support.apple.com/guide/deployment/intro-to-apple-device-enrollment-types-dep08f54fcf6/web

And if Apple is not offering what you're looking for you can file feedback here:

https://www.apple.com/feedback/

This does not seem to be a MicroMDM issue -- all/any MDM servers function this way and by Apple's rules.
