### ISSUE TITLE
Don't install the .mobileconfig file manually in enrolling devices

### ISSUE THREAD

**Issue by end-former-LAH** [micromdm/micromdm#1029]
### What version of `micromdm` are you using?
1.12.1
### What did you expect to see?
We can install the .mobileconfig file automatically behind downloading the .mobileconfig file.

**Comment by jessepeterson** [comment]
Hello. I'm not quite sure what you're asking here. I pointed out some docs to you in #1028. Could you re-state what you'd like to see happen, or what you're trying to do? Outside of ADE Apple has, very intentionally, made automated enrollment not possible.

Again if you've got general questions or need guidance on how to use or configure things I suggest joining the [MacAdmins Slack](https://www.macadmins.org) in the #micromdm channel.

**Comment by end-former-LAH** [comment]
Thank you

**Comment by jessepeterson** [comment]
See comment in #1029

**Comment by jessepeterson** [comment]
I'm going to close this as there does not seem to be problems with MicroMDM here. Working as expected. :) Again please join us in Slash to ask any general questions.
