### ISSUE TITLE
Add example syntax to -h command

### ISSUE THREAD

**Issue by loyaltyarm** [micromdm/micromdm#103]
When using `sudo micromdm serve -h`, there is no example syntax given. This would be helpful to see outside of the specific example in the quickstart, simply because some commands use a `=` sign and some do not. Feel free to close if too trivial, but an example would be where a particular user is using `.pem` and not `.p12`.

**Comment by groob** [comment]
`=` is optional for every flag. 

The way it works is `-flag=value` or `-flag value`. 
But there are defaults for each. 
For example, with a boolean value, you have the option of:

- omitting it: will default to whatever the `-h` flag says. 
- using the short version, `-flag`, which would set it to true, or
- with both the flag and the value `-flag false` or `-flag=false` 

I do think an `micromdm serve -examples` flag would be a really neat way to provide extra documentation for a command.

**Comment by loyaltyarm** [comment]
Closing with #119
