### ISSUE TITLE
mac os 15 and ios 18

### ISSUE THREAD

**Issue by ehsandavari2000** [micromdm/micromdm#1031]
in mac os 15 and ios 18 user enrollment no work because managed apple id key id MDM enrollment profile deprecated.

please help me for find solution for this issue?

**Comment by jessepeterson** [comment]
You'll need to switch to the new [ADUE (User Enrollment)](https://support.apple.com/guide/deployment/user-enrollment-and-mdm-dep23db2037d/web) or [ADDE (Account-Driven Device Enrollment)](https://support.apple.com/guide/deployment/device-enrollment-and-mdm-depd1c27dfe6/web) processes.

Check out Apple's WWDC 2021 video here for high-level review of how that works for ADUE: https://developer.apple.com/wwdc21/10136

Built-in support for this enrollment style is not available in MicroMDM, even though MicroMDM should support the actual enrollment/device itself.
