### ISSUE TITLE
mdmctl apply app -pkg ioscaja.ipa results in : verifying package: could not open reader: xar: bad magic

### ISSUE THREAD

**Issue by phillippc** [micromdm/micromdm#1039]
### What version of `micromdm` are you using?
micromdm version v1.12.1
### What `micromdm` command did you run?
mdmctl apply app -pkg ioscaja.ipa 
### What did you expect to see?
I expected the ipa to be installed
### What did you see instead?
verifying package: could not open reader: xar: bad magic

running on fresh linux debian install. Am I Missing any python packages maybe?

**Comment by korylprince** [comment]
`mdmctl apply app ...` is for pkgs. There's not an mdmctl command for dealing with IPAs.

I don't have any experience deploying iOS apps with MicroMDM, would would suggest you check out these issues: #512 #519
