### ISSUE TITLE
Add documentation for using self-signed TLS certificates for testing (or science)

### ISSUE THREAD

**Issue by loyaltyarm** [micromdm/micromdm#104]
If you follow the quickstart, it is assumed you are on the **public internet** 😱. We should have some documentation about using self-signed TLS certs so that users/testers can use `https://localhost` to run their MDM server if needed for testing (or _science_). Without this, you can start the micromdm server on localhost, but will receive the following errors when trying to hit `/mdm/enroll`:

```
component=main msg=started
no DEP server configured. skipping device sync from DEP.
no blueprint specified in /etc/micromdm/blueprint.json, skipping default device actions
transport=HTTP addr=:https
ts="2017/03/21 17:08:00" caller="http: TLS handshake error from [::1" msg="]:53508: 400 urn:acme:error:malformed: DNS name does not have enough labels"
ts="2017/03/21 17:08:00" caller="http: TLS handshake error from [::1" msg="]:53509: acme/autocert: missing certificate"
```

**Comment by groob** [comment]
One possible option would be to do this for the user: 

`micromdm serve -self-sign -server-url=mdm.acme.co` which would create certificates for mdm.acme.co. 

If they pass a self-sign flag we'll also know that they need anchor certs in their profile etc. 

Of course we should also document this as there's too many options for TLS configuration. 
I started something on the wiki, but it's not yet complete: 

https://github.com/micromdm/micromdm/wiki/Using-MDM-with-self-signed-certificates

@loyaltyarm would you mind going over the wiki instructions here once you figure out your setup?

**Comment by groob** [comment]
If anyone would like to tackle it, theres a complete example in the go stdlib. 

https://github.com/golang/go/blob/master/src/crypto/tls/generate_cert.go
Another example is the key,cert/csr files in the `scepclient` package:
https://github.com/micromdm/scep/tree/master/cmd/scepclient

**Comment by loyaltyarm** [comment]
> @loyaltyarm would you mind going over the wiki instructions here once you figure out your setup?

This generally worked well, with the exception of the editing of `/etc/hosts`, which I've tried on multiple machines now and gotten the following weird situation:

```
$ sudo echo "127.0.0.1 mdm.acme.co" >> /etc/hosts
-bash: /etc/hosts: Permission denied
```
I believe this is because `echo` in macOS doesn't support an expected flag (`-e`?). At any rate, the below command should fix it as far as the wiki goes.

```
sudo sh -c 'echo "127.0.0.1 mdm.acme.co\n" >> /etc/hosts'
```

**Comment by groob** [comment]
Documentation for self signed certificates is available on the wiki page:

https://github.com/micromdm/micromdm/wiki/Using-MicroMDM-with-self-signed-certificates

Please update if/when there's anything new to add.
