### ISSUE TITLE
mdm

### ISSUE THREAD

**Issue by Gaoxichao** [micromdm/micromdm#1040]
mdm

**Comment by Gaoxichao** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>CommandUUID</key>
        <string>xxx</string>
        <key>QueryResponses</key>
        <dict>
                <key>BatteryLevel</key>
                <real>0.059999999999999998</real>
                <key>CellularTechnology</key>
                <integer>1</integer>
                <key>DataRoamingEnabled</key>
                <false/>
                <key>IMEI</key>
                <string>xxx</string>
                <key>IsActivationLockEnabled</key>
                <false/>
                <key>IsMDMLostModeEnabled</key>
                <false/>
                <key>IsNetworkTethered</key>
                <true/>
                <key>IsRoaming</key>
                <false/>
                <key>IsSupervised</key>
                <true/>
                <key>OSVersion</key>
                <string>18.1</string>
                <key>ProductName</key>
                <string>iPhone17,2</string>
                <key>ServiceSubscriptions</key>
                <array>
                        <dict>
                                <key>CarrierSettingsVersion</key>
                                <string>60.0</string>
                                <key>CurrentCarrierNetwork</key>
                                <string>中国移动</string>
                                <key>CurrentMCC</key>
                                <string>460</string>
                                <key>CurrentMNC</key>
                                <string>00</string>
                                <key>ICCID</key>
                                <string>xxx</string>
                                <key>IMEI</key>
                                <string>xxx</string>
                                <key>IsDataPreferred</key>
                                <true/>
                                <key>IsRoaming</key>
                                <false/>
                                <key>IsVoicePreferred</key>
                                <true/>
                                <key>Label</key>
                                <string>主号</string>
                                <key>LabelID</key>
                                <string>xxxx</string>
                                <key>PhoneNumber</key>
                                <string>xxx</string>
                                <key>Slot</key>
                                <string>CTSubscriptionSlotOne</string>
                                <key>SubscriberCarrierNetwork</key>
                                <string>中国移动</string>
                        </dict>
                        <dict>
                                <key>CarrierSettingsVersion</key>
                                <string>60.0</string>
                                <key>CurrentCarrierNetwork</key>
                                <string>中国移动</string>
                                <key>CurrentMCC</key>
                                <string>460</string>
                                <key>CurrentMNC</key>
                                <string>00</string>
                                <key>ICCID</key>
                                <string>xxxx</string>
                                <key>IMEI</key>
                                <string>xxxx</string>
                                <key>IsDataPreferred</key>
                                <false/>
                                <key>IsRoaming</key>
                                <false/>
                                <key>IsVoicePreferred</key>
                                <false/>
                                <key>Label</key>
                                <string>副号</string>
                                <key>LabelID</key>
                                <string>xxx</string>
                                <key>PhoneNumber</key>
                                <string></string>
                                <key>Slot</key>
                                <string>CTSubscriptionSlotTwo</string>
                                <key>SubscriberCarrierNetwork</key>
                                <string>中国移动</string>
                        </dict>
                </array>
        </dict>
        <key>Status</key>
        <string>Acknowledged</string>
        <key>UDID</key>
        <string>xxx</string>
</dict>
</plist>
`
This is the xml file, it looks like a Chinese encoding problem? Then the device will not interact (even if there is a network)

**Comment by jessepeterson** [comment]
I saw you also submitted micromdm/plist#40 which is essentially the same thing.

Apple appears to be sending MicroMDM invalid XML in a command response (specifically a NUL character or 0-byte) somewhere in the data — though your pasted example seems okay? We'd have to run it through a hexdump perhaps to see where the invalid data is coming from. The [Golang XML parser](https://pkg.go.dev/encoding/xml) (which the Plist library and thus MicroMDM uses) is not accepting this invalid XML that Apple has sent it. I suspect you're going to need to submit [Feedback to Apple](https://feedbackassistant.apple.com).

As another example of Apple sending invalid XML here's an issue we've seen before that we submitted to Apple (but haven't heard back on yet): https://openradar.appspot.com/FB11380612

**Comment by Gaoxichao** [comment]
Will this cause command backlog or something? Because when this error occurs, I cannot send other commands to the device (when sending, the console will immediately display the last error message)
![1732040516468](https://github.com/user-attachments/assets/271b94f3-0c02-45de-a5cc-c64166470523)

**Comment by jessepeterson** [comment]
@Gaoxichao yes. MicroMDM knows to 'advance' the command queue because the last command was acknowledged (received). If the MDM server never 'receives' the acknowledgment (say, because it can't decode the acknowledged report) then the command is still sitting in the queue for the device to request again. It will effectively block new commands from being processed.

**Comment by jessepeterson** [comment]
@Gaoxichao did you get to a resolution with this? Just curious! Thanks!
