### ISSUE TITLE
add a simple homepage

### ISSUE THREAD

**Issue by loyaltyarm** [micromdm/micromdm#106]
potentially redirect base url (`/`) to `/mdm/enroll` endpoint for forgetful people like me who just hit the base URL during testing 🤔

**Comment by groob** [comment]
if anyone wants to try:

https://golang.org/pkg/net/http/#Redirect

**Comment by jessepeterson** [comment]
I'd advise against this, personally. I think a super simple HTML page saying "Hi, welcome to uMDM." with a hyperlink to the enroll page would be better. This avoids accidental enrollment profile generation (which may or may not be your goal). Or better yet it can be a config option for folks.

**Comment by erikng** [comment]
Agreed.

________________________________

**Comment by groob** [comment]
Let's do that instead :)

**Comment by groob** [comment]
Done, thanks to @jessepeterson in #113
