### ISSUE TITLE
Setup without enterprise license - Just for development

### ISSUE THREAD

**Issue by dhirenrouterabbit** [micromdm/micromdm#11]
Hello, 

I want to setup micro-mdm just for the experimentation purpose & explore the possibilities. 
Please help how can I set it up just for development purpose.

Thank you.

**Comment by groob** [comment]
Hi @dhirenrouterabbit, 

Thank you for interest in the project. As you can see from https://github.com/project-imas/mdm-server/issues/33, I opened a similar request on project-imas before starting my own project. 
Unfortunately, this is in Apple's hands. The best you could do as a developer without access to an MDM push certificate is write unit tests. 

All the server does is communicate with a device, and the device will only talk to the server after a push notification, which must be signed by an MDM cert. Apple does not offer a device simulator, or a test certificate. Even the protocol definition is behind an NDA. 

At best I can point you to @bruienne's excellent guide on requesting a cert from Apple through your company's developer account. http://enterprisemac.bruienne.com/2015/06/06/mdm-azing-setting-up-your-own-mdm-server/

Your company can also request a push certificate through https://mdmcert.download/ 
That cert can be used to start the MDM server.

**Comment by dhirenrouterabbit** [comment]
Thanks, Hey I am trying to use some open source component for BYOD iOS devices (non-supervised), does project-imas can be used for production for a simple operation like VPN configuration & restrictions push and remove on iOS devices?

**Comment by jessepeterson** [comment]
Hi @dhirenrouterabbit, to do anything with MDM you'll need an Apple MDM Push certificate. This means you need to get a certificated signed by Apple in one of two ways. 1) Become an Enterprise Developer and sign a request yourself (to then get signed by Apple), or 2) Have someone else sign the certificate for you (and then get that signed by Apple). In the case of 2) there is 2a) have Apple sign an OS X Server push cert (and extract it from OS X) or 2b) have a 3rd party sign the certificate (and then get it signed by Apple).

Per 2b) above you might want to check out https://mdmcert.download/ to get a free certificate. I'm not sure if MicroMDM has support for it quite yet, but I know [Commandment](https://github.com/jessepeterson/commandment) does.
