### ISSUE TITLE
Verify the device identity certificate

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#118]
We want to verify the device identity certificate which was signed by the scep CA. 
This cert is only necessary for the `/mdm/connect` endpoint. Unfortunately cert auth happens during a TLS handshake so we can't verify it in the http handler. 

Here are the options for the connect endpoint:
Bind to `:8443` (configurable by the user) and require the identity certificate there. 

or: 

use `tls.Config.GetConfigForClient func(*ClientHelloInfo) (*Config, error)` and require certificate for 
`connect.mdm.acme.co`

Either way the user has to do additional configuration.

**Comment by jessepeterson** [comment]
We can also go the MDM enrollment profile `SignMessage` route which passes the client identity over a `Mdm-Signature` header. (doc'd [here](https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/MobileDeviceManagementProtocolRef/6-MDM_Best_Practices/MDM_Best_Practices.html#//apple_ref/doc/uid/TP40017387-CH5-SW1)).
