### ISSUE TITLE
how to create server certificates for development

### ISSUE THREAD

**Issue by patriciojofre** [micromdm/micromdm#12]
The push certificate is ready, but I can't create correctly the server certificates for development. I followed many guides and tutorials but I can't make it works. Please help!

**Comment by groob** [comment]
Hi Patrick, 

The server certificates are just standard TLS certs. You can use openssl to create a server cert.
I like using the https://github.com/rcrowley/certified tool, which is a collection of wrappers to manage certificates easily. 
I wrote a gist [here](https://gist.github.com/groob/01a40417e0176bd9ea8d473c8e381daa) and an earlier blog post [earlier](https://groob.io/posts/internal_ca/) to show how I create server certs. 

I hope that helps. 
There's also a [guide](https://devcenter.heroku.com/articles/ssl-certificate-self) on heroku for using openssl. I hope these resources help.

**Comment by patriciojofre** [comment]
Hi @groob , thanks for your answer. 
I created the certificates but the osx console returns the next error:
![screen shot 2016-09-02 at 3 06 34 pm](https://cloud.githubusercontent.com/assets/4438095/18213511/faaa7f22-711e-11e6-9cf0-04cb1d96c01c.png)

What do you know about this error?
Thanks

**Comment by groob** [comment]
I am working on adding SCEP support built into the micromdm server(see the other repo). 
For now, you have to manually create an identity certificate for enrollment. 

The directions here https://github.com/project-imas/mdm-server/blob/master/README.md#setup go into detail about creating an `Identity.p12` cert, which you will need to add to your enrollment mobileconfig. 

My blog post on setting an MDM server goes a bit more into creating an identity cert. https://groob.io/posts/mdm-experiments/
I use apple configurator to create an Enrollment.mobileconfig with the above identity file and with the server CA cert chain as a certificate payload. 

I will be adding the SCEP server  directly to micromdm soon.

**Comment by patriciojofre** [comment]
Thanks for your help, I'll try it again and wait for your complete micromdm solution.

**Comment by mosen** [comment]
/mdm/enroll endpoint can now deliver a SCEP payload that contacts a micromdm SCEP service.
There's still a gotcha: you will have to trust the SCEP CA before push works.

**Comment by groob** [comment]
SCEP server is now embedded in micromdm :)
