### ISSUE TITLE
Consistent `mdmctl` CLI UI

### ISSUE THREAD

**Issue by jessepeterson** [micromdm/micromdm#162]
A few of the `apply` and `get` commands are very similar but have different flags and calling conventions. To make these consistent throughout.

**Comment by groob** [comment]
with apply I noticed that you created 
```
mdmctl apply blueprints -generate-blueprint /path/to/new_blueprint.json
```
which creates a template and saves it to a path.

With DEP profiles, I did something similar, but 

```
mdmctl apply dep-profiles -template
```
My version prints the template to stdout.

We should settle on one way to do this. 

Personally, I'd prefer if we print to stdout instead of asking for a file, because it's more flexible. I can always redirect output to a file if I need to, but many times I want to use the `-generate-blueprint` file just to remind myself of what the fields are, and creating a file is too much commitment.

**Comment by jessepeterson** [comment]
Yep, I'm on board with stdout. However there's a number of options that _do_ generate files. Should it be across the board? E.g. `get blueprints -json` `get profiles -f`. Should those also be stdout? I could see it either way. However with blueprints and profiles I think the "saving" portion is implemented in the "listing" portion, so we'd have to resolve how output is done overall in those commands to support that.

Another option is to support using `-` as an argument to the filename to output as a way to dump to stdout.

**Comment by groob** [comment]
IMO, flags like `-json` should also print to stdout. Another argument for doing so is that I can use a tool like `jq` (or even sed/awk etc) to filter output further. 

Also, that's how kubernetes does it:
```
kubectl get pods -o json
``` 
prints a big json blob to stdout.

**Comment by jessepeterson** [comment]
Yep! Overall I'm fine with stdout output unless there's a good reason not to (e.g. non-encoded or excessive binary output, very large data, etc.).

**Comment by jessepeterson** [comment]
One consideration for profiles is that they are blobs and may be CMS encoded. Some folks might be surprised to have binary data being output.

**Comment by groob** [comment]
IMO the output for something like that should be b64 encoded.

**Comment by jessepeterson** [comment]
Sure, but then it defeats some of the purpose of going to stdout in the first place. :) I.e. every time I wanted to look at a profile I don't want to have to worry about piping through `openssl base64 -d`. I suppose it could auto-detect if the first few bytes are `<?xml` and act accordingly, but then its somewhat non-deterministic.

**Comment by jessepeterson** [comment]
Perhaps the CLI UX follows a set of rules, something like: 

1. If the output will be used as a file _by most users/administrators of the MicroMDM software_ most of the time (e.g. to upload to a browser, to email as an attachment, or otherwise primarily treat as a "file") then default to saving to a path.
2. If the data either is binary or there's some non-zero chance the data can be binary (or otherwise "not-CLI-friendly" like non-encoded data, non-ASCII/UTF-8 characters, very very large data, etc.) then default to saving to a path.
3. All other cases should output to stdout.

**Comment by groob** [comment]
I like that guideline. We can work out any edge cases once they come up :)

**Comment by jessepeterson** [comment]
Another aspect of this is data _input_. Presumably we should read from stdin as well along a similar rule.

**Comment by jessepeterson** [comment]
I've spelled out all the mdmctl parameters and switches here https://paste.ee/p/GrGHM

With that, and the rules above I see a few changes that seem to be in order:

* `get blueprints`: `-json` should output to stdout, not a file
* `get dep-tokens`: `-export-token` should be `-json` and export to stdout, not a file
* `apply blueprints`: `-f` should be `-json` and read from stdin, not a file
* `apply dep-profiles`: `-f` should be `-json` and read from stdin, not a file

**Comment by jessepeterson** [comment]
Concerns have been addressed for now, see all merged PRs. Closing! :)
