### ISSUE TITLE
support switching servers with mdmctl

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#188]
as an operator I might want to work with multiple remote micromdm servers. 
mdmctl should support this

**Comment by natewalck** [comment]
Noting this here so I don't lose it to the ether:

* Read existing default.json and append config with new format if changing
* Need a method for tracking the active config
* NewConfig function
* Formatter for output so it is more pretty
   * print current config
   * print all configs

**Comment by groob** [comment]
Closed by #275
