### ISSUE TITLE
sign/validate signature on linux

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#202]
From @jessepeterson in #199 
> I'd make a note in the flag arguments that -sign requires productbuild (even though it compiles out of the linux binaries).
> Perhaps we should use go-xar to verify a signature instead of pkgutil (or both, somehow). Can also be used to pull apart the package to verify that its Distribution.

agree with all that, but in the interest of time `mdmctl` will start by exec'ing to productbuild on macOS. 
Over time we should add this functionality on linux(as long as it's built purely in Go and doesn't require installing deps/or makes them optional.

**Comment by Beanow** [comment]
Can you provide some background on the command you mean and its use case? Or the expected functionality?

**Comment by jessepeterson** [comment]
Packages deployed/Installed by MDM need to be signed. Currently mdmctl can shell out to `productbuild` (a macOS-only tool) to sign package installers. My comment was ruminating on supporting native pkg sign capability for, not least of which, cross-platform package signing.

**Comment by korylprince** [comment]
This was implemented in #785 with the generic `-sign-identity` flag. This depends on [go-macos-pkg](https://github.com/korylprince/go-macos-pkg), which currently depends on the `xar` utility being installed on the system. I hope to one day have a pure Go xar encoder.
