### ISSUE TITLE
verify that imported package is a distribution package

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#203]
`mdmctl` as implemented in #199 validates that the imported package is signed (and has an option to sign it. I punted on also validating that the package is a distribution one, but ideally we should do that validation on import too. 
If someone knows _how_ we should do the validation either send a PR or comment on the issue please :)

**Comment by jessepeterson** [comment]
As noted in #199 Commandment [simply extracted the Distribution file](https://github.com/jessepeterson/commandment/blob/master/commandment/utils/app_manifest.py#L13-L94) from the `.pkg` xar file. This had the added benefit of being able to inspect the bundle-ids for placement in the app manifest as well. In Commandment we shelled out to the `xar` binary; not exactly ideal, but worked.
