### ISSUE TITLE
if the MDMAuthSignMessage middleware fails, the device keeps retrying forever

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#211]
Reported bug:

Issue a ProfileList command to the device. The `mdmAuthSignMessageMiddleware` middleware fails at `p.Parse(sig)`  (possibly a pkcs7 bug) which causes the device to get a 400 Bad Request response. 
When that happens, the device keeps resending the ProfileList response forever...

**Comment by jessepeterson** [comment]
I'm not able to repro this — I get successful response to `ProfileList` which parsed fine by the middleware. How is the ProfileList command getting generated & sent?

**Comment by AnkurGel** [comment]
`ProfileList` is working fine most of the time. However, a device sometimes is sending the ack with the signature where pkcs7 is failing. https://gist.githubusercontent.com/AnkurGel/8b0e169e646fcd20a600190570512d85/raw/e98b22f4c535ad84339f71b7050323dc84227bae/gistfile1.txt This is such mdm-signature.

**Comment by jessepeterson** [comment]
Hmm. OpenSSL parses the PKCS7 fine, and its dump of the ASN1 data seems fine. Wish I could repro it. :) Some questions:

* Where does it fail on the signature? The first check-in? The command response?
* Is this iOS or macOS?
* Do you have other profiles installed?
* If you take out the middleware, do you get successful replies? Do they look normal?

**Comment by jessepeterson** [comment]
Indeed as @groob suspected `fullsailor/pkcs7` is getting an error upon Parse:

> ber2der: BER tag length is more than available data

OpenSSL's PKCS7 handling doesn't seem to have this issue.

**Comment by AnkurGel** [comment]
> Where does it fail on the signature? The first check-in? The command response?

Command response.

> Is this iOS or macOS?

iOS

> Do you have other profiles installed?

As in, on other devices? Yes. They work normal

> If you take out the middleware, do you get successful replies? Do they look normal?

Yes. It passes if I take the middleware out. Infact, I'm running a binary after excluding the check.

It breaks [here](https://github.com/micromdm/micromdm/blob/master/serve.go#L816) inside [`ber2der`](https://github.com/fullsailor/pkcs7/blob/master/ber.go#L57)

**Comment by jessepeterson** [comment]
On a whim I decided to try @addie9000's fix in fullsailor/pkcs7#17. This successfully parsed your command response. I'll add our +1 note to that project.

**Comment by jessepeterson** [comment]
@AnkurGel let us know with the new p7 deps if you still see this issue!

**Comment by jessepeterson** [comment]
Have not heard of a re-occurrence of this issue. Presuming the updated pkcs7 lib in #213 solved issue. Closing.
