### ISSUE TITLE
Support profile signing

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#212]
```
	// TODO: support CMS signed profiles
```

Let's do this for the next milestone.

**Comment by jessepeterson** [comment]
The mentioned TODO was addressed in #218. However the larger issue of MicroMDM itself supporting actual signing of profiles, including its own e.g. enrollment profiles may still be a discussion. PR #214 addresses the latter concern (supplying/modifying the enrollment & OTA profiles), but when MicroMDM wants to e.g. auto-sign profiles and such may still be a discussion.

**Comment by jessepeterson** [comment]
I believe this was resolved with #602.
