### ISSUE TITLE
Add per user connections to ServerCapabilities in the enroll profile

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#221]
```
ServerCapabilities:  []string{"com.apple.mdm.per-user-connections"},
``` 

line 95 of `enroll/service.go`

Without that configuration, the AwaitDeviceConfigured mode is always `false`, even if configured correctly in the DEP profile. 

This should probably be a radar because the dependency between the two is not documented anywhere.

**Comment by jessepeterson** [comment]
Thanks for remembering that! Still had un-staged changes from PSU! :)
