### ISSUE TITLE
forward all device responses to  a callback url

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#223]
Opening this to track the proposal from #216. 

The gist of the issue: until we have a good implementation that exposes pubsub, it might be useful to tee all device responses to a remote url. This can be accomplished through an HTTP middleware around `/connect`. 

In #216 we briefly discussed if the forwarded messages should be JSON or PLIST. 
JSON is potentially more convenient for someone implementing the webhook. On the other hand PLIST will be more accurate because that's what the device already sends.
I think we can parametrize the middleware such that both are accepted.

**Comment by Beanow** [comment]
Had a glance at the milestones, is this part of https://github.com/micromdm/micromdm/milestone/4 (v1.5.0)?

**Comment by groob** [comment]
it is now

**Comment by Beanow** [comment]
Cool, just checking if it's the same concept we're talking about.

Additionally I discussed this feature with a colleague and we think some type of white-listing may be appropriate for the callback functionality. Not just to prevent chatter over the network, but also because some responses are potentially sensitive. Clearly the secrets during checkin are, but other information like device location may not be part of the functionality you're building and would better never be forwarded.

**Comment by groob** [comment]
The callback url/webhook is sort of a simplification of a different but much wider idea we've had on the roadmap since the beginning. 

https://docs.google.com/drawings/d/1B4w5xOmU-7D5pcW0kdiY7ia5fl7UnBfRpWR8KxzD1YI/edit?usp=sharing

It boils down to the `pubsub` package, which we want to expose over a implementation like [NSQ](http://nsq.io/) where all internal components are actually using that as the message bus, so it's becomes up to you to write additional services with equal power to the "core" server. 

This idea has been on the roadmap for over a year, and all internal components already communicate this way, but exposing this capability to other processes is only becoming a priority as of recent. 

MicroMDM would definitely benefit from a `DESIGN.md`. The good news is that i finally have more time to devote to the project so all these things are coming. We also started doing semi-official monthly "office-hours" -- an online meetup for interested parties. I've announced the last one in the slack channel, but I'll try to make the next event a bit more public to get the word out there.

**Comment by Beanow** [comment]
I see, so a "privileged" consumer would be connected to the NSQ where we'd put the white-listing step.
Having this callback URL feature built-in to the micromdm stack then would be the mean-time solution right?

**Comment by groob** [comment]
It might be a short term solution but ideally the callback functionality is just a implementation of webhooks powered by the pubsub system described in that document. 

webhooks are useful because they're a lower barrier to entry for development. 

The whole message bus idea is there because you could do some very powerful by implementing the PubSub interface as an AWS SNS queue and using that to trigger Lambda functions which extend the MDM.
