### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#249]
Provide an option to start the server with PostgreSQL persistent stores and expose PubSub over [NSQ](http://nsq.io/)

Future implementations could also add cloud specific implementations, for example for GCP:

GCP Datastore for persistence.
GCP Pubsub for the message queue.
A single binary can initialize with those dependencies instead of the boltdb backed dependencies. 

The first implementation will be hard as both the store and message queue need to be exposed simultaneously, but future ones will have a better defined interface.

**Comment by jessepeterson** [comment]
I think an intermediate storage layer/abstraction needs to be devised. Right now BoltDB is hardcoded for many/all of the modules and that needs to be de-coupled and abstracted away so any arbitrary storage backend can be developed, including Postgres or any other K/V store.

**Comment by groob** [comment]
I created a project to track the progress of this issue, and began by breaking down the cleanup necessary for each package into individual issues. 

Closing this relatively vague issue in favor of tracking all work through the project/milestone https://github.com/micromdm/micromdm/projects/3
