### ISSUE TITLE
mdmctl: LastSeen not updated often enough

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#251]
It appears that LastSeen is only updated during a TokenUpdate, not during regular check-ins. 

LastSeen should be populated as often as the device reports to `/mdm/connect`

**Comment by jessepeterson** [comment]
This probably implies having a new tracking key. The key in the code is called `LastCheckin` which implies, well, last Checkin (and in fact we removed add'l non-checkin loggings here: 8b36409f2061a34ffcd39cacb662439803388699). Perhaps we make a new LastSeen tracking key or something similar. @opragel had asked about 'last enrollment' (in case of multiply-enrolled single devices where we've seen them in DEP or enrollments before). All sorts of accounting checkin dates stamps can be envisioned. The age-old debate of where do we draw the line between 'platform' functionality and 'MDM product' functionality. :)

**Comment by groob** [comment]
LastEnrollment also goes with "First Seen" #226
