### ISSUE TITLE
enroll service never saves the enroll profile

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#252]
We check if it exists, but never save the enrollment profile in the profile db.
https://github.com/micromdm/micromdm/blob/665e2b8bcccacb5fb9f619fd238ca0f39a5487ec/enroll/service.go#L156-L167

Due to this bug, `mdmctl get profiles` never returns the enroll profile.

**Comment by groob** [comment]
I'm realizing that this might not actually be a bug, and that @jessepeterson intended for the profile to be manually added if the admin wanted to override. 

`mdmctl apply profiles -f /path/to/your/enroll.mobileconfig`

**Comment by groob** [comment]
Relabeled this as discussion to get some confirmation. If my intuition is correct, we just need to document this.

**Comment by jessepeterson** [comment]
@groob: yep, that's true, dynamic unless over-ridden by the admin. this is what unlies the suggestion in #231 to allow that person to adjust the enrollment profile to remove a certificate if they want.

**Comment by groob** [comment]
Ok I'm cool with that. I'm going to write up a little doc and close this issue.

**Comment by jessepeterson** [comment]
I'm not sure how long it can/should be sustained like this though — especially as we come up with techniques to dynamically generate a SCEP challenge we're going to need find a way to either merge with/modify an admin's profile or have a dynamic enough configuration to specify all the details to assemble a dynamic configuration profile. This was a sort of a stop-gap in-between situation.

**Comment by groob** [comment]
Closing the issue since this is possible today but I will update the documentation.
