### ISSUE TITLE
Implement a read-only boltdb repl

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#253]
Inspired by https://github.com/belak/nut/tree/cf6e29a158669b8621331a27380c18a9ee2d6596/cmd/nutdb 

I think this can make great tooling for exploring the current DB state.

**Comment by knightsc** [comment]
I've been trying out this one:

https://github.com/br0xen/boltbrowser

It's pretty nice for just getting a quick look at the buckets and keys since the values are binary they don't display as nice but still useful

**Comment by groob** [comment]
I don't think this is necessary anymore.
