### ISSUE TITLE
Support user-targeted MDM

### ISSUE THREAD

**Issue by jessepeterson** [micromdm/micromdm#274]
Allow sending MDM commands to the user-specific UDID that is generated for the MDM user on checkin.

**Comment by jessepeterson** [comment]
Is this truly closed? Do we have a way to target profiles, other commands, etc. to user UUIDs in Blueprints?

**Comment by groob** [comment]
In blueprints no. but it all works via the API. 

Let's open a separate issue for modifying blueprints to target users vs devices in a blueprint and how that will look like.
