### ISSUE TITLE
command: move archive functionality out of package.

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#299]
Same as #298 

A few possible ways to go here:

create an archiver interface, using the current boltdb as an implementation.
(IMO this is best, but might take more work) move the event archiving into a separate service which relies on pubsub to receive all the events.

**Comment by groob** [comment]
Bolt is now out of this package.

**Comment by jessepeterson** [comment]
i think relevant commit is c1c1cfb17572c21d760fc73b874c05cd2e10e7bd
