### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by Beanow** [micromdm/micromdm#311]
~Is there one? And if not, can we provide it?~

Edit: can we re-implement Docker builds with official releases being tagged?

**Comment by Beanow** [comment]
I see there is something here: https://hub.docker.com/r/micromdm/micromdm/tags/
However it's outdated, has no tagged releases and it's Dockerfile does not show up in this repo.

**Comment by groob** [comment]
This needs to be added. Thanks for filing an issue.

**Comment by groob** [comment]
Closed by #316 

I will push a release up soon.
