### ISSUE TITLE
unenroll device

### ISSUE THREAD

**Issue by DanijelBumbar** [micromdm/micromdm#312]
### What version of `micromdm` are you using?
version 1.2
### What `micromdm` command did you run?
there is no command for that yet
### What did you expect to see?
I expected to unenroll device just with /push/{udid}
### What did you see instead?
nothing

**Comment by jessepeterson** [comment]
@DanijelBumbar just for clarification are looking to unenroll a device on the client-side or on the micromdm side? Or perhaps both?

**Comment by DanijelBumbar** [comment]
@jessepeterson 
I need to send a command to the Server and then it should be automatically deleted. That is server side what I understood.
I am aware that clients on their devices can delete profile, if you thought on that.

**Comment by groob** [comment]
Closed by https://github.com/micromdm/micromdm/pull/342

https://github.com/micromdm/micromdm/wiki/Terminating-a-Management-Relationship-with-a-device-block
