### ISSUE TITLE
Dual initialization of depClient()?

### ISSUE THREAD

**Issue by jessepeterson** [micromdm/micromdm#329]
### What version of `micromdm` are you using?
master:HEAD

### What `micromdm` command did you run?
n/a

### What did you expect to see?
Should we be reusing the same DEP client? It doesn't look like we have a singleton pattern anywhere unless I'm missing something. The two invocations:

https://github.com/micromdm/micromdm/blob/e3348a9a301a250310f3dd663f5978cbd5592b09/serve.go#L259

and

https://github.com/micromdm/micromdm/blob/e3348a9a301a250310f3dd663f5978cbd5592b09/serve.go#L816

### What did you see instead?
One call to initialize the DEP client, saving a reference to the service and reusing? But it feels like I'm missing something.

**Comment by groob** [comment]
Yikes

**Comment by jessepeterson** [comment]
Okay, wasn't just me, then. :) I thought there might have been some sort of reason for separation of duties or decoupling or something that wasn't obvious to me.
