### ISSUE TITLE
panic: runtime error when trying to apply an invalid DEP profile template

### ISSUE THREAD

**Issue by hewisaurus** [micromdm/micromdm#331]
### What version of `micromdm` are you using?\
1.2.0

### What `micromdm` command did you run?
mdmctl apply dep-profiles -f /path/to/profile.json

### What did you expect to see?
Defined DEP Profile with UUID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

### What did you see instead?
On the micromdm side:
`---BEGIN Response---
HTTP/1.1 500 Internal Server Error
Connection: close

{
 "error": "DEP API Error: FLAGS_INVALID"
}

---END Response---`

On the mdmctl side:
` mdmctl apply dep-profiles -f /path/to/profile.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6ddd9a]

goroutine 1 [running]:
main.(*applyCommand).applyDEPProfile(0xc4200da3e0, 0xc42000e170, 0x2, 0x2, 0x0, 0x0)
        /Users/victor/go/src/github.com/micromdm/micromdm/cmd/mdmctl/apply_dep_profile.go:98 +0x6fa
main.(*applyCommand).(main.applyDEPProfile)-fm(0xc42000e170, 0x2, 0x2, 0xc, 0x18)
        /Users/victor/go/src/github.com/micromdm/micromdm/cmd/mdmctl/apply.go:57 +0x48
main.(*applyCommand).Run(0xc4200da3e0, 0xc42000e160, 0x3, 0x3, 0x7ffdc8a44701, 0xc4200da3e0)
        /Users/victor/go/src/github.com/micromdm/micromdm/cmd/mdmctl/apply.go:68 +0x14a
main.(*applyCommand).Run-fm(0xc42000e160, 0x3, 0x3, 0x5, 0x767960)
        /Users/victor/go/src/github.com/micromdm/micromdm/cmd/mdmctl/mdmdctl.go:34 +0x48
main.main()
        /Users/victor/go/src/github.com/micromdm/micromdm/cmd/mdmctl/mdmdctl.go:46 +0x1a5`

According to apple under [Request-specific errors](https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/MobileDeviceManagementProtocolRef/4-Profile_Management/ProfileManagement.html) it's supposed to return a 400 but saw a 500 instead.

**Comment by groob** [comment]
I want to make 2 fixes for this bug:

1) detect the incompatible values in the template in `mdmctl` even before sending the request. The flags are arbitrary, and we can warn the user.

2) detect and handle the API error from apple.com
