### ISSUE TITLE
Get devices (and most other successful commands) should output to Stdout, not Stderr

### ISSUE THREAD

**Issue by jessepeterson** [micromdm/micromdm#356]
### What version of `micromdm` are you using?

v1.2.0 from releases page.

### What `micromdm` command did you run?

mdmctl get devices

### What did you expect to see?

Output on Stdout (to be able to further pipe command)

### What did you see instead?

Output on Stderr (making 'standard' piping a PITA)

Code here: https://github.com/micromdm/micromdm/blob/master/cmd/mdmctl/get.go#L126

**Comment by groob** [comment]
ha yes!. I've failed to grep a bunch because of this.

**Comment by thepriefy** [comment]
I just created a PR for this. I changed only "os.Stderr" in "log.NewLogfmtLogger" and "tabwriter.NewWriter" function. Do I need to change it for "fmt.Fprintf" command?

For example,
`fmt.Fprintf(os.Stderr, "%v\n", err)`
