### ISSUE TITLE
Profile Signed by "Not Signed"

### ISSUE THREAD

**Issue by EssoDev** [micromdm/micromdm#362]
iPhone shows "Signed by   Not Signed" when enrolling device. The mdm session works properly anyway and I'm able to manage my devices.
But now I've been trying to read how to sign the DEP profile, but I haven't succeeded. Is it even possible?

**Comment by clburlison** [comment]
Right now micromdm does sign the enrolllment profile. Can you try the following article? https://github.com/micromdm/micromdm/wiki/Sign-the-enrollment-profile-with-Hancock

**Comment by EssoDev** [comment]
Thanks, the hancock project solved my problem.
