### ISSUE TITLE
Enrollment profile rejected by iOS due to invalid topic

### ISSUE THREAD

**Issue by larsar** [micromdm/micromdm#366]
### What version of `micromdm` are you using?
Tested with 1.2.0 binary and master, with the same result.

### What `micromdm` command did you run?
sudo build/linux/micromdm serve -http-debug -apns-cert ~/mdm.p12 -apns-password=redacted -server-url=https://mdm.mydomain -filerepo /home/ubuntu/pkg/ -tls-cert ~/mdm_mydomain.pem -tls-key ~/mdm_mydomain.key.pem

### What did you expect to see?
Succssfully a Mac by visiting https://mdm.mydomain/mdm/enroll
Expected that I could enroll an iOS device the same way

### What did you see instead?
When visiting the enrollment URL with Safari on iOS, I was prompted to accept the enrollment profile. After accepting, I got an error message about an "unknown error". The profile was not installed. 

The device logs indicates that the **topic** is invalid. See attached log and profile.

According to the documentation, the Topic must have a specific prefix.
https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/MobileDeviceManagementProtocolRef/3-MDM_Protocol/MDM_Protocol.htm

>  Topic | String |Mandatory. The topic that MDM listens to for push notifications. The certificate that the server uses to send push notifications must have the same topic in its subject. The topic must begin with the com.apple.mgmt. prefix.

The enrollment profile contained a topic without the _com.apple.mgmt_ prefix.
```
<key>Topic</key>
<string>95PAURT649</string>
``` 

[device.log](https://github.com/micromdm/micromdm/files/1641809/device.log)
[enrollment_profile.txt](https://github.com/micromdm/micromdm/files/1641811/enrollment_profile.txt)

**Comment by jessepeterson** [comment]
@larsar where did you get your push certificate?

**Comment by larsar** [comment]
Got it from Apple, but I guess that 

```

**Comment by larsar** [comment]
Yes, reading the [micromdm certificates](https://micromdm.io/blog/certificates/) docs now and it's clear that I'm using the wrong certificate. 

It might be an improvement if Micromdm could validate the certificate type and give an appropriate error message.

**Comment by jessepeterson** [comment]
@larsar that's a great suggestion. Can you open a new issue to add that validation?
