### ISSUE TITLE
Validation of push certificate on mdm startup

### ISSUE THREAD

**Issue by larsar** [micromdm/micromdm#367]
It's possible to run _micromdm serve -apns-cert cert_and_key.p12_ even though the p12 file contains a certificate that is not a push certificate. If the wrong type of certificate is used an iOS client will reject the enrollment profile.

It would be helpful for the user if the micromdm refuse to start unless the certificate is a "push certificate". 

Issue #366 shows the result of starting the mdm with a vendor certificate (aka CSR certificate) instead of a signed push certificate.

**Comment by jessepeterson** [comment]
We should also fail to provide an enrollment profile if the Topic (APNs cert) is missing.
