### ISSUE TITLE
Feature Request: Disable the ability for the webpage to display "Enroll"

### ISSUE THREAD

**Issue by WardsParadox** [micromdm/micromdm#369]
### What version of `micromdm` are you using?
V1.2.0
### What `micromdm` command did you run?
N/A
### What did you expect to see?
N/A
### What did you see instead?
N/A

If there was a flag that could be used to disable the webpage interface from showing "enroll this device" or requiring a login, it would help secure enrollments.

**Comment by groob** [comment]
Related https://github.com/micromdm/micromdm/issues/310
