### ISSUE TITLE
Add api call after device enrollment

### ISSUE THREAD

**Issue by axlroden** [micromdm/micromdm#375]
We have apple TV's that we wipe regularly.

Upon re-enrollment (or initial enrollment) we would like to send devicename to the device.

This could be added to blueprints as a seperate "commands" area. 

This would require a json with the actual call to /v1/commands for each udid/serial to be stored somewhere for micromdm to access.

fx:

```
{
	"settings": [
		  {
			"device_name": "testing", 
			"item": "DeviceName"
		  }
		],
	"request_type": "Settings",
	"udid": "495a51336b86aeb9cada62adcf7383d142d2292c"
}
´´´

**Comment by jessepeterson** [comment]
The [4th milestone](https://github.com/micromdm/micromdm/milestone/4) (message bus implementation, see also #370 and others) is planned to allow you to develop workflows like this yourself. You'd be able to receive the event that represents device enrollment and perform any actions that you would like. We do also plan on fleshing out the Blueprints capability with arbitrary device selection as well, but this is not currently on the roadmap.

For the short term you could keep track of new udids and wiped udids to mimic the workflow you've described here. I.e. when seeing a new or wiped device's UDID send the commands, via the API, that you would like.

**Comment by axlroden** [comment]
That would be visible in logs, is there any other way of tracking it ?

**Comment by jessepeterson** [comment]
Sure, if you use the command webhook you'll get command responses (in XML plist form) that include the UDID from every device's command response. If you see a new UDID you haven't seen before (or a device that you've wiped before) - send it a Device name API command.

**Comment by axlroden** [comment]
Sorry, there will only be a plist sent ack'ing my wipe. There is no plist sent when the device re-enrolls.

**Comment by axlroden** [comment]
adding a webhook on re-enrollment would work for me as well

**Comment by jessepeterson** [comment]
But you do get a command responses after a wipe. That's how you know a device has enrolled. Since you know it was wiped, once you see either the same or a new UDID you can assume it is a newly enrolled device.

**Comment by axlroden** [comment]
the micromdm logs shows a reenrollment, but there is no plists when that happens.

**Comment by jessepeterson** [comment]
Right, but you can infer it. MicroMDM tells you when a device gets a command response. If you know a device has been wiped, and you see a command response over the API you know the device has re-enrolled and you can send whatever command you like.

**Comment by axlroden** [comment]
yes, I know this, but I have to wait 1 - 2 mins before the device is rebooted and back up again before I can send a new command. (re)enrollment message happens after its done wiping and is inside the OS again ready for commands.

**Comment by jessepeterson** [comment]
Right, so listen to the command response after the device reboots. This conversation is pretty back-and-forth. If you wanna chat more about what you're able to do you may want to come into #micromdm in the [macadmins slack](https://macadmins.herokuapp.com/) and we can discuss there.

**Comment by groob** [comment]
Check-Ins are not exposed via webhook like commands, but that doesn't mean they shouldn't be. This should be working once the message bus is exposed. We already have all these topics internally.

**Comment by jessepeterson** [comment]
Not yet, no. But you can still infer device enrollments. I'm doing it.

**Comment by knightsc** [comment]
I'm going to mark this as closed. I think with the completion of https://github.com/micromdm/micromdm/pull/424 the Check-Ins are now exposed via the webhook
