### ISSUE TITLE
API /v1/push/{udid} runs into 404

### ISSUE THREAD

**Issue by ThePutzy** [micromdm/micromdm#393]
### What version of `micromdm` are you using?
micromdm version v1.2.0-32-g979f32b

### What `micromdm` command did you run?
API Endpoint: /v1/push/{udid}

### What did you see instead?
404 page not found

**Comment by groob** [comment]
There's no `v1/` for the push endpoint. It's just `GET /push/:udid`

I started adding API commands to the `tools/api` folder of the repo. See the [README](https://github.com/micromdm/micromdm/tree/f843041cbc30a2ccd19df88e2aeb4c72fe4f36e4/tools/api) for how to use them.
Hope that helps!

**Comment by ThePutzy** [comment]
Ok, thanks.

i've seen this in micromdm/platform/apns/server.go:
`
func MakeHTTPHandler(e Endpoints, logger log.Logger) *mux.Router {
	r, options := httputil.NewRouter(logger)

	// POST   /v1/push/:udid	create an APNS Push notification for a managed device or user

	r.Methods("POST").Path("/v1/push/{udid}").Handler(httptransport.NewServer(
		e.PushEndpoint,
		decodePushRequest,
		httputil.EncodeJSONResponse,
		options...,
	))

	return r
}
`

But it's not finsihed, right?

**Comment by groob** [comment]
Ah yes. That's there for a future release. I have to change the routing for a few paths, but the main router still loads the GET route.

**Comment by ThePutzy** [comment]
Ah ok, thank you to understand :-).
If you want, you can close ;-)
