### ISSUE TITLE
Deprecate apns serve switches

### ISSUE THREAD

**Issue by jessepeterson** [micromdm/micromdm#417]
#414 added warnings. This is just a reminder issue to actually remove the apns switches altogether. Perhaps in 1.4.0?

**Comment by groob** [comment]
removing these is good now. I created a branch for 1.3.x where I will cherrypick bugs until 1.3 is stable, and that still has the flags. 

Master is now tracking feature development for 1.4 so we can safely delete the APNS flags from main.
