### ISSUE TITLE
Error enrolling on macOS 10.12.6

### ISSUE THREAD

**Issue by knightsc** [micromdm/micromdm#436]
### What version of `micromdm` are you using?

v1.3.0
commit 25a07b82b5407a1115b6cf6770716cfdc43c9719

### What `micromdm` command did you run?

Attempted to enroll from a macOS 10.12.6 machine. The server was running through ngrok using the ngrok instructions. The default enrollment profile was being used and a blueprint was set to push out two profiles

### What did you expect to see?

The machine to enroll in mdm

### What did you see instead?

A Profile installation failed error from macOS on the client machine. The profile could not be installed due to an unexpected error. <NSOSStatusErrorDomain: -603

In the console logs of the client there is this additional info

```
[ERROR] <: [MDM_SCEP_Enroll] Calling SCEPRequestCertSignature --> <NSOSStatusErrorDomain:-603>
```

and the following on the server

```
transport=http method=GET status=200 proto=HTTP/1.1 host=::1 user_agent="mdmclient/960 CFNetwork/811.9 Darwin/16.7.0 (x86_64)" path="/scep?operation=GetCACert&message=Device%20Management%20Identity%20Certificate"
method=PKIOperation err="invalid data len 0" took=4.216921ms
invalid data len 0
transport=http err="invalid data len 0"
transport=http method=POST status=500 proto=HTTP/1.1 host=::1 user_agent="mdmclient/960 CFNetwork/811.9 Darwin/16.7.0 (x86_64)" path="/scep?operation=PKIOperation"
```

So it looks like the POST to /scep is returning a 500 Internal Server Error for the reason of `invalid data len 0`

**Comment by jessepeterson** [comment]
I'm not able to reproduce this error. I'm running `master` (same build above, 25a07b82b5407a1115b6cf6770716cfdc43c9719) and I can successfully enroll a 10.12.5 (yes, .5 oddly — old machine). I'll test a fresh 10.12.6 VM here in a sec.

**Comment by jessepeterson** [comment]
Can confirm — seeing same issue in new 10.12.6 VM. No ngrok.

**Comment by jessepeterson** [comment]
Reasonably sure this is related to fullsailor/pkcs7#31. We've integrated that fix/patch into @groob's pkcs7 fork: groob/pkcs7@f41fa115eb76823dcfb8c45678da0fb6d7ecb792. Updated micromdm/scep#87 here and then need to integrate that into the mainline project here.
