### ISSUE TITLE
Profile installation failed

### ISSUE THREAD

**Issue by davisbra** [micromdm/micromdm#453]
### What version of `micromdm` are you using?
1.30

I downloaded the source code and built micromdm from its own source ,when I try to enroll a device the following error appears in my iphone(ios 11.2):
Profile Installation Failed The SCEP server returned an invalid response.
but when I want to use the built version micromdm(downloaded from releases) I don't  confront with this error.
what can I do to resolve this problem?

**Comment by knightsc** [comment]
@davisbra Can you confirm what commit you're using? Prior to this commit 1593d130e76b5792e22cc426e5ca330eb0c9ce98 there was an issue with enrolling on iOS. If you have the latest code from master 8ab19a93e810f6360503b5baf872b440b2f16c8f make sure to do a `make deps` to pull in the updated code dependencies and then try rebuilding/retesting

**Comment by groob** [comment]
I can repro this with master. 

```
method=PKIOperation err=null took=12.38663ms
component=scep op=PKIOperation error=null took=12.403352ms
component=scep method=POST status=200 proto=HTTP/1.1 host=::1 user_agent="profiled/1.0 CFNetwork/901.1 Darwin/17.6.0" path="/scep?operation=PKIOperation"
transport=http method=POST status=200 proto=HTTP/1.1 host=::1 user_agent="profiled/1.0 CFNetwork/901.1 Darwin/17.6.0" path="/scep?operation=PKIOperation"
```

I'll dig into why this is happening today.
