### ISSUE TITLE
Signature verification error during enrollment

### ISSUE THREAD

**Issue by mattlqx** [micromdm/micromdm#460]
### What version of `micromdm` are you using?
1.3.1

### What `micromdm` command did you run?
/micromdm serve -server-url=https://XXX -filerepo /repo -config-path /config -api-key XXX -tls=false -http-debug

(TLS is provided by the Kubernetes cluster in which this container is running)

### What did you expect to see?
Successful enrollment of the macOS laptop.

### What did you see instead?
The laptop appears to go into a loop after installing the enrollment profile with the error `err="read acknowledge request body: verify signature: verify MDM Signed Message: crypto/rsa: verification error`. See https://gist.github.com/mattlqx/38104810c8db5f089aab7bd04e773a50 for a more complete request log.

I'm not sure if this is somehow related to the push certificate (which I've uploaded using `mdmctl mdmcert upload -cert ~/Downloads/MDM_\ McMurtrie\ Consulting\ LLC_Certificate.pem -private-key mdmcert.download.push.key`). I believe it is done correctly though.

**Comment by knightsc** [comment]
@mattlqx What version of macOS is this on?

**Comment by mattlqx** [comment]
Latest, 10.13.6

**Comment by jessepeterson** [comment]
This doesn't have much to do with the Push Certificate. This is a problem with the device identity certificate (i.e. the SCEP cert) and how it's being used to communicate with MDM. It basically means the HTTP body doesn't match included Mdm-Signature header PKCS#7 header. I wonder if that's due to some sort of proxying or modification of the request that your stack is playing with?

**Comment by mattlqx** [comment]
It looks like I've found the problem. I had a blueprint that referenced the `com.github.micromdm.micromdm.enroll` profile. I thought this linked the blueprint to a given enrollment profile, but I see now that this specifies additional profiles to be installed. Putting that ID in the blueprint results in this failure loop. Removing it results in everything working.

Here's what was causing a problem.
```
{
  "uuid": "73f2f706-3031-4f20-abb4-7f39f95fbfab",
  "name": "Engineering",
  "install_application_manifest_urls": [
    "https://mdm.example.com/repo/mypackage.plist"
  ],
  "profile_ids": [
    "com.github.micromdm.micromdm.enroll"
  ],
  "user_uuids": null,
  "skip_primary_setup_account_creation": false,
  "set_primary_setup_account_as_regular_user": false,
  "apply_at": [
    "Enroll"
  ]
}
```

**Comment by jessepeterson** [comment]
Oh, that's really fun! You were basically re-enrolling your MDM server (by re-sending the MDM enrollment profile) as one of the blueprint steps! Theoretically you should be able to re-enroll at any time, but I could totally see some timing issues having that be the first profile off the mark!
