### ISSUE TITLE
Error in /v1/devices call

### ISSUE THREAD

**Issue by ThePutzy** [micromdm/micromdm#461]
### What version of `micromdm` are you using?
`micromdm version v1.3.1`

### What `micromdm` command did you run?
API: `/v1/devices`

### What did you expect to see?
A list of enrolled devices

### What did you see instead?
```
{
    "error": "EOF"
}
```

**Comment by groob** [comment]
This is a bug, but the GET request requires a body. 
Example here: https://github.com/micromdm/micromdm/blob/d7f07bb02218e2a00a59ad783c8b79121efc507d/tools/api/get_devices#L4
