### ISSUE TITLE
url_params in checkin or connect

### ISSUE THREAD

**Issue by ThePutzy** [micromdm/micromdm#462]
### What version of `micromdm` are you using?
`micromdm version v1.3.1`

### What `micromdm` command did you run?
`/mdm/checkin` or `/mdm/connect`

The response of the webhook has changed to JSON and now it's a key "url_params" in data.
I've tested many things but i have never get filled this, is it not supported or how can it be filled in connect or checkin?

```
{
  "topic": "mdm.TokenUpdate",
  "event_id": "aab836d7-6934-4ac2-9039-6e441489e2fd",
  "created_at": "2018-07-17T14:09:19.917530216Z",
  "checkin_event": {
    "udid": "***",
    "url_params": null,
    "raw_payload": "***"
  }
}
```

**Comment by groob** [comment]
The URL params are only available if your enrollment profile has ServerURL configured to have additional url parameters.

`/mdm/connect?id=foo` for example. 

Are you setting URL params in your enrollment profile? 
What are you trying to accomplish?

**Comment by ThePutzy** [comment]
the param is visible in syslog:
`micromdm[4508]: transport=http method=PUT status=200 proto=HTTP/2.0 host=217.92.72.57 user_agent=MDM/1.0 path="/mdm/connect?id=foo"`

But no params in JSON response:
```
{
  "topic": "mdm.Connect",
  "event_id": "cf5652aa-be73-4108-9024-77f1e6e45f4d",
  "created_at": "2018-07-18T05:40:39.988286575Z",
  "acknowledge_event": {
    "udid": "***",
    "status": "Idle",
    "command_uuid": "",
    "url_params": null,
    "raw_payload": "***"
  }
}
```

**Comment by 000amorfo** [comment]
@groob what you exactly mean with
*The URL params are only available if your enrollment profile has ServerURL configured to have additional url parameters.*

is there a documented way to get this?

I need to pass a parameter when a device enrolls to the server to classify the devices in a determined of group,
I think that's the goal of ulr_params, am I right?

ty so much

**Comment by jessepeterson** [comment]
@000amorfo not 100% familiar with this feature, but I think that means you need to modify the enrollment profile before you hand it to a device.
