### ISSUE TITLE
ClearPasscode Error 502

### ISSUE THREAD

**Issue by davisbra** [micromdm/micromdm#468]
when I use curl with "request_type": "ClearPasscode" there is appear following error :
<key>ErrorChain</key>
        <array>
                <dict>
                        <key>ErrorCode</key>
                        <integer>502</integer>
                        <key>ErrorDomain</key>
                        <string>Catalyst.error</string>
                        <key>LocalizedDescription</key>
                        <string>Server session invalidated.</string>
                </dict>
        </array>
        <key>Status</key>
        <string>Error</string>
How can i Fix this Error?
Thanks

**Comment by groob** [comment]
502 is usually a proxy error. Is there a proxy in front of MicroMDM?
