### ISSUE TITLE
Failure to upload Push certificate using mdmctl mdmcert upload

### ISSUE THREAD

**Issue by pmamberti** [micromdm/micromdm#470]
### What version of `micromdm` are you using?
`1.3.1`

### What `micromdm` command did you run?
`$ mdmctl mdmcert upload -cert="/Users/admin/Downloads/MDM_McMurtrie_Consulting LLC_Certificate.pem" -private-key=mdmcert.download.push.key`

### What did you expect to see?
The Push Certificate is uploaded correctly

### What did you see instead?
Client side: 
```
upload push certificate and key to server: expected JSON formatted error, got Content-Type text/plain; charset=utf-8
```

Server Side:
```
transport=http method=PUT status=404 proto=HTTP/2.0 host=<IP> user_agent=Go-http-client/2.0 path=/v1/config/certificate
```

**Comment by pmamberti** [comment]
Indeed. Thanks for following up @knightsc, I forgot to close.

**Comment by angelacelucenter** [comment]
Hello, I have the same bug when uploading the Push certificate.

What version of micromdm are you using?
1.10.1

What did you see instead?
Client side:

upload push certificate and key to server: expected JSON formatted error, got Content-Type text/plain; charset=utf-8

 and i can't enter the url: https://macadmins.slack.com/archives/C19RTE0L9/p1532473614000045 
 of @knightsc

**Comment by pmamberti** [comment]
Hey @angelacelucenter you can get invited to the macadmins slack here: https://www.macadmins.org/
