### ISSUE TITLE
How can I pass a parameter through the URL to the server or the the webhook

### ISSUE THREAD

**Issue by 000amorfo** [micromdm/micromdm#475]
I want to pass an identifier (an argument) to the micromdm server or to the webhook, what exactly do I have to do? is there any problem with the version that I'm using currently?
How can I get this value in the url_params of the payload?
thanks a lot

**Comment by jessepeterson** [comment]
@000amorfo I left you a comment in #462. I think you need to modify the enrollment profile that is delivered to devices.

**Comment by 000amorfo** [comment]
@jessepeterson Can you be more descriptive please?

**Comment by jessepeterson** [comment]
@000amorfo sure! So a device enrolls into MDM using a Configuration Profile which is an XML property list. MicroMDM hands one of these out when you visit the `/mdm/enroll` endpoint, but you can deliver it to the device anyway you like. It's just an XML file — open it up take a look at the contents. One of the properties in that Profile is a "Server URL" string. This is where you would 'inject' the enrollment code of your choice and, again, deliver that device however you want. Then you hand that to the client and it will forever provide that code to the MDM server each checkin event. Once the device is doing this you can then get that information out of the webhook callback.

**Comment by 000amorfo** [comment]
gotcha
thanks a lot, I will test it
It would be great If I could send the parameter from micromdm, I mean with no manipulation to the created profile but for now I will perform what you said
thanks again

**Comment by 000amorfo** [comment]
We just did it as you said, injecting the parameter to the payload and it worked fine
thank you very much
