### ISSUE TITLE
Possible to delete last command

### ISSUE THREAD

**Issue by ThePutzy** [micromdm/micromdm#491]
Only a question - if it is possible to delete the last send command?
If i submit a InstallProfile to the MDM and the device returns NotNow, but after this response i want to remove this command - is there any command for this?

And is it possible to delete old devices from micromdm database?

**Comment by knightsc** [comment]
@ThePutzy There is not currently any built in `mdmctl` command to remove a command.

There is a `mdmctl remove devices -udid <udid>` command which will delete the device record

**Comment by jessepeterson** [comment]
I wonder if this leads to a situation where we have an extra key on the command API request — something like "only_immediately" where it auto-removes a command if the doesn't doesn't Acknowledge and accept it?

@ThePutzy what would this feature allow? what were you trying to accomplish?

**Comment by ThePutzy** [comment]
I'll try to explain ;-).

We send a Profile, with InstallProfile command, to the iOS device. The response from device can be NotNow.

It can be, we want to remove the Profile, after a short time. But the device has not installed, till this Moment.

So we receive an _error_ from RemoveProfile command but after this the InstallProfile can be ACK.

For this, i think, a property like 'fireOrForget' is nice ;-).
