### ISSUE TITLE
acme/autocert: missing server name

### ISSUE THREAD

**Issue by dbrody2004** [micromdm/micromdm#494]
### What version of `micromdm` are you using?
1.3.1
### What `micromdm` command did you run?

micromdm serve -apns-cert /etc/micromdm/certs/mdm_push_cert.pem -apns-key /etc/micromdm/certs/ProviderPrivateKey.key -apns-password={redacted} -server-url=https://127.0.0.1 -filerepo /etc/micromdm/repo -config-path /etc/micromdm/config -api-key {redacted} -http-debug true

On server we run curl https://127.0.0.1/ and output is 

2018/08/24 22:45:33 -apns-cert, -apns-password, and -apns-key switches are deprecated. please transition to `mdmctl mdmcert upload` instead
component=main msg=started
level=info msg="loaded DEP config" cursor=
level=info msg="waiting for DEP token to be added before starting sync"
level=info msg="serving HTTPS using Let's Encrypt certificates" addr=:https
ts="2018/08/24 22:45:35" caller="http: TLS handshake error from 172.17.0.1:45042" msg="acme/autocert: missing server name"

**Comment by jessepeterson** [comment]
So two things. 1) Let's Encrypt is not currently working for the initial cert pull. See #408. And 2) unless you are actually serving from the same computer you're enrolling (nearly useless in a production environment) you need a real URL in the `-server-url` parameter. Let's Encryption simply won't work for 127.0.0.1.

**Comment by dbrody2004** [comment]
Thanks, got it working.  Fairly straightforward once you read the documentation.  The two videos that you and Groob did helped a lot.

**Comment by dbrody2004** [comment]
Using Let's Encrypt certificates requires renewal at minimum every 90 days.  There doesn't appear to be an option to reload the certs without killing the process and restarting it again.

**Comment by groob** [comment]
Thats common for all webservers (nginx for example). Reloading certs usually requires restarting a process.

**Comment by jessepeterson** [comment]
Is this true? This comment seems to imply renewal is automagic:

https://github.com/golang/crypto/blob/0709b304e793a5edb4a2c0145f281ecdc20838a4/acme/autocert/autocert.go#L83-L86

Isn't that one of the main benefits of having a native implementation built-in — that it can just manage the renewals for you? If it _is_ the case that it's supposed to be automagic then this issue would be better suited for the golang crypto project @dbrody2004.

**Comment by groob** [comment]
Renewal with built-in lets encrypt does refresh the certs @jessepeterson. But autocert is broken right now, forcing the user to obtain their own certs. (we should fix the autocert integration, and @knightsc has a PR for that https://github.com/micromdm/go4/pull/8). 

specifying your certs with `-tls-*` has no means of renewing certs. I'm only referring to that. Users that supply their own certs (which is everyone right now) are responsible for restarting the process too.
