### ISSUE TITLE
Blueprints platform service needs listener abstracted from builtin package

### ISSUE THREAD

**Issue by jessepeterson** [micromdm/micromdm#495]
Like the other services that recently went through this blueprints also needs to be split out.

**Comment by groob** [comment]
This is done I think.

**Comment by jessepeterson** [comment]
Not done yet. :(

**Comment by jessepeterson** [comment]
https://github.com/micromdm/micromdm/blob/f45a0469f0ae711600971495a3e44f1237147673/platform/blueprint/builtin/listener.go#L91

**Comment by groob** [comment]
That is contained within `package builtin` so it's clean enough IMO. 

On the other hand that code is in need of a refactor. I'll try to find the time this weekend to clean it up!

**Comment by jessepeterson** [comment]
Well, it doesn't really have anything to do with the builtin BoltDB stuff. Therefore it works against abstracting the persistence layout out for e.g. SQL support.
