### ISSUE TITLE
ProfileList not listing configurations

### ISSUE THREAD

**Issue by dbrody2004** [micromdm/micromdm#498]
We enrolled a client in mdm and then deleted the profile so the enrollment status shows false.  We then pushed a VPN configuration using InstallProfile from the api tools.  Following we ran the ProfileList also from api tools, but it doesn't show the configuration.  Not sure if that is default behavior as the configuration hasn't been installed on the device (since the enrollment status is false).

**Comment by groob** [comment]
This is detailed but I have no clue what you're saying still. Could you break the issue down a bit more?
(one of the problems is "profile" is an overloaded term in this space, and the word can mean different things")

**Comment by jessepeterson** [comment]
What @groob said. Why would you delete the enrollment profile (i.e. un-enroll the device from MDM) and try to send it commands? If you do that (and you're saying what I think you're saying) you can't manage the client or push anything to it anymore.

**Comment by dbrody2004** [comment]
I'm trying a different approach.  I've enrolled the device and just trying to send it a vpn.mobileconfig and that doesn't seem to work.  The mobileconfig file is a basic file created from Apple Configurator.  Even restarting or other commands show the below -

root@ip-172-31-39-54:/home/dbrody/tmp# /root/slim/wixio/Debug/mdmctl get devices
UDID                                      SerialNumber  EnrollmentStatus  LastSeen
39c0f2fd690169d358a6412a8594ba0821b0842c  DLXR22XRGHK9  true              2018-09-07 00:25:43.534391654 +0000 UTC
root@ip-172-31-39-54:/home/dbrody/tmp# 

root@ip-172-31-39-54:/home/dbrody/tmp# micromdm-master/tools/api/commands/install_profile 39c0f2fd690169d358a6412a8594ba0821b0842c vpn.mobileconfig 
{
  "payload": {
    "command_uuid": "7f133fdf-1c33-4941-852c-551148fe7872",
    "command": {
      "request_type": "InstallProfile",
      "payload": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+UGF5bG9hZENvbnRlbnQ8L2tleT4KCTxhcnJheT4KCQk8ZGljdD4KCQkJPGtleT5JUFNlYzwva2V5PgoJCQk8ZGljdD4KCQkJCTxrZXk+QXV0aGVudGljYXRpb25NZXRob2Q8L2tleT4KCQkJCTxzdHJpbmc+U2hhcmVkU2VjcmV0PC9zdHJpbmc+CgkJCQk8a2V5PkxvY2FsSWRlbnRpZmllclR5cGU8L2tleT4KCQkJCTxzdHJpbmc+S2V5SUQ8L3N0cmluZz4KCQkJCTxrZXk+U2hhcmVkU2VjcmV0PC9rZXk+CgkJCQk8ZGF0YT4KCQkJCWRHVnpkQT09CgkJCQk8L2RhdGE+CgkJCTwvZGljdD4KCQkJPGtleT5JUHY0PC9rZXk+CgkJCTxkaWN0PgoJCQkJPGtleT5PdmVycmlkZVByaW1hcnk8L2tleT4KCQkJCTxpbnRlZ2VyPjE8L2ludGVnZXI+CgkJCTwvZGljdD4KCQkJPGtleT5QUFA8L2tleT4KCQkJPGRpY3Q+CgkJCQk8a2V5PkF1dGhOYW1lPC9rZXk+CgkJCQk8c3RyaW5nPnRlc3Q8L3N0cmluZz4KCQkJCTxrZXk+QXV0aFBhc3N3b3JkPC9rZXk+CgkJCQk8c3RyaW5nPnRlc3Q8L3N0cmluZz4KCQkJCTxrZXk+Q29tbVJlbW90ZUFkZHJlc3M8L2tleT4KCQkJCTxzdHJpbmc+MTkyLjE2OC4xLjE8L3N0cmluZz4KCQkJPC9kaWN0PgoJCQk8a2V5PlBheWxvYWREZXNjcmlwdGlvbjwva2V5PgoJCQk8c3RyaW5nPkNvbmZpZ3VyZXMgVlBOIHNldHRpbmdzPC9zdHJpbmc+CgkJCTxrZXk+UGF5bG9hZERpc3BsYXlOYW1lPC9rZXk+CgkJCTxzdHJpbmc+VlBOPC9zdHJpbmc+CgkJCTxrZXk+UGF5bG9hZElkZW50aWZpZXI8L2tleT4KCQkJPHN0cmluZz5jb20uYXBwbGUudnBuLm1hbmFnZWQuODEzQzhDM0ItNUQyNi00MzMxLThFQ0QtMjkzMEFBRTMxMjhEPC9zdHJpbmc+CgkJCTxrZXk+UGF5bG9hZFR5cGU8L2tleT4KCQkJPHN0cmluZz5jb20uYXBwbGUudnBuLm1hbmFnZWQ8L3N0cmluZz4KCQkJPGtleT5QYXlsb2FkVVVJRDwva2V5PgoJCQk8c3RyaW5nPkMyNjkzMTg4LTE4NjItNDk2Mi1BRjMzLTc5Q0VCREVDNzc0Qzwvc3RyaW5nPgoJCQk8a2V5PlBheWxvYWRWZXJzaW9uPC9rZXk+CgkJCTxyZWFsPjE8L3JlYWw+CgkJCTxrZXk+UHJveGllczwva2V5PgoJCQk8ZGljdD4KCQkJCTxrZXk+SFRUUEVuYWJsZTwva2V5PgoJCQkJPGludGVnZXI+MDwvaW50ZWdlcj4KCQkJCTxrZXk+SFRUUFNFbmFibGU8L2tleT4KCQkJCTxpbnRlZ2VyPjA8L2ludGVnZXI+CgkJCTwvZGljdD4KCQkJPGtleT5Vc2VyRGVmaW5lZE5hbWU8L2tleT4KCQkJPHN0cmluZz50ZXN0PC9zdHJpbmc+CgkJCTxrZXk+VlBOVHlwZTwva2V5PgoJCQk8c3RyaW5nPkwyVFA8L3N0cmluZz4KCQk8L2RpY3Q+Cgk8L2FycmF5PgoJPGtleT5QYXlsb2FkRGlzcGxheU5hbWU8L2tleT4KCTxzdHJpbmc+VW50aXRsZWQ8L3N0cmluZz4KCTxrZXk+UGF5bG9hZElkZW50aWZpZXI8L2tleT4KCTxzdHJpbmc+ZGF2ZXMtbWFjYm9vay1wcm8ubG9jYWwuMEVEMEMyRjUtMTk1Ni00NzY4LUEzMUMtNUY4MTczRTE1QkM1PC9zdHJpbmc+Cgk8a2V5PlBheWxvYWRSZW1vdmFsRGlzYWxsb3dlZDwva2V5PgoJPGZhbHNlLz4KCTxrZXk+UGF5bG9hZFR5cGU8L2tleT4KCTxzdHJpbmc+Q29uZmlndXJhdGlvbjwvc3RyaW5nPgoJPGtleT5QYXlsb2FkVVVJRDwva2V5PgoJPHN0cmluZz5GNzNCRTRENS01QTE2LTQxQTktOEI4Ri1DRUYwNkRBOTNDQ0E8L3N0cmluZz4KCTxrZXk+UGF5bG9hZFZlcnNpb248L2tleT4KCTxpbnRlZ2VyPjE8L2ludGVnZXI+CjwvZGljdD4KPC9wbGlzdD4KCg=="
    }
  }
}

root@ip-172-31-39-54:/home/dbrody/tmp# micromdm-master/tools/api/commands/profile_list 39c0f2fd690169d358a6412a8594ba0821b0842c
{
  "payload": {
    "command_uuid": "912de45c-b15e-45e9-a528-9cf71be9a4d6",
    "command": {
      "request_type": "ProfileList"
    }
  }
}

root@ip-172-31-39-54:/home/dbrody/tmp# micromdm-master/tools/api/commands/os_update_status 39c0f2fd690169d358a6412a8594ba0821b0842c
{
  "payload": {
    "command_uuid": "ca352afb-ba3f-4249-924d-845274365224",
    "command": {
      "request_type": "OSUpdateStatus"
    }
  }
}
root@ip-172-31-39-54:/home/dbrody/tmp# micromdm-master/tools/api/commands/restart_device 39c0f2fd690169d358a6412a8594ba0821b0842c
{
  "payload": {
    "command_uuid": "706ef8c4-9f28-4826-bbe8-60a534507cfd",
    "command": {
      "request_type": "RestartDevice"
    }
  }
}

**Comment by jessepeterson** [comment]
Ohh, I see. You're trying to get MDM command _results_ from the API tools CLI stuff. Yeah you won't see device responses by using the shell scripts. But you _should_ see the devices checking into the MDM via the micromdm logs.

To get command result data you'd want to setup a webhook handler. Take a look at some documentation here: https://github.com/micromdm/micromdm/wiki/Webhooks  and also take a look at @knightsc's excellent starter webhook handlers here: https://github.com/knightsc/micromdm-webhook-blueprints

**Comment by dbrody2004** [comment]
Got a webhook handler working.  Is there a command to see what *.mobileconfig files have been installed on the device?

**Comment by jessepeterson** [comment]
Sure. ProfileList, like you were using above!
