### ISSUE TITLE
run without domain name

### ISSUE THREAD

**Issue by davidjanson2020** [micromdm/micromdm#507]
is it possible to run linux version without domain address?
I want to run this app on my server ip address,How can I do that?

**Comment by jessepeterson** [comment]
MDM devices require connecting to a TLS endpoint. Which for almost all intents and purposes this means you need to specify a domain name. Further, MicroMDM needs to know how to point MDM devices at the server's address for devices to check into — so one way or another, an address is required.

Technically speaking MicroMDM itself doesn't need to run with TLS, you can use a reverse proxy to handle that part if you wish, but TLS is still required on the devices. As well you _might_ be able to run MicroMDM with a self-signed certificate using a SAN with an IP address — though I don't think anybody has tested that.

If you just want to get up and running quickly to test some features out I'd suggest taking a look at [running it with ngrok](https://github.com/micromdm/micromdm/tree/master/tools/ngrok) or [running with self-signed certs](https://github.com/micromdm/micromdm/wiki/Using-MicroMDM-with-self-signed-certificates).
