### ISSUE TITLE
can I unroll the device from micromdm?

### ISSUE THREAD

**Issue by 000amorfo** [micromdm/micromdm#509]
Hi guys
If I remove the profile from the device I can unroll the device but how can I do it from the micromdm?
thanks

**Comment by 000amorfo** [comment]
I think I found the answer but it would be better if someone can tell me something about it
This is the answer that I found

"Unless the profile is installed using the Device Enrollment Program, a user may remove the profile containing the MDM payload at any time."
link: https://developer.apple.com/enterprise/documentation/MDM-Protocol-Reference.pdf

thanks

**Comment by jessepeterson** [comment]
Yes, that's true. Only DEP can install "non-removable" enrollment profiles.

But it's worth noting that you can still remove non-removable profiles via Recovery mode on the Mac — even with a DEP non-removable profile.

**Comment by 000amorfo** [comment]
@jessepeterson thanks for the info
