### ISSUE TITLE
What type of certificates and accounts we required to implement MicroMDM ?

### ISSUE THREAD

**Issue by Lyankar** [micromdm/micromdm#511]
Hai this is Lyankar, yesterday i saw MicroMDM it's interesting. I want to implement MicroMDM to my organisation , but I have some doughs that is - 

1) Is Apple Enterprise account mandatory to implement MicroMDM ?. 

Because of we don't have that. But we  have Apple Developer account.

2) And one more is, is it completely free to develop MicroMDM to my organization ?
3) And please tel me the complete process to develop MicroMDM (Like required certificates and accounts details)

**Comment by arubdesu** [comment]
Hey Lyankar, while an Apple Enterprise account is not mandatory, it is definitely recommended. That is explained here on the wiki https://github.com/micromdm/micromdm/wiki/Quickstart#getting-an-mdm-push-certificate and more detail is provided here https://micromdm.io/blog/certificates/

Yes, it is free to use MicroMDM, the license is MIT https://github.com/micromdm/micromdm/blob/master/LICENSE

**Comment by Lyankar** [comment]
@arubdesu, thank you. Is Apple DEP account require for this?. Sorry to say this , I'm unable to understand to start MicroMDM.

**Comment by Lyankar** [comment]
Thank you @arubdesu, is there any tutorial to implement MicroMDM?

**Comment by arubdesu** [comment]
A recent talk is here https://youtube.com/watch?v=WGKT-PyHz6I an update talk is here https://www.youtube.com/watch?v=RAmc2RC4llI (there's one from the year before on the MDOYVR channel) but besides the links on the wiki https://github.com/micromdm/micromdm/wiki/Links there aren't many tutorials I am aware of.

**Comment by Lyankar** [comment]
@arubdesu Thank you very much.......
