### ISSUE TITLE
How can I install an in-house app with micromdm

### ISSUE THREAD

**Issue by 000amorfo** [micromdm/micromdm#519]
I would like to install an app created by my company by MDM but I dont have a DEP account, is it posible?
can you guide me abt it?
thanks a lot

**Comment by groob** [comment]
https://developer.apple.com/enterprise/documentation/MDM-Protocol-Reference.pdf Check out the Documentation on the InstallApplication section. 

Specifically with micromdm there is a `mdmctl apply apps` command, and some examples under `tools/api/commands` as well. 

Is this for iOS or for macOS? Is MDM even necessary for your use case? 
https://medium.com/apps-studio/distributing-enterprise-ios-app-in-house-without-mdm-3ed015009893
https://stackoverflow.com/questions/31157792/distribute-enterprise-app-in-house

Would like to know more about your specific needs here.

**Comment by 000amorfo** [comment]
This is for iOS and what I want to do is install an application in any device when they get enrolled to the MDM server. 
I feel Im missing something, I will check out the documentation again
I think is necessary using MDM cause I want to install the application silently
thanks @groob

**Comment by groob** [comment]
InstallApplication is what you want.

**Comment by 000amorfo** [comment]
Hi guys, first at all thanks for your help
I did it with the InstallApplication command in this way
I made a simple app with xcode, then I exported its ipa, after that I made the manifest manually, put this one available in an url and sent the command by Postman... 
At the end the app appeared in the device trying to install itself but didnt get over, it just shows "waiting" and never finished. Also in the micromdm console appeared the acknowledge result so it didnt show any error...
Any idea abt my issue?

This is the screenshot of the app trying the installation
![scv_15387873590591667122580](https://user-images.githubusercontent.com/36115136/46574636-e24a3d80-c96b-11e8-81c0-8a81a7f247c2.jpg)

**Comment by groob** [comment]
Can you give us a little more detail about how you scheduled the command, and where you're hosting the app file? 

The client (your iphone) will receive the InstallApplication command and do the following:
1. issue a GET request to download the manifest at the manifest url specified in the command.
2. the manifest has a file URL. the client will issue a GET request to download the file from that URL. 

I'm interested in seeing logs both for your manifest and for the eventual file. Where are these hosted? Can you provide logs for each action? If theyre hosted with micromdm via `mdmctl apply apps`, and you have `-filerepo` the GET requests will go to your MDM server, but if you created the manifest manually, it could be going somewhere else.

**Comment by 000amorfo** [comment]
Im hosting the file in my own site
This is the process that I did
https://docs.google.com/document/d/1s0iZIxlO745Z2AZeFYkwEQaxBOXotPlq6MoXlPZH3yY/edit?usp=sharing
and here I have the results in the console
https://drive.google.com/open?id=1P_bTRVMVhjnAK0Zjia58F9sKhyypfwjSLoafB3jZLlo

I couldnt upload the ipa with mdmctl, I dont know what Im doing wrong
when using this command ### mdmctl apply apps which is the Id that I have to use to sign? the enterprise account Id? or the developer account Id?

thanks for your help

**Comment by feralbob** [comment]
@000amorfo How are you serving the IPA and the Manifest file? Are you using the -filerepo option?
When I manually put the manifest.plist and the .ipa into the file repo I'm able to install the app using 
/tools/api/command/install_application $udid urlofmanifest

I also used the manifest.plist created by Xcode. Product -> Archive and then Distribute App to export the .ipa with the embedded provisioning profile and a the manifest.plist

**Comment by 000amorfo** [comment]
I just wrote the manifest manually and put both files (.ipa and .plist) in my web server where I can access them, maybe the problem is over there
I will check it out

**Comment by feralbob** [comment]
sudo ./micromdm serve -api-key <SNIP> -server-url https://FQDN -s-cert /etc/letsencrypt/live/FQDN/fullchain.pem -tls-key /etc/letsencrypt/live/FQDN/privkey.pem -filerepo /home/ubuntu/build/linux/files/ -http-debug

**Comment by 000amorfo** [comment]
It means I cannot use postman to send the command?

**Comment by 000amorfo** [comment]
I got these errors 
![img_08102018_223954_0](https://user-images.githubusercontent.com/36115136/46637365-832e2980-cb21-11e8-91bc-17a7d64e85d0.png)

**Comment by feralbob** [comment]
You can - the ./install_application just builds the JSON and sends it to the API via curl

{
  "udid": "c<SNIP>******************b",
  "request_type": "InstallApplication",
  "manifest_url": "https://FWDN/repo/manifest.plist"
}

But ensure that you're sending the Basic Authentication and setting the Content-Type: application/json

There is no need to do 

./mdmctl app -pkg for the IPA. If your device can access the URL then it should work fine.

**Comment by 000amorfo** [comment]
I already check that is set the Basic Authentication and the Content-Type is application/json but is not working yet
is it possible that I am doing something wrong creating the ipa? maybe Im using an incorrect account?

**Comment by 000amorfo** [comment]
after a while the device shows the app with its name but when I try to open it shows a message
**unable toe install testdist, please try again later**

**Comment by feralbob** [comment]
How are you exporting the archive? Enterprise or Ad-hoc distribution?

**Comment by 000amorfo** [comment]
Enterprise distribution

**Comment by 000amorfo** [comment]
I already got it
It was my fault, I was making some mistakes when exporting the IPA as enterprise distribution, thanks for your help, all these resources were really helpful

**Comment by shashankmeddo** [comment]
@000amorfo can u help me with the steps I am also following what u did.
hosting .ipa and .plist on my server then hitting Install Application via postman . I am getting success (201 created) in response but there is no notification on my device. :(

**Comment by shashankmeddo** [comment]
@feralbob how does filerepo option work , in case i wanna try it?

**Comment by 000amorfo** [comment]
is the app trying to install in your device as the first picture shows?
My error was the way that I was using to export the .ipa
check it out again and tell us about it

**Comment by shashankmeddo** [comment]
@000amorfo yes, I am able to see the app on my device but it is not getting installed.
What wrong were you doing while exporting .ipa . maybe it can help me. I am able to download the same .ipa through diawi though.

**Comment by shashankmeddo** [comment]
In my case on clicking greyed app icon i get an alert Unable to Install, please try again later.
