### ISSUE TITLE
Can I re-sign any ipa with enterprise distribution?

### ISSUE THREAD

**Issue by 000amorfo** [micromdm/micromdm#529]
I was looking for abt how to install apps through MDM and actually I did it.
To do this I had to create an application in xcode, signed it and then exported to .ipa with the the enterprise distribution.
Now I would like to know if is possible to use any .ipa to get this work. I mean, can I re-sign with my enterprise account any ipa created with a developer account?

**Comment by groob** [comment]
What you do with the .ipa file is not a concern for micromdm. The MDM server only cares about delivering the application command to the device. The rest is up to you.

**Comment by 000amorfo** [comment]
you are right
my apologies
