### ISSUE TITLE
[Question] MDM for Mobiles 

### ISSUE THREAD

**Issue by mrahmadt** [micromdm/micromdm#535]
Hello

I know the goal of this project but I have a passion to build an open source project similar to this project but to manage Android, iOS and Windows but the problem I have no idea how MDM works :)

Can you direct me to any book or reference in how to do it?

Thanks

**Comment by groob** [comment]
For macOS/iOS: https://developer.apple.com/enterprise/documentation/MDM-Protocol-Reference.pdf
For windows: https://docs.microsoft.com/en-us/windows/client-management/mdm/

A bunch of community updated resources are listed on the wiki https://github.com/micromdm/micromdm/wiki/Links
