### ISSUE TITLE
[Question] InstallProfile UDID

### ISSUE THREAD

**Issue by dbrody2004** [micromdm/micromdm#536]
The requesttype InstallProfile specifies a UDID.  Is it possible to installprofile to a wildcard (all UDIDs registered in the mdm server).  

iOS has long taken away the ability to identify a device using it's UDID (or serial) inside an app, so there is no way an app knows if enrollment has occurred.   Furthermore, consider an app that enrolls the device (via a website/mobileconfig file) and then tries to come back and install a vpn profile using its own UDID (via an api call to the MDM server) is impossible.  The workaround to this is to have the server install profile on every device.  I guess the mdm server could push an ManagedApplicationConfiguration to the device with the UDID found in the mdm server, but again it would have to poll all UDIDs in the mdm server and determine which ones didn't have that requesttype sent to it.

**Comment by groob** [comment]
There are two tricks for this that people have used in the past. 

1) Pushing a ManagedApplicationConfiguration along with your custom app, and then tracking the embedded GUID that uniquely identifies that app install. 

2) creating a custom enrollment profile for each device. would add a query parameter like `?uuid=foobar` to the `/connect` and `/checkin` endpoints. Then every time the device connects it will send back those query parameters. MicroMDM further supports this by forwarding any URL parameters in the webhook requests. 

As far as mass pushes of InstallProfile to all devices, or to a specific group, that is coming in the future, likely as a workflow plugin, not in core. 
You can solve this yourself today by using the API to [list devices](https://github.com/micromdm/micromdm/blob/a230831725f173f779cf7e030a93a71b32e8ab13/tools/api/get_devices) and then sending the InstallProfile command to each UDID in the list response.

**Comment by dbrody2004** [comment]
I've implemented option 2, but not getting the query parameters passed to the webhook.

Enrollment profile showing the connect url with parameters.

https://www.dropbox.com/s/8ihy7jj1fe0mt0g/IMG_7270.PNG?dl=0

Here is the output of the webhook.  url_params are null
{
  "topic": "mdm.Authenticate",
  "event_id": "3b63e691-bc23-4b62-bb4f-82dc22aa61ca",
  "created_at": "2018-10-17T18:55:48.118874443Z",
  "checkin_event": {
    "udid": "a9dae7871014da8c48922d646c850023fa78edf6",
    "url_params": null,
    "raw_payload": "{redacted}"
  }
}{
  "topic": "mdm.TokenUpdate",
  "event_id": "5c6bb528-d697-4aa1-8929-9b20256cd651",
  "created_at": "2018-10-17T18:55:50.634302866Z",
  "checkin_event": {
    "udid": "a9dae7871014da8c48922d646c850023fa78edf6",
    "url_params": null,
    "raw_payload": "{redacted}"
  }
}/

**Comment by groob** [comment]
what is your `micromdm version`?

**Comment by groob** [comment]
I promise this was fixed in 1.4 :)

**Comment by dbrody2004** [comment]
Yes I confirmed it is fixed in 1.4.  Thanks

**Comment by rkoshti** [comment]
@groob @dbrody2004  I have tried the 2nd option as well but unfortunately i am not  able to receive response in webhook  same as below after enrolling profile, Not sure what is wrong i can see the device information via get devices command but not getting any response in webhook after profile enrollment

```
{
"topic": "mdm.Authenticate",
"event_id": "3b63e691-bc23-4b62-bb4f-82dc22aa61ca",
"created_at": "2018-10-17T18:55:48.118874443Z",
"checkin_event": {
"udid": "a9dae7871014da8c48922d646c850023fa78edf6",
"url_params": null,
"raw_payload": "{redacted}"
}
}{
"topic": "mdm.TokenUpdate",
"event_id": "5c6bb528-d697-4aa1-8929-9b20256cd651",
"created_at": "2018-10-17T18:55:50.634302866Z",
"checkin_event": {
"udid": "a9dae7871014da8c48922d646c850023fa78edf6",
"url_params": null,
"raw_payload": "{redacted}"
}
}
```

Do anyone has any idea what am i doing wrong? or any help would be appreciated!

**Comment by rkoshti** [comment]
@dbrody2004 @groob can any one help me  for implementing the second option ?
How to create dynamic profiles with php ? Is there any solution for that ? Ang help would be appreciated.

Thanks

**Comment by tomaswallentinus** [comment]
Here is an example: https://raw.githubusercontent.com/tomaswallentinus/mdm/master/enrollmentgenerator.php
