### ISSUE TITLE
[Proposal] - PushProfile endpoint. 

### ISSUE THREAD

**Issue by gavinelder** [micromdm/micromdm#537]
Currently the install profile endpoint takes a Payload from the API, It would be nice to push a profile already on the MDM server 

The proposal of work would be something like add new endpoint 

/v1/pushprofile which takes device UDID & profile name as per already on the server. 

Add to `commands.go`
```
type PushProfile struct {
	Identifier string `json:"identifier,omitempty"`
}
```

Add to marshall_json.go 

```
	case "PushProfile":
		var x = struct {
			RequestType string `json:"request_type"`
			*InstallProfile
		}{
			RequestType:    c.RequestType,
			InstallProfile: c.PushProfile,
		}
		return json.Marshal(&x)
```

**Comment by groob** [comment]
Ok so I like this proposal, but would make the following changes. 

- This should go to `POST /v1/profiles/install` same as the upload steps for uploading a profile
- We shouldn't reuse the mdm/commands.go, that's strictly for what is listed in the spec. Instead just marshal a brand new type in the profiles package. 

It should be added here: https://github.com/micromdm/micromdm/blob/master/platform/profile/server.go

I'll accept a PR :)

**Comment by GavinElder** [comment]
:) 

Give me a few days!
