### ISSUE TITLE
enroll.mobileconfig customization

### ISSUE THREAD

**Issue by dbrody2004** [micromdm/micromdm#541]
How is customization done on enroll.mobileconfig.  I know it can be uploaded back using mdmctl apply profiles -f /path/to/MyProfile.mobileconfig; however how does micromdm know to use this as the enroll profile?  There are also payload content that is dynamically generated (I believe) such as the TLS cert.

**Comment by groob** [comment]
the best answer I can give you is to write your own server that handles returning custom enroll.mobileconfigs and points to micromdm's ServerURL for the connect/checkin endpoints. then you can do all the custom things you want.
