### ISSUE TITLE
Not able remove DEP-token

### ISSUE THREAD

**Issue by trekkim** [micromdm/micromdm#546]
### What version of `micromdm` are you using?
1.4.0
### What `micromdm` command did you run?

mdmctl apply dep-tokens -import ...

I have problem with imported  two DEP-Tokens don't know how to remove or clean imported tokens to get correct one working.

Couse only first token is apply but no more valid in my case.

How can i remove that token.

Thank you

**Comment by WardsParadox** [comment]
I am also having an issue with removing the previous token. Our DEP token expired on 01/19/2019 and in an attempt to be proactive I renewed our token in school.apple.com. I went to upload the new token and after uploading realized that there was no way to remove the token. Without being able to remove the token, communication with DEP errors out with 403 forbidden.

**Comment by jessepeterson** [comment]
Looks like we take the first token that is stored and use it (only). We should consider a) removal of other tokens b) replacement of single tokens c) consider only supporting a single token and d) swawn multiple DEP clients for each token. I think D is probably the way to go; this would allow 
 multiple DEP account setups (i.e. multi-org).

**Comment by WardsParadox** [comment]
@trekkim Try this: https://github.com/micromdm/micromdm/wiki/Updating-and-Removing-DEP-Tokens
