### ISSUE TITLE
Blueprints InstallApplication array always install last application

### ISSUE THREAD

**Issue by deathofshit** [micromdm/micromdm#549]
### What version of `micromdm` are you using?
1.4.0
### What `micromdm` command did you run?
micromdm serve
### What did you expect to see?
InstallApplication array command should send each manifest_url at enroll.
### What did you see instead?
There might be an issue with appurl pointer. It sends last item manifest_url of install_application_manifest_urls array on blueprint file as array length.

	for _, appURL := range bp.ApplicationURLs {
		fmt.Println(appURL)
		requests = append(requests, &mdm.CommandRequest{
			UDID: udid,
			Command: &mdm.Command{
				RequestType: "InstallApplication",
				InstallApplication: &mdm.InstallApplication{
					ManifestURL:     &appURL,
					ManagementFlags: intPtr(1),
				},
			},
		})
	}

**Comment by deathofshit** [comment]
this changes solves the issue on ./platform/blueprint/builtin/listener.go

	for i := range bp.ApplicationURLs {
		appURL := &bp.ApplicationURLs[i]
		requests = append(requests, &mdm.CommandRequest{
			UDID: udid,
			Command: &mdm.Command{
				RequestType: "InstallApplication",
				InstallApplication: &mdm.InstallApplication{
					ManifestURL:     appURL,
					ManagementFlags: intPtr(1),
				},
			},
		})
	}

**Comment by groob** [comment]
Yeah this is a silly go footgun. I’ll fix. 
Although InstallApplication is not really good with multiple applications. Your blueprint should try to only have 1 pkg.

**Comment by tperfitt** [comment]
this is affecting us as well.

**Comment by tperfitt** [comment]
would a pull request be helpful? or will gentle prodding be enough?

**Comment by groob** [comment]
Would appreciate a pull request @tperfitt
