### ISSUE TITLE
get device information is bringing a data incorrect

### ISSUE THREAD

**Issue by 000amorfo** [micromdm/micromdm#551]
When I get all the hardware features there is a field that’s not correct. I’m talking about Product Name.
Actually I'm doing tests in a device with iPhone 6 but the commands fetch Product Name: iPhone 7,3
why is it happening? Could be a default configuration loaded in the device?
thanks micromdm

**Comment by groob** [comment]
please explain better what you're doing.

**Comment by 000amorfo** [comment]
When I execute the command "DeviceInformation" all the information that the device sends is good except for the "Product name". I'm using an iPhone 6 but the device is sending in the Product Name: Iphone 7,3.
why is this happening?

**Comment by groob** [comment]
Sounds like something Apple could answer for you, but I cannot. MicroMDM is showing you the exact data the device sent, it cannot influence it.

**Comment by 000amorfo** [comment]
thanks @groob 
I'll  try to solve this issue with apple

**Comment by johngag** [comment]
> When I execute the command "DeviceInformation" all the information that the device sends is good except for the "Product name". I'm using an iPhone 6 but the device is sending in the Product Name: Iphone 7,3.
> why is this happening?

Sounds like the identifier is correct. https://www.theiphonewiki.com/wiki/Models
