### ISSUE TITLE
Manual Profile deletion

### ISSUE THREAD

**Issue by dbrody2004** [micromdm/micromdm#555]
Manual profile deletion when wifi is disabled doesn't remove the device from the database.

For instance, the following works as expected -
 Install Profile 
 Remove Profile
 webhook mdm.CheckOut is triggered
 mdmctl get devices show EnrollmentStatus as false

The following does not work -
 Install Profile
 Turn off wifi
 Remove profile
 Turn on wifi
 webhook mdm.CheckOut is never triggered
 mdmctl get devices show EnrollmentStatus still is true

**Comment by dbrody2004** [comment]
Then is it possible to do a "ProfileList" query to see if the profile is still active - not sure if the device would respond if there is no profile on it.  Using the lastseen date is not that reliable - as the user could have powered off their device.

**Comment by Lepidopteron** [comment]
I think you won't receive a response to the ProfileList Push Notification, as the iPad would simply neither have a Key and Certificate nor a server url to know where to send the response to the "ProfileList" request to.
