### ISSUE TITLE
tls: error decrypting message

### ISSUE THREAD

**Issue by tinamina12** [micromdm/micromdm#559]
### What version of `micromdm` are you using?
1.4.0-1

### What `micromdm` command did you run?

./tools/api/commands/device_information (udid)

## What did you expect to see?
the information of device 

### What did you see instead?
Post https://api.push.apple.com/3/device/c063f01a4eb897d0e78b5d0315d1421bec9399100cb236f353a367e41514a59c: remote error: tls: error decrypting message

**Comment by jessepeterson** [comment]
Sounds like a problem with your push certificate — the server is complaining about it. How did you generate it? Can you give some details on it?

**Comment by groob** [comment]
This might be helpful in troubleshooting https://github.com/micromdm/micromdm/wiki/Troubleshooting-MDM#check-the-topic-for-apns

**Comment by tinamina12** [comment]
i created MDM csr by using https://mdmcert.download, after receiving the email, i downloaded the file decrypted it and uploaded mdmcert.download.push.req to identity.apple.com and generated a push certificate. after that i uplaoded the certificate by using the following command: 
./mdmctl mdmcert upload -cert="/Users/xyz/Downloads/‎⁨mdm-cert/MDM_ McMurtrie Consulting LLC_Certificate.pem" -private-key=⁩mdmcert.download.push.key
