### ISSUE TITLE
 filename argument required

### ISSUE THREAD

**Issue by tinamina12** [micromdm/micromdm#560]
### What version of `micromdm` are you using?
1.4.0-1

## What `micromdm` command did you run?
./tools/api/get_devices | jq .devices[0].udid -r

## What did you expect to see?
udid of device
### What did you see instead?
./tools/api/get_devices: line 2: source: filename argument required
source: usage: source filename [arguments]

**Comment by jessepeterson** [comment]
Please take a look at the documentation:

https://github.com/micromdm/micromdm/tree/master/tools/api

Specifically the `export MICROMDM_ENV_PATH="$(pwd)/env"` line with the settings for your server.

**Comment by tinamina12** [comment]
Thanks it was helpful
