### ISSUE TITLE
TLS handshake error 

### ISSUE THREAD

**Issue by tinamina12** [micromdm/micromdm#562]
### What version of `micromdm` are you using?
1.4.0-1

### What `micromdm` command did you run?
first i removed "-reqexts SAN -extensions SAN -config /dev/stdin" to register my iphone with this mdm by using the following command: 
DNSNAME=mdm.example.org;  (cat /etc/ssl/openssl.cnf ; printf "\n[SAN]\nsubjectAltName=DNS:$DNSNAME\n") | openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -sha256 -keyout server.key -out server.crt -subj "/CN=$DNSNAME"

After that i removed  "-subj "/CN=$DNSNAME" also.

### What did you expect to see?
Enrollment success message

### What did you see instead?
In both cases i am seeing TLS handshake error

**Comment by jessepeterson** [comment]
You're using a self-signed certificate? If you so you'll need to include that trust certificate on your device before enrolling. This will need to be a profile installed on the device before enrollment. It's a bit easier for macOS (importing into the Keychain).

**Comment by tinamina12** [comment]
yes i am using self-signed certificate. How to install that certificate on iphone?

**Comment by tinamina12** [comment]
i have emailed myself the certificate and i have installed that certificate on iOS, still i am facing error "profile installation failed, a network error has occurred". i am using DNSNAME=mdm.example.org; (cat /etc/ssl/openssl.cnf ; printf "\n[SAN]\nsubjectAltName=DNS:$DNSNAME\n") | openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -sha256 -keyout server.key -out server.crt -subj "/CN=$DNSNAME" to generate certificate

**Comment by jessepeterson** [comment]
Is your mdm server actually at `mdm.example.org`? Have you overridden DNS for that host? Is it running? Can you reach it in a browser?

**Comment by tinamina12** [comment]
when i type mdm.example.org in desktop browser, it is reachable. And when i type mdm.example.org from web browser, it is not reachable. Instead, when i write the https://(ip) it is reachable.

**Comment by tinamina12** [comment]
yep and i have override the DNS

**Comment by hiepnh0** [comment]
> You're using a self-signed certificate? If you so you'll need to include that trust certificate on your device before enrolling. This will need to be a profile installed on the device before enrollment. It's a bit easier for macOS (importing into the Keychain).

How to add the trust certificate into a prolife?
