### ISSUE TITLE
Profile Installation failed on iOS

### ISSUE THREAD

**Issue by tinamina12** [micromdm/micromdm#564]
### What version of `micromdm` are you using?
1.4.0-1

### What `micromdm` command did you run?
DNSNAME=mdm.example.org; (cat /etc/ssl/openssl.cnf ; printf "\n[SAN]\nsubjectAltName=DNS:$DNSNAME\n") | openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -sha256 -keyout server.key -out server.crt -subj "/CN=$DNSNAME"

### What did you expect to see?
iphone enrollment successful. 

### What did you see instead?
TLS Hand shake error 

Explanation: 
I am using self signed certificate. i am generating certificate by using the following command: 

DNSNAME=mdm.example.org; (cat /etc/ssl/openssl.cnf ; printf "\n[SAN]\nsubjectAltName=DNS:$DNSNAME\n") | openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -sha256 -keyout server.key -out server.crt -subj "/CN=$DNSNAME"

When i try to enroll my iOS device, it says Profile installation failed, a network error has occurred. I have manually trusted the certificate on iphone. Can someone please guide me where i am wrong.

**Comment by jessepeterson** [comment]
Does macOS enroll? What are the iOS logs telling you? What specific error are you seeing (screenshot would be nice). Can you get to the MicroMDM page via Safari on the iPhone? How are you initiating enrollment?

**Comment by tinamina12** [comment]
Does macOS enroll? Yes

Can you get to the MicroMDM page via Safari on the iPhone? Yes (screenshot attached)

How are you initiating enrollment? first installing the self signed certificate and then download the enrollment profile. when i click "install", i see an error saying "network error has occurred"

(server logs)
<img width="566" alt="screen shot 2019-02-06 at 11 30 11 am" src="https://user-images.githubusercontent.com/32898278/52325646-98e82880-2a07-11e9-9e5b-7dcc31d2d7de.png">

(Error on installation)
![9875047e-4b23-47b0-879f-7d92dc36e678](https://user-images.githubusercontent.com/32898278/52325659-a7364480-2a07-11e9-8dd2-fa291dbc52c1.png)

(Enrolling)
![65c25081-da0c-4a67-804a-ccac524ba7ca](https://user-images.githubusercontent.com/32898278/52325668-b3ba9d00-2a07-11e9-9e6a-d39fa2d9c827.png)

(Accessing mdm.example.org from mobile safari)
![32d0d49d-ba1d-4844-a3fc-36b3a7d85f22](https://user-images.githubusercontent.com/32898278/52325675-bddc9b80-2a07-11e9-8502-84cdb0fe9c43.png)

**Comment by larsar** [comment]
Have you uploaded push certificates to the MDM server? Unless you have, the profile installation will fail at this step and from my recollection the error message is somewhat misleading.

**Comment by tinamina12** [comment]
Yep, i have uploaded the push certificate to MDM server.

**Comment by iOsMechanic** [comment]
@tinamina12  Howdu fix this?

**Comment by thomastong0718** [comment]
@tinamina12 may i ask that how did you fix this issue?

**Comment by ravikevat55345-dot** [comment]
Ravi vpn

**Comment by ravikevat55345-dot** [comment]
Von

**Comment by ravikevat55345-dot** [comment]
### What version of `micromdm` are you using?
1.4.0-1

### What `micromdm` command did you run?
DNSNAME=mdm.example.org; (cat /etc/ssl/openssl.cnf ; printf "\n[SAN]\nsubjectAltName=DNS:$DNSNAME\n") | openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -sha256 -keyout server.key -out server.crt -subj "/CN=$DNSNAME"

### What did you expect to see?
iphone enrollment successful. 

### What did you see instead?
TLS Hand shake error 

Explanation: 
I am using self signed certificate. i am generating certificate by using the following command: 

DNSNAME=mdm.example.org; (cat /etc/ssl/openssl.cnf ; printf "\n[SAN]\nsubjectAltName=DNS:$DNSNAME\n") | openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -sha256 -keyout server.key -out server.crt -subj "/CN=$DNSNAME"

When i try to enroll my iOS device, it says Profile installation failed, a network error has occurred. I have manually trusted the certificate on iphone. Can someone please guide me where i am wrong.

**Comment by grahamgilbert** [comment]
Do not use a self signed certificate. Letsencrypt is free and trusted natively on Apple devices.
