### ISSUE TITLE
mdmcert.download is down

### ISSUE THREAD

**Issue by samuelb2** [micromdm/micromdm#568]
@jessepeterson 

I was going through the quick start guide and I found that I was unable to access https://mdmcert.download. It seems like the site is down.

Is this just a temporary disruption?

**Comment by jessepeterson** [comment]
mdmcert.download is not officially associated with micromdm. but, I'll take a look. thanks!

**Comment by jessepeterson** [comment]
corrected, mdmcert is back up. server-side networking issue.

**Comment by k23sh2** [comment]
@jessepeterson 
The site is not opening again.

**Comment by jessepeterson** [comment]
@k23sh2 corrected, mdmcert should be back up shortly. server-side networking issue.
