### ISSUE TITLE
RemoveProfile - profile not installed

### ISSUE THREAD

**Issue by dbrody2004** [micromdm/micromdm#569]
Trying to remove the scep profile that is installed via the .mobileconfig but doesn't seem to be working.  Using RemoveProfile with com.github.micromdm.micromdm.enroll.scep.  It says profile is not installed.  Does the whole upper level profile com.github.micromdm.micromdm.enroll need to be reinstalled in order to remove it?

**Comment by groob** [comment]
The enroll profile has multiple payloads, one of which is the scep one. There is no default scep profile. So yes, you'd have to replace the top level profile.
