### ISSUE TITLE
Enrolling device with MDM and DEP

### ISSUE THREAD

**Issue by Michelkoubi** [micromdm/micromdm#570]
I was trying to setup a computer through MDM+DEP but ran into an issue. The computer is in Apple’s DEP portal, when I do `mdmctl get devices` it appears in the devices list and when I do `mdmclt get dep-devices -serials=<SERIAL>` the ProfileStatus says `assigned`, however after connecting to WiFi in the Apple setup, the enrollment page doesn’t appear. After trying to debug it looking at the logs and going back and forth like 3 or 4 times in the WiFi page, the enrollment page came up. Have you guys run into any similar issue?

### What version of `micromdm` are you using?
micromdm version v1.3.1

### What did you expect to see?
Expected to see mdm enrollment page in Apple's setup flow

### What did you see instead?
Nothing

**Comment by jessepeterson** [comment]
I have definitely seen this issue before — especially your experience of hitting 'back and forth' on the Setup Assistant Wi-Fi screen. Given that during this time the MDM is not involvedat all - this is between Apple's DEP services and the device. Sometimes it's just flakey. Do you have a captcha or anything on the WiFi network you're joining? Is it reproducible for you? Have you tried another WiFi network.

**Comment by Michelkoubi** [comment]
Got it, so I've seen it a couple times, we don't have a captcha on the WiFi network and unfortunately I am not able to reproduce it. :(
