### ISSUE TITLE
upload push certificate and key to server: Put https://example.com/v1/config/certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by tinamina12** [micromdm/micromdm#571]
### What version of `micromdm` are you using?
v1.4.0

## What `micromdm` command did you run?
(Following directions at https://github.com/micromdm/micromdm/wiki/mdmcert.download)

* I requested a csr to mdmcert.download
* decrypted it and uploaded the mdmcert.download.push.req to https://identity.apple.com.
* It gave us the MDM_McMurtrieConsultingLLC_Certificate.pem 
* and finally I run the command below

./mdmctl mdmcert upload -password secret -cert /build/linux/MDM_\ McMurtrie\ Consulting\ LLC_Certificate.pem -private-key /build/linux/mdmcert.download.push.key

### What did you expect to see?
success or something similar.

### What did you see instead?

upload push certificate and key to server: Put https://example.com/v1/config/certificate: x509: certificate signed by unknown authority

**Comment by lazar-sidor** [comment]
Hi @tinamina12 : I'm trying to setup/start micromdm server on my domanin and I got the same error. Did you find the root cause? Thanks

**Comment by tinamina12** [comment]
it was a hit and trial method. i regenerated my certificates and the issue somehow disappeared.

**Comment by lazar-sidor** [comment]
Thanks @tinamina12 for the quick reply. Just to make sure I understand correctly, you did generate the Apple Vendor Push certificates (the one downloaded from identity.apple...), right? (not the ssl certificates used for the https requests). Thanks again!

**Comment by tinamina12** [comment]
oh yeah, regenerated the apple vendor push certificates. basically repeated the all steps and magically the error was gone :D

**Comment by nwasiqBD** [comment]
Stuck here as well. Repeated the steps but same issue
