### ISSUE TITLE
how to install application from iOS appstore?

### ISSUE THREAD

**Issue by tinamina12** [micromdm/micromdm#572]
### What version of `micromdm` are you using?
v1.4.0
### What `micromdm` command did you run?
./tools/api/commands/install_appstore_application (udid) com.getdropbox.Dropbox

## What did you expect to see?
The application installation logs 

### What did you see instead?
sudo: ./tools/api/commands/install_appstore_application: command not found
(when i do it without sudo i get permission denied error)

attached below is the screenshot: 
<img width="578" alt="screen shot 2019-02-12 at 4 27 51 pm" src="https://user-images.githubusercontent.com/32898278/52632775-49609b80-2ee4-11e9-9537-30732482b02c.png">

**Comment by GavinElder** [comment]
`chmod +x ./tools/api/commands/install_appstore_application`  ?

**Comment by tinamina12** [comment]
got this result 

<img width="557" alt="screen shot 2019-02-12 at 5 00 15 pm" src="https://user-images.githubusercontent.com/32898278/52633936-b6c1fb80-2ee7-11e9-969a-d8f14344b1f3.png">
