### ISSUE TITLE
restart_device is not a valid request

### ISSUE THREAD

**Issue by tinamina12** [micromdm/micromdm#573]
### What version of `micromdm` are you using?
v1.4.0

### What `micromdm` command did you run?
./tools/api/commands/restart_device (udid)

## What did you expect to see?
the iphone restarts

### What did you see instead?
ErrorDomain</key>
<string>MCMDMErrorDomain</string>
<key>LocalizedDescription</key>
<string>9cRestartDevice is not a valid request type. </string>

attached below is the screenshot:
<img width="561" alt="screen shot 2019-02-12 at 4 41 59 pm" src="https://user-images.githubusercontent.com/32898278/52633079-24205d00-2ee5-11e9-89a0-2ed89da4c301.png">

**Comment by tinamina12** [comment]
btw it is working fine on macOS

**Comment by petarov** [comment]
@tinamina12 Just an idea, but what's the iOS version on the iPhone? `RestartDevice` requires at least iOS 10.3.

**Comment by tinamina12** [comment]
its 12.1

**Comment by groob** [comment]
> This command is supervised only and requires the Device Lock access right

Does your device meet these requirements?
