### ISSUE TITLE
purchase method not supported (macOS app store)

### ISSUE THREAD

**Issue by tinamina12** [micromdm/micromdm#574]
### What version of `micromdm` are you using?
v1.4.0

## What `micromdm` command did you run?
 
./tools/api/commands/install_appstore_application (udid) com.everimaging.beautune
(do we install applications from app store through bundle id)?

## What did you expect to see?
success or something similiar

### What did you see instead?
Payment Method not supported

And when i run command: 
./tools/api/commands/install_application udid com.everimaging.beautune, the commands get queued and receiving no response.

**Comment by Lepidopteron** [comment]
Dear tinamina12,

this response seems to be related to your AppleId on the device.
Do you need to update payment information or something else in the AppStore?

**Comment by tinamina12** [comment]
Nope i just want to install a free application from app store. How can i do that?

**Comment by Lepidopteron** [comment]
It seems like the AppStore refused your billing information of your Apple Id in the Mac AppStore.
Please check 
https://support.apple.com/en-us/HT201266#computer

**Comment by tinamina12** [comment]
When i use install_application, the commands get queued and no response is returned. And when I use install_appstore_application, i receive "PurchaseMethodNotSupported, purchase method must be 1".

**Comment by tinamina12** [comment]
@Lepidopteron can i not install application without adding payment details?

**Comment by groob** [comment]
Purchase Method is supported, but there's a bug with encoding the value when it's set to `0`.
If you were encoding any other value, it would work. 

https://github.com/micromdm/micromdm/pull/592 fixes this.

**Comment by groob** [comment]
Also note that Purchase Method of 0 is _only_ available for iOS, where it is deprecated. 

<img width="651" alt="Screen Shot 2019-06-10 at 5 34 37 AM" src="https://user-images.githubusercontent.com/1526945/59186679-7e52c700-8b41-11e9-8e09-eb81433d9c59.png">
