### ISSUE TITLE
Getting Username/Password in a profile

### ISSUE THREAD

**Issue by virus2016** [micromdm/micromdm#576]
Hi there,

I am using erikberglund/ProfileManifests and looking to do the following however I can't find any docs on this. How do I use the Username for example in Mail? It needs to read {{username}}@domain.com.

Thanks!

**Comment by groob** [comment]
MicroMDM doesn't care about the contents of the profile. Some profiles have auto substititution built in. For example SCEP profile has some variables like ComputerName which get replaced by _apple_, not the client. 

If you're pushing a profile via micromdm and you want it to have some kind of custom values, micromdm does not help or restrict you from doing that. Generate the profile through your own means and submit it through the API.
