### ISSUE TITLE
set the time when moving an ack'd command to a completed queue

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#580]
https://github.com/micromdm/micromdm/blob/8e0d722d61cfd50b631f15912488f9ac2de3117e/platform/queue/queue.go#L75-L82

When a command is ack'd the command's Acknowledged time needs to be set.

**Comment by bdemetris** [comment]
this actually extends to the other queues as well.  `time` handles this as "zero time" and outputs `1754-08-30 22:43:41.128654848 +0000 UTC` to all items in the command struct
