### ISSUE TITLE
DEP watcher behaviour

### ISSUE THREAD

**Issue by Bretterteig** [micromdm/micromdm#582]
### What version of `micromdm` are you using?
1.4.0.1
### What `micromdm` command did you run?
none
### What did you expect to see?
DEP watcher sync devices on schedule
### What did you see instead?
Whenever mdmenrollment.apple.com cannot be reached the DEP watcher disengagemenes itself and does not reenage at a later point in time. No further depsyncs are performed until the server is restarted.

**Comment by jessepeterson** [comment]
Yes, any error in the DEP syncer will stop the sync and we won't re-start the runner. This is here:

https://github.com/micromdm/micromdm/blob/204834e70cdfe830ebe2e94d2c84c4e03cce1c65/platform/dep/sync/depsync.go#L88-L90

We probably ought to more gracefully handle common errors like connection problems.
