### ISSUE TITLE
Connection reset by peer error when receiving webhook

### ISSUE THREAD

**Issue by grahamgilbert** [micromdm/micromdm#590]
Micromdm verison: 1.4.0 (release)

When sending a webhook to a Django app, I am getting a connection reset by peer error:

```
Exception happened during processing of request from ('127.0.0.1', 54893)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/Users/graham_gilbert/Dropbox/src/Mine/mdmdirector/venv/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 173, in handle
    self.handle_one_request()
  File "/Users/graham_gilbert/Dropbox/src/Mine/mdmdirector/venv/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 181, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
```

**Comment by jessepeterson** [comment]
Interesting. What is the request handler returning? Have you tried other simple HTTP endpoints? (There's a trivial Flask example here https://github.com/micromdm/micromdm/wiki/Webhooks#example-code)

**Comment by grahamgilbert** [comment]
It is returning 200 and sending back the body it received. When I do not write anything to the database we do not get the error, so it appears to be related to how quickly the webhook returns. All we are doing right now is saving a couple of fields in a sqlite database - everything is happening locally on my mac right now, so it's not really 'slow', it appears that MicroMDM is intolerant of any delay in the response.

**Comment by groob** [comment]
can you confirm with adding `sleep(60` in your otherwise empty handler?

**Comment by groob** [comment]
also, I just realized you're running the release version. let me check if that is different.

**Comment by groob** [comment]
1.4.0 is still the same code as far as webhooks go. As far as I can tell from the client code, timeouts should not matter...

**Comment by grahamgilbert** [comment]
Interesting. With the 60 second sleep in there I get 

```
level=info msg="post webhook event" err="post webhook event to URL: Post http://localhost:8000/webhooks/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
level=info msg="post webhook event" err="post webhook event to URL: Post http://localhost:8000/webhooks/: EOF"
```

But no traceback from the Django development server.

Keeping the sleep in with the database write does the same as above.

Adding a 2 second in made everything work as expected. I'm confused.com

**Comment by groob** [comment]
Ah!

https://github.com/micromdm/micromdm/blob/577e4c9538226313643f93e55ae28673eb2b0cf3/cmd/micromdm/serve.go#L129

you have 30 seconds

**Comment by grahamgilbert** [comment]
Okay, that doesn't explain why a two second sleep cleared up the errors though.

**Comment by groob** [comment]
two seconds is less than 30? 

Are you sure `ConnectionResetError` is coming because micromdm canceled? it could be sqlite?

**Comment by groob** [comment]
can you share what your handler does? I'm also confused.

**Comment by grahamgilbert** [comment]
Right now, it's super simple

Main view
```# from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import devices.utils

import json

import time

@csrf_exempt
def index(request):
    out = {}

    if request.method == "POST":
        out = json.loads(request.body)

        devices.utils.update_or_create(out)
    print(out)
    time.sleep(2)
    return JsonResponse(out)
```

devices/utils.py
```
from .models import *

from django.http import HttpResponseServerError

import base64
import json
import plistlib


def update_or_create(request_body):
    checkin_event = None
    acknowledge_event = None
    if "checkin_event" in request_body:
        checkin_event = request_body.get("checkin_event")
        payload = base64.b64decode(checkin_event.get("raw_payload"))
    elif "acknowledge_event" in request_body:
        acknowledge_event = request_body.get("acknowledge_event")
        payload = base64.b64decode(acknowledge_event.get("raw_payload"))
    # print(payload)
    try:
        plist_payload = plistlib.loads(payload)
    except Exception:
        print("Couldn't load raw_payload plist")
        return HttpResponseServerError()

    topic = request_body.get("topic")
    enrolled = True
    if checkin_event:
        udid = checkin_event.get("udid")
    else:
        udid = acknowledge_event.get("udid")

    if topic == "mdm.CheckOut":
        enrolled = False
    device, created = Device.objects.update_or_create(
        udid=udid,
        defaults={
            "enrolled": enrolled,
            "name": plist_payload.get("DeviceName", None),
            "os_version": plist_payload.get("OSVersion", None),
            "build_version": plist_payload.get("BuildVersion", None),
        },
    )

    return device
```

**Comment by groob** [comment]
micromdm does not log any errors when you get the tracebacks in your handler?

**Comment by groob** [comment]
It's almost like Device.objects.update_or_create is not blocking so you have to wait for the save?

**Comment by grahamgilbert** [comment]
Nope, everything is dandy according to micromdm

**Comment by groob** [comment]
micromdm will cancel the request once you `return JsonResponse(out)` so if `update_or_create` is asynchronous in any way you could run into trouble. 

How does `update_or_create` work? is that a celery queue?

**Comment by grahamgilbert** [comment]
No, it's nothing fancy like that. https://docs.djangoproject.com/en/2.1/ref/models/querysets/#update-or-create

**Comment by groob** [comment]
I'm tempted to say this is an issue that might only appear in development, and once you have a real server like nginx in front it would go away? 

I tried to google around for this and there's lots of python bugs related to this, but it's hard to say if there's an existing issue or anything... And I don't want to point fingers but there's nothing happening on the go side other than the default http.Client.

**Comment by groob** [comment]
Have you done any additional testing on this?

**Comment by grahamgilbert** [comment]
I didn’t see this with a go server running. Kill it with fire.
