### ISSUE TITLE
alternative for mdmcert.download

### ISSUE THREAD

**Issue by davisbra** [micromdm/micromdm#591]
is there any alternative for mdmcert.download?
(mdmcert.download is down)

**Comment by jessepeterson** [comment]
Absolutely. The Apple Developer Account to use the MDM Vendor CSR is an
option, as is extracting a Server.app MDM push cert.

**Comment by davisbra** [comment]
can you explain more?
how can I create it?
does it need to have an enterprise developer account?
I don't have an enterprise  developer account

**Comment by groob** [comment]
Get one.

**Comment by feishi312** [comment]
Excuse me, may I ask if it is currently not possible to apply for certificates on mdmcert.download?

**Comment by jessepeterson** [comment]
@feishi312 should still be possible.

**Comment by feishi312** [comment]
> @feishi312 should still be possible. ↓
I attempted to register but have not received any email. This is quite disappointing.

**Comment by jessepeterson** [comment]
@feishi312 check your spam folders for email issues. But otherwise: if it doesn't work, it doesn't work. mdmcert.download is not part of the MicroMDM project. we don't provide support here for it.

**Comment by feishi312** [comment]
> @feishi312 check your spam folders for email issues. But otherwise: if it doesn't work, it doesn't work. mdmcert.download is not part of the MicroMDM project. we don't provide support here for it.
I understand, thank you.

**Comment by korylprince** [comment]
I can confirm that mdmcert.download _is_ working, as I tested it just a couple of days ago. Fleet has a similar service, and it filters known free email domains; I believe mdmcert.download does as well, so make sure you're using an email from your own domain.

**Comment by feishi312** [comment]
@korylprince Hi, I received the reply email and was informed that there was a delay of 3 days in receiving the email. Thank you for your response. ^_^

**Comment by jessepeterson** [comment]
Sounds like mail server gray listing. Glad it worked out!
