### ISSUE TITLE
define dep profile: DEP API Error: CONFIG_URL_REQUIRED

### ISSUE THREAD

**Issue by cyb3rc0d3** [micromdm/micromdm#596]
### What version of `micromdm` are you using?
1.4.0 (Latest)
### What `micromdm` command did you run?
/mdmctl/mdmctl apply dep-profiles -f /mdm_data/blueprint.json
### What did you expect to see?
Enrolment message
### What did you see instead?
define dep profile: DEP API Error: CONFIG_URL_REQUIRED

**Comment by groob** [comment]
looks like you're trying to push the blueprint json as a DEP profile. They're separate things.

**Comment by cyb3rc0d3** [comment]
Oops sorry, major derpness  on my part
