### ISSUE TITLE
FR: MDMCTL should expose DeviceFamily when calling get dep-devices/devices

### ISSUE THREAD

**Issue by WardsParadox** [micromdm/micromdm#598]
### What version of `micromdm` are you using?
`version 1.4.0-1-g32e0711`

### What `micromdm` command did you run?
`mdmctl get dep-devices -serials=SERIAL`

### What did you expect to see?
N/A

### What did you see instead?
N/A

**Comment by groob** [comment]
Tagging as `good-first-issue`. The field already exists in the API response, it just needs to be added to the output. =)

**Comment by WardsParadox** [comment]
Not sure why I called it 81 by any means, but this has been fixed in #599 
Side note: Issues and PR's are dead even in numbers 😄
