### ISSUE TITLE
Support RestartDevice and ShutDownDevice commands

### ISSUE THREAD

**Issue by levey** [micromdm/micromdm#600]
Hi dev team,
Any plan to support RestartDevice and ShutDownDevice commands for iOS devices?

**Comment by Lepidopteron** [comment]
This is already working. I have attached 2 files (as text due to Github limitations). You can call them like:
./restart_device.txt [udid]

Sample payload for shutdown:

**Comment by levey** [comment]
@Lepidopteron well explained, thanks!
