### ISSUE TITLE
Uploading APNS certificate via the web API

### ISSUE THREAD

**Issue by tperfitt** [micromdm/micromdm#606]
### What version of `micromdm` are you using?
1.5

I need to programmatically upload an APNS certificate and key, but am getting an error when using PUT to /v1/config/certificate. I encode the cert and key like this:

{"cert":"MII...","key":"MII..="}  

(base64 encoded cert and key)

I get a success, but when I hit the endpoint to view the cert by doing a GET to /v1/config/certificate, I get this error:

{
  "error": "get push certificate: decode private key for push cert"
}

Looking at the code, it appears that the private key cannot be base64 decoded. 

How do I encode the key correctly for PUTting to the endpoint?

**Comment by groob** [comment]
the `mdmcert upload` command sends a PEM encoded key that should look like this
```
----RSA PRIVATE KEY---
...
```

What format are your certifiacate/key before you base64 encode them?

**Comment by groob** [comment]
your key could be encrypted before the upload, in which case the server cannot handle decoding it without a password.

**Comment by tperfitt** [comment]
I tried both -----BEGIN RSA PRIVATE KEY----- and -----BEGIN PRIVATE KEY-----. I don't base64 encode them, they are base64 encoded when outtputing from OpenSSL.

The private key doesn't have a password.

I'll try again, but it is correct to upload the base64 data without the header and "-----" prefix and suffixes?

**Comment by groob** [comment]
you need to base64 encode the entire file, headers and all.

**Comment by tperfitt** [comment]
even the attributes?

Bag Attributes
    friendlyName: com.apple.servermgrd.apns.mgmt
    localKeyID: 9F 8A 6F 22 06 4F 63 72 CE 3E 1E 77 C6 97 27 29 1C CA C8 DF 
Key Attributes: <No Attributes>

**Comment by tperfitt** [comment]
ah, i see. so i base64 encode the base64 encoded data with the headers?

**Comment by groob** [comment]
The attributes are not necessary, only the `---` and the data in between.

**Comment by tperfitt** [comment]
OK, this worked:

cat privatKey_rsa.key |base64
cat apns/publicCert.pem |base64

base64 encoded base64 :)

**Comment by groob** [comment]
You make a good point, perhaps we should skip the headers and only accept the PEM block.

**Comment by jessepeterson** [comment]
Since this is technically working I'm going to close this. PRs always considered, of course. :)
