### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ThePutzy** [micromdm/micromdm#608]
Hi, we have many entries in our log like this (ip is masked from our side ;-)):

 
>Aug  1 07:18:32 fsn-mdm micromdm[1061]: transport=http method=PUT status=200 proto=HTTP/1.1 host=91.115.***.*** user_agent=MDM/1.0 path="/mdm/connect"

>Aug  1 07:18:32 fsn-mdm micromdm[1061]: ts="2019/08/01 07:18:32" caller="http: panic serving 91.115.***.***:59320" msg="runtime error: invalid memory address or nil pointer dereference"

>Aug  1 07:23:24 fsn-mdm micromdm[1061]: transport=http method=PUT status=200 proto=HTTP/1.1 host=91.115.***.*** user_agent=MDM/1.0 path="/mdm/connect"

>Aug  1 07:23:24 fsn-mdm micromdm[1061]: ts="2019/08/01 07:23:24" caller="http: panic serving 91.115.***.***:59322" msg="runtime error: invalid memory address or nil pointer dereference"

>Aug  1 07:23:24 fsn-mdm micromdm[1061]: transport=http method=PUT status=200 proto=HTTP/1.1 host=91.115.***.*** user_agent=MDM/1.0 path="/mdm/connect"

>Aug  1 07:23:24 fsn-mdm micromdm[1061]: ts="2019/08/01 07:23:24" caller="http: panic serving 91.115.***.***:59323" msg="runtime error: invalid memory address or nil pointer dereference"

>Aug  1 07:23:24 fsn-mdm micromdm[1061]: transport=http method=PUT status=200 proto=HTTP/1.1 host=91.115.***.*** user_agent=MDM/1.0 path="/mdm/connect"

>Aug  1 07:23:24 fsn-mdm micromdm[1061]: ts="2019/08/01 07:23:24" caller="http: panic serving 91.115.***.***:59324" msg="runtime error: invalid memory address or nil pointer dereference"

We have blocked and after checkout, we removed the device but after re-enrolling it's the same error. But it is only at a few devices, we have more than 50 devices enrolled i think there are 6 devices with this error.

Do you have any idea what happend?

Running version: micromdm version v1.4.0-34-g1988c30

**Comment by groob** [comment]
I believe this is fixed in the master branch if you compile from HEAD. Can you test and reply back?

**Comment by ThePutzy** [comment]
Hi groob, it seems to be fixed, thanks :-)
