### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference when sending PUT to /v1/blueprints

### ISSUE THREAD

**Issue by tperfitt** [micromdm/micromdm#615]
### What version of `micromdm` are you using?
micromdm version v1.6.0-1-gbd14ba6-dirty

When sending a PUT to create a blueprint to the /v1/blueprints api, I get a runtime error: invalid memory address or nil pointer dereference when sending. I tried using the exact same JSON using mdmctl apply blueprints -f /tmp/bp3.tt and it works fine.

Here is the curl command:
curl -k -X PUT "https://mdscentral.local:8443/v1/blueprints"     -H "Content-Type: application/json; charset=utf-8"      -u "micromdm":"REDACTED" -d@/tmp/bp3.tt

Here is /tmp/bp3.tt:

{
"name":"1MDS DEP Profiles-blueprint",
"devices":["C02X30FDJGH5","C02XH5ZJJK77","C07XH97ZJYVW"],
"uuid":"3B091A1B-5E63-4FDD-B495-693802C0A425",
"skip_primary_setup_account_creation":false,
"apply_at":["Enroll"],
"set_primary_setup_account_as_regular_user":false,
"user_uuids":["969A5F7D-BDEA-4294-AB25-F6E2D96E57BA"]
}

The log shows:

2019-09-11 17:41:13.711434-0500 MDS[52343:2205475] error: ts="2019/09/11 17:41:13" caller="http2: panic serving 192.168.1.156:54318" msg="runtime error: invalid memory address or nil pointer dereference"

**Comment by r2DoesInc** [comment]
I have experienced this as well on `micromdm version v1.6.0`

**Comment by tperfitt** [comment]
OK, i figured this out. turns out that the top level object for the JSON blob needs to be "blueprint", like this:

 {"blueprint":{"uuid":"3B091A1B-5E63-4FDD-B495-693802C0A425","name":"1MDS DEP Profiles-blueprint","install_application_manifest_urls":null,"profile_ids":null,"user_uuids":["969A5F7D-BDEA-4294-AB25-F6E2D96E57BA"],"skip_primary_setup_account_creation":false,"set_primary_setup_account_as_regular_user":false,"apply_at":["Enroll"]}}

Still shouldn't crash, but at least I can move forward.

Also, if the profile exists already with the same name, it returns a 500 error:

2019-09-11 22:07:07.159174-0500 MDS[71316:2566767] error: transport=http method=PUT status=500 proto=HTTP/1.1 host=192.168.107.108 user_agent="MDS/20015 CFNetwork/978.0.7 Darwin/18.7.0 (x86_64)" path=/v1/blueprints

Probably should be a 400 or a 409 error.
