### ISSUE TITLE
where PushCertificateRequest.plist?

### ISSUE THREAD

**Issue by holen1210** [micromdm/micromdm#625]
### What version of `micromdm` are you using?
micromdm version v1.6.0
### What `micromdm` command did you run?
mdmctl mdmcert vendor -sign -cert=./mdm-certificates/mdm.cer -password=secret
### What did you see instead?
signing push certificate request with vendor private key: load push CSR from mdm-certificates/PushCertificateRequest.csr: open mdm-certificates/PushCertificateRequest.csr: no such file or directory

**Comment by groob** [comment]
I'm assuming this is user error. Please read the documentation 
https://github.com/micromdm/micromdm/blob/master/docs/user-guide/quickstart.md

**Comment by JEricaM** [comment]
I have the same exact problem and I'm following the quickstart.md 
Seems like there is a problem with the path of the PushCertificateRequest.csr

**Comment by jessepeterson** [comment]
I believe this would only happen if the step to generated the push CSR wasn't run. If you execute `mdmctl mdmcert` (with no options to get the help), is that more descriptive/helpful? Perhaps we need to update the docs.

**Comment by JEricaM** [comment]
@jessepeterson 
I was able one time only to create the PushCertificateRequest.csr changing the path of -cert in the command and moving the files (VendorCertificateRequest.key, VendorCertificateRequest.csr and mdm.cer) between folders (inside and outside mdm-certificates) but I don't remember which combination was the  successfull one.

Sometimes I did  
mdmctl mdmcert vendor -sign -cert=mdm.cer -password=secret
sometimes
mdmctl mdmcert vendor -sign -cert=/mdm-certificates/mdm.cer -password=secret
etc...

I will run `mdmctl mdmcert ` asap and I will give you more informations.

Thank you

**Comment by jessepeterson** [comment]
There's three steps (from the `mdmctl` help):

    mdmctl mdmcert vendor -password=secret -country=US -email=admin@acme.co
    mdmctl mdmcert push -password=secret -country=US -email=admin@acme.co
    mdmctl mdmcert vendor -sign -cert=./mdm-certificates/mdm.cer -password=secret

**Comment by JEricaM** [comment]
Why `mdmctl mdmcert push` is not mentioned inside the quickstart? I only see `mdmctl mdmcert vendor`
https://github.com/micromdm/micromdm/blob/main/docs/user-guide/quickstart.md

**Comment by jessepeterson** [comment]
@JEricaM That's a good question. I think it's just an omission that needs to be fixed. PRs accepted! :)

**Comment by JEricaM** [comment]
@jessepeterson Hi! thank you so much
Doing **mdmctl mdmcert push** solved the problem so I think that should be added inside the doc. I can do a PRs request but I won't be able to justify or describe the command. It would be only a copy paste of what you said to me.
