### ISSUE TITLE
MicroMDM Running on Self Signed Certs Getting Profile Installation Failed!

### ISSUE THREAD

**Issue by iOsMechanic** [micromdm/micromdm#628]
### What version of `micromdm` are you using?

The Latest Release of MDM

### What `micromdm` command did you run?

To enroll the Jailbreak device went to my domain running on local network .
Earlier steps include

1.Editing the Host file with my ip and domain on the jailbreak. 13.0 
2.Accepting the Certs via mail on my jailbreak phone

### What did you expect to see?

To get the device enrolled on the local server.

### What did you see instead?

Was able to access the local server via ip.
Clicked on enroll device
Downloaded the enrollment profile
Clicked on it
It Stopped at 👎 Profile Installation Failed!

Same Setup is working on for my MAC on which the server is running.Im able to enroll and send the command ,install profile on My mac but not on the iphone jailbreak

**Comment by jessepeterson** [comment]
I've noticed that the embedded self-signed certs in the enrollment profile only work on macOS — they're not honored on iOS. On iOS, in the past at least, you've had to pre-trust the self-signed certs before enrollment could happen (or be using DEP with anchor certs).

What do you mean when you say "2.Accepting the Certs via mail on my jailbreak phone"? Are you able to try putting your self-signed certs in a separate profile and installing that on the device? (Perhaps that's what you meant when you mentioned mail)?

**Comment by iOsMechanic** [comment]
Yes.Im Mailing my certificate via Mail App and then ive manually installed the certs profile.
Also another symptom for the OTA enroll it tires to connect to YourDomain.com/scep which fails with "Unable to get Scep Configuration" and no way to edit or update it from MDMCTL.

**Comment by iOsMechanic** [comment]
@jessepeterson Also how can i change the port for SCEP server in the enrollment profile from either config or manually?

**Comment by jessepeterson** [comment]
@iOsMechanic you re-upload the enrollment profile to MicroMDM with the same profile ID. Not too difference from this: https://github.com/micromdm/micromdm/wiki/Sign-the-enrollment-profile-with-Hancock (even though that's for a different issue)

**Comment by iOsMechanic** [comment]
Thanks @jessepeterson
