### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS micromdm serve

### ISSUE THREAD

**Issue by dpachecols** [micromdm/micromdm#629]
Micromdm version v1.6.0
I am using  system service to run the serve command. 
micromdm.service
```
[Unit]
Description=MicroMDM MDM Server
Documentation=https://github.com/micromdm/micromdm
After=network.target

[Service]
ExecStart=/usr/local/bin/micromdm serve \
    -server-url=https://mdm.lumstondev.com \
    -api-key=devic3s-f0r-real \
    -tls=true \
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
I am using a external loadbalancer for trusted certificate.
I expect to see the welcome page on this url: https://mdm.lumstondev.com instead I see 
`ERR_TOO_MANY_REDIRECTS` error

**Comment by gavinelder** [comment]
Can I ask if you're using an external load balancer why have you set tls=true given that's the flag to get a certificate via LE and should be false in your described scenario.

**Comment by dpachecols** [comment]
If I use `-tls=false` it response with a 502 Bad Gateway status code.

> Can I ask if you're using an external load balancer why have you set tls=true given that's the flag to get a certificate via LE and should be false in your described scenario.

**Comment by dpachecols** [comment]
> Can I ask if you're using an external load balancer why have you set tls=true given that's the flag to get a certificate via LE and should be false in your described scenario.

If I use -tls=false it response with a 502 Bad Gateway status code.

**Comment by gavinelder** [comment]
@dpachecols Awesome at that point I would look at your front end load balancer to make sure you're using the right configuration, if you read the micro docs the server uses two different ports if TLS is on or off `8080` https://github.com/micromdm/micromdm/blob/577e4c9538226313643f93e55ae28673eb2b0cf3/cmd/micromdm/serve.go#L78

**Comment by dpachecols** [comment]
> @dpachecols Awesome at that point I would look at your front end load balancer to make sure you're using the right configuration, if you read the micro docs the server uses two different ports if TLS is on or off `8080`
> 
> https://github.com/micromdm/micromdm/blob/577e4c9538226313643f93e55ae28673eb2b0cf3/cmd/micromdm/serve.go#L78

There was the problem! My loadbalancer was using 80 port, I just update to 8080 and it works. @gavinelder  thanks!

**Comment by gavinelder** [comment]
@dpachecols Awesome feel free to close this also please change your API key consider it burned and you don't want people having API access to your mdm devices...

**Comment by jessepeterson** [comment]
Looks like this is resolved. Feel free to re-open if there's still an issue.
