### ISSUE TITLE
Invalid certificate signing request.

### ISSUE THREAD

**Issue by dpachecols** [micromdm/micromdm#630]
### What version of `micromdm` are you using?
1.6.0
### What `micromdm` command did you run?
mdmctl mdmcert vendor -password=mysecret -country=US -email=my@email.com

Apple reject de vendor certificate

> Invalid Certificate Signing Request

Why the certificate is invalid? I am requesting the certificate on [apple identity page](https://identity.apple.com/)

**Comment by gavinelder** [comment]
This is an impossible question to answer as we don't know what you have done. 

Please make sure you follow the [QuickStart](https://github.com/micromdm/micromdm/blob/master/docs/user-guide/quickstart.md) Fully. 

You need to carry out multiple steps in the correct order to generate valid certs.

**Comment by jessepeterson** [comment]
We need more details @dpachecols in order to help. Also for support issues like this I'd recommend joining us over in [#micromdm on the MacAdmin slack](https://www.macadmins.org/). Feel free to re-open if you're having issues and have more details.
