### ISSUE TITLE
how to detect device unenroll?

### ISSUE THREAD

**Issue by davisbra** [micromdm/micromdm#631]
how can I detect than a device is unenrolled when this scenario occurred
1.device network is disabled (or when my MDM server is not reachable by device)
2.user unenroll device
3.device network enabled after unenrolled succeed (or MDM server is reachable by device)

**Comment by jessepeterson** [comment]
I don't think you can "detect" this. If you don't get notification of the unenroll for whatever reason then I think you have to infer it. It's in the same situation as a device that was, say, damaged, or stolen, or whatever. Once the device is unenrolled it won't try to contact your MDM server any longer. If the device is in DEP and it happens to contact your MDM via DEP upon getting re-setup, that might be an option. You can disallow user un-enrollment with DEP.
