### ISSUE TITLE
getting "CommandFormatError" for bluetooth enabled/disabled

### ISSUE THREAD

**Issue by ajayp11** [micromdm/micromdm#637]
### What version of `micromdm` are you using?
v1.6

### What `micromdm` command did you run?
v1/commands
request

{
  "udid": "***",
  "request_type": "Settings",
  "settings": [{
      "item": "Bluetooth",
      "enabled": true
    }
  ]
}

##ServerResponse

{
  "payload": {
    "command_uuid": "e4875a82-0242-45a0-8181-ca955466a6b0",
    "command": {
      "request_type": "Settings",
      "settings": [{
          "item": "Bluetooth",
          "enabled": true,
          "identifier": null
        }
      ]
    }
  }
}

### What did you see instead?
{
  "CommandUUID": "e4875a82-0242-45a0-8181-ca955466a6b0",
  "Settings": [{
      "Item": "Bluetooth",
      "Status": "CommandFormatError"
    }
  ],
  "Status": "Acknowledged",
  "UDID": "***"
}

**Comment by jessepeterson** [comment]
Just a quick look at this, but could you try with the `enabled` key capitalized (e.g. `Enabled`)?

**Comment by ajayp11** [comment]
@jessepeterson  i have tried with two cases 
1- item and Enabled
2- Item and Enabled

{  "udid": " ", "request_type":"Settings",  "Settings": [{
      "Item": "Bluetooth",
      "Enabled": true
    }
  ]}

#but still getting 

	<dict>
			<key>Item</key>
			<string>Bluetooth</string>
			<key>Status</key>
			<string>CommandFormatError</string>
		</dict>

**Comment by jessepeterson** [comment]
@ajayp11 Okay, I just tested. This works fine for me. I'm sending this:

```
{
  "udid": "<real_uuid_here>",
  "request_type": "Settings",
  "settings": [
    {
      "item": "Bluetooth",
      "enabled": true
    }
  ]
}
```

When I send this I can literally watch system preferences on macOS turn on when I had it set it to off before.

**Comment by jessepeterson** [comment]
I did notice that on iOS this requires a supervised device. Make sure your device is enrolled as supervised. If you don't know if a device is supervised you can send a `DeviceInformation` command to check for the `IsSupervised`, but in general if you're DEP enrolling and have turned on supervision you're probably good.

**Comment by ajayp11** [comment]
@jessepeterson thanks for your favor..  is it possible to supervised device by micromdm enroll file ?
i am not using DEP...
