### ISSUE TITLE
How to restrict perticular app by its bundle id

### ISSUE THREAD

**Issue by ajayp11** [micromdm/micromdm#638]
### What version of `micromdm` are you using?
v1.6

### What `micromdm` command did you run?
{  "udid": "", "request_type": "Restrictions","ProfileRestrictions":[{"blacklistedAppBundleIDs":[" "]}]}

### What did you expect to see?
want to restrict app by micromdm

### What did you see instead?
{
  "payload": {
    "command_uuid": "2df6eaf2-e1ca-XXXXXXXXXXX",
    "command": {
      "request_type": "Restrictions",
      "profile_restrictions": false
    }
  }
}

**Comment by jessepeterson** [comment]
I think `Restrictions ` only has one key: a boolean called `ProfileRestrictions`. It's not an array or dictionary, it's just a query command. Try this instead:

```
{ "udid": "", "request_type": "Restrictions","ProfileRestrictions":true}
```

**Comment by ajayp11** [comment]
@jessepeterson can you help me out for ..how to blacklist or hide any app of device with micromdm?
any request for that ?

**Comment by Lepidopteron** [comment]
You need to push a profile with the following parameter: `blacklistedAppBundleIDs`
https://developer.apple.com/documentation/devicemanagement/restrictions

Sample Profile attached (should be .mobileconfig, but one can not attach .mobileconfig files to github... --> [ProfileBlacklistApps.txt](https://github.com/micromdm/micromdm/files/4039206/ProfileBlacklistApps.txt))

To push this profile, use the attached script ([install_profile.txt](https://github.com/micromdm/micromdm/files/4039190/install_profile.txt)) and call it like:
```
export API_TOKEN=secret
export SERVER_URL=https://localhost
export CURL_OPTS=""
./install_profile.txt \
       1111222233334444555566667777888899990000 \
       ./ProfileBlacklistApps.txt
```

**Comment by ajayp11** [comment]
should i place these in my env file?

export API_TOKEN=supersecret
export PUSH_CERTIFICATE_PRIVATE_KEY_PASSWORD=supersecret
export SERVER_URL="$(curl -s localhost:4040/api/tunnels | jq '.tunnels[]|.public_url' -r |grep https)"
export CURL_OPTS=""
./install_profile.txt \
       1111222233334444555566667777888899990000 \
       ./ProfileBlacklistApps.txt

**Comment by ajayp11** [comment]
my request in postman
{  "udid": "XXXXXXXXXXXXX",  "request_type": "InstallProfile"}

##response
{
  "payload": {
    "command_uuid": "bd2277d9-f65a-4518-abb3-95e96a7b64c6",
    "command": {
      "request_type": "InstallProfile"
    }
  }
}

##getting
<dict>
	<key>CommandUUID</key>
	<string>bd2277d9-f65a-4518-abb3-95e96a7b64c6</string>
	<key>ErrorChain</key>
	<array>
		<dict>
			<key>ErrorCode</key>
			<integer>1000</integer>
			<key>ErrorDomain</key>
			<string>MCProfileErrorDomain</string>
			<key>LocalizedDescription</key>
			<string>Invalid Profile</string>
			<key>USEnglishDescription</key>
			<string>Invalid Profile</string>
		</dict>
	</array>
	<key>Status</key>
	<string>Error</string>
	<key>UDID</key>
	<string>b0ee7687407a781f270577412c35c8efb0bc4e40</string>
</dict>

**Comment by Lepidopteron** [comment]
Please have a look at the script and Apple's documentation.
You Need to provide a profile. The profile needs to be base64 encoded.
Sample:

```
{
  "udid": "XXXXXXXXXXXXX",
  "payload": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KICAgIDxrZXk+UGF5bG9hZENvbnRlbnQ8L2tleT4KICAgIDxhcnJheT4KICAgICAgICA8ZGljdD4KICAgICAgICAgICAgPGtleT5QYXlsb2FkRGVzY3JpcHRpb248L2tleT4KICAgICAgICAgICAgPHN0cmluZz5CbGFja2xpc3QgQXBwPC9zdHJpbmc+CiAgICAgICAgICAgIDxrZXk+UGF5bG9hZERpc3BsYXlOYW1lPC9rZXk+CiAgICAgICAgICAgIDxzdHJpbmc+QmxhY2tsaXN0IEFwcDwvc3RyaW5nPgogICAgICAgICAgICA8a2V5PlBheWxvYWRJZGVudGlmaWVyPC9rZXk+CiAgICAgICAgICAgIDxzdHJpbmc+ODgyQjAyRUQtQkNBNy00MTI5LTgxOTAtODVGQzZDQkFDRDJDPC9zdHJpbmc+CiAgICAgICAgICAgIDxrZXk+UGF5bG9hZFR5cGU8L2tleT4KICAgICAgICAgICAgPHN0cmluZz5jb20uYXBwbGUuYXBwbGljYXRpb25hY2Nlc3M8L3N0cmluZz4KICAgICAgICAgICAgPGtleT5QYXlsb2FkVVVJRDwva2V5PgogICAgICAgICAgICA8c3RyaW5nPjg4MkIwMkVELUJDQTctNDEyOS04MTkwLTg1RkM2Q0JBQ0QyQzwvc3RyaW5nPgogICAgICAgICAgICA8a2V5PlBheWxvYWRWZXJzaW9uPC9rZXk+CiAgICAgICAgICAgIDxpbnRlZ2VyPjE8L2ludGVnZXI+CiAgICAgICAgICAgIDxrZXk+YmxhY2tsaXN0ZWRBcHBCdW5kbGVJRHM8L2tleT4KICAgICAgICAgICAgPGFycmF5PgogICAgICAgICAgICAgICAgPHN0cmluZz5jb20uYXBwbGUubW9iaWxlbWFpbDwvc3RyaW5nPgogICAgICAgICAgICAgICAgPHN0cmluZz5jb20uYXBwbGUuVGVzdEZsaWdodDwvc3RyaW5nPgogICAgICAgICAgICA8L2FycmF5PgogICAgICAgIDwvZGljdD4KICAgIDwvYXJyYXk+CiAgICA8a2V5PlBheWxvYWREaXNwbGF5TmFtZTwva2V5PgogICAgPHN0cmluZz5CbGFja2xpc3QgQXBwPC9zdHJpbmc+CiAgICA8a2V5PlBheWxvYWRJZGVudGlmaWVyPC9rZXk+CiAgICA8c3RyaW5nPkY2MTU4M0FDLTg2NEEtNDJDMy05NTNDLTU2RjNBODhDMjMyQjwvc3RyaW5nPgogICAgPGtleT5QYXlsb2FkUmVtb3ZhbERpc2FsbG93ZWQ8L2tleT4KICAgIDx0cnVlLz4KICAgIDxrZXk+UGF5bG9hZFR5cGU8L2tleT4KICAgIDxzdHJpbmc+Q29uZmlndXJhdGlvbjwvc3RyaW5nPgogICAgPGtleT5QYXlsb2FkVVVJRDwva2V5PgogICAgPHN0cmluZz43QzI2Q0EzRC1GMTUxLTQ4QTItODJENC1DOTEyQUU5NDBGODg8L3N0cmluZz4KICAgIDxrZXk+UGF5bG9hZFZlcnNpb248L2tleT4KICAgIDxpbnRlZ2VyPjE8L2ludGVnZXI+CjwvZGljdD4KPC9wbGlzdD4K",
  "request_type": "InstallProfile"
}
```

**Comment by rkoshti** [comment]
@Lepidopteron Is it correct request ?
```

{
  "udid": "XXXXXXXXXXXXX",
  "payload": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KICAgIDxrZXk+UGF5bG9hZENvbnRlbnQ8L2tleT4KICAgIDxhcnJheT4KICAgICAgICA8ZGljdD4KICAgICAgICAgICAgPGtleT5QYXlsb2FkRGVzY3JpcHRpb248L2tleT4KICAgICAgICAgICAgPHN0cmluZz5CbGFja2xpc3QgQXBwPC9zdHJpbmc+CiAgICAgICAgICAgIDxrZXk+UGF5bG9hZERpc3BsYXlOYW1lPC9rZXk+CiAgICAgICAgICAgIDxzdHJpbmc+QmxhY2tsaXN0IEFwcDwvc3RyaW5nPgogICAgICAgICAgICA8a2V5PlBheWxvYWRJZGVudGlmaWVyPC9rZXk+CiAgICAgICAgICAgIDxzdHJpbmc+ODgyQjAyRUQtQkNBNy00MTI5LTgxOTAtODVGQzZDQkFDRDJDPC9zdHJpbmc+CiAgICAgICAgICAgIDxrZXk+UGF5bG9hZFR5cGU8L2tleT4KICAgICAgICAgICAgPHN0cmluZz5jb20uYXBwbGUuYXBwbGljYXRpb25hY2Nlc3M8L3N0cmluZz4KICAgICAgICAgICAgPGtleT5QYXlsb2FkVVVJRDwva2V5PgogICAgICAgICAgICA8c3RyaW5nPjg4MkIwMkVELUJDQTctNDEyOS04MTkwLTg1RkM2Q0JBQ0QyQzwvc3RyaW5nPgogICAgICAgICAgICA8a2V5PlBheWxvYWRWZXJzaW9uPC9rZXk+CiAgICAgICAgICAgIDxpbnRlZ2VyPjE8L2ludGVnZXI+CiAgICAgICAgICAgIDxrZXk+YmxhY2tsaXN0ZWRBcHBCdW5kbGVJRHM8L2tleT4KICAgICAgICAgICAgPGFycmF5PgogICAgICAgICAgICAgICAgPHN0cmluZz5jb20uYXBwbGUubW9iaWxlbWFpbDwvc3RyaW5nPgogICAgICAgICAgICAgICAgPHN0cmluZz5jb20uYXBwbGUuVGVzdEZsaWdodDwvc3RyaW5nPgogICAgICAgICAgICA8L2FycmF5PgogICAgICAgIDwvZGljdD4KICAgIDwvYXJyYXk+CiAgICA8a2V5PlBheWxvYWREaXNwbGF5TmFtZTwva2V5PgogICAgPHN0cmluZz5CbGFja2xpc3QgQXBwPC9zdHJpbmc+CiAgICA8a2V5PlBheWxvYWRJZGVudGlmaWVyPC9rZXk+CiAgICA8c3RyaW5nPkY2MTU4M0FDLTg2NEEtNDJDMy05NTNDLTU2RjNBODhDMjMyQjwvc3RyaW5nPgogICAgPGtleT5QYXlsb2FkUmVtb3ZhbERpc2FsbG93ZWQ8L2tleT4KICAgIDx0cnVlLz4KICAgIDxrZXk+UGF5bG9hZFR5cGU8L2tleT4KICAgIDxzdHJpbmc+Q29uZmlndXJhdGlvbjwvc3RyaW5nPgogICAgPGtleT5QYXlsb2FkVVVJRDwva2V5PgogICAgPHN0cmluZz43QzI2Q0EzRC1GMTUxLTQ4QTItODJENC1DOTEyQUU5NDBGODg8L3N0cmluZz4KICAgIDxrZXk+UGF5bG9hZFZlcnNpb248L2tleT4KICAgIDxpbnRlZ2VyPjE8L2ludGVnZXI+CjwvZGljdD4KPC9wbGlzdD4K",
  "request_type": "Restriction"
}
```

**Comment by Lepidopteron** [comment]
The `request_type` should be ÌnstallProfile` as the restrictions is part of a Profile that is to be installed on the device.

[Profile Requirements](https://developer.apple.com/documentation/devicemanagement/configuring_multiple_devices_using_profiles#3234127)
[Profile Specific Payload Keys](https://developer.apple.com/documentation/devicemanagement/profile-specific_payload_keys) (e.g. Restrictions)

**Comment by tomaswallentinus** [comment]
request_type is InstallProfile for all profiles. The payload string is the profile itself but you encode it to base64 before pasting it.
If you decode the PD94... string above you see one example I believe.
There is a great forum for profiles, micromdm and other mac-stuff at: https://macadmins.slack.com/
Search the history there and you shall find almost anything you need.

**Comment by ajayp11** [comment]
[profileblacklistapp.txt](https://github.com/micromdm/micromdm/files/4040101/profileblacklistapp.txt)

@Lepidopteron @tomaswallentinus Can you check this profile and acknowledge is it correct or not as it is installed in my phone but nothing happens

**Comment by tomaswallentinus** [comment]
Wait a second, you put it together with your enrollment profile again. Don't do that. Use the unmodified profile from micromdm for the enrollment alone. And then a new profile for black/white listing.

**Comment by ajayp11** [comment]
@tomaswallentinus Thanks for your quick followup

Let me explain what i have got from your answer

Do you mean i need to do fresh enrollment again in my phone 

and after that with above profile that @Lepidopteron has shared i need to replace blacklistedapp array and i need to push that profile again with install profile command

is that correct?

**Comment by tomaswallentinus** [comment]
Yes, it sounds like your on the right track.

**Comment by ajayp11** [comment]
@tomaswallentinus i had followed the same steps but nothing happened
I got this response 
```
{
  "payload": {
    "command_uuid": "4bd2acc6-d907-4e2d-ad9c-ab195f98a8bd",
    "command": {
      "request_type": "InstallProfile",
      "payload": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjwhRE9DVFlQRSBwbGlzdCBQVUJMSUMgIi0vL0FwcGxlLy9EVEQgUExJU1QgMS4wLy9FTiIgImh0dHA6Ly93d3cuYXBwbGUuY29tL0RURHMvUHJvcGVydHlMaXN0LTEuMC5kdGQiPg0KPHBsaXN0IHZlcnNpb249IjEuMCI+DQo8ZGljdD4NCiAgICA8a2V5PlBheWxvYWRDb250ZW50PC9rZXk+DQogICAgPGFycmF5Pg0KICAgICAgICA8ZGljdD4NCiAgICAgICAgICAgIDxrZXk+UGF5bG9hZERlc2NyaXB0aW9uPC9rZXk+DQogICAgICAgICAgICA8c3RyaW5nPkJsYWNrbGlzdCBBcHA8L3N0cmluZz4NCiAgICAgICAgICAgIDxrZXk+UGF5bG9hZERpc3BsYXlOYW1lPC9rZXk+DQogICAgICAgICAgICA8c3RyaW5nPkJsYWNrbGlzdCBBcHA8L3N0cmluZz4NCiAgICAgICAgICAgIDxrZXk+UGF5bG9hZElkZW50aWZpZXI8L2tleT4NCiAgICAgICAgICAgIDxzdHJpbmc+ODgyQjAyRUQtQkNBNy00MTI5LTgxOTAtODVGQzZDQkFDRDJDPC9zdHJpbmc+DQogICAgICAgICAgICA8a2V5PlBheWxvYWRUeXBlPC9rZXk+DQogICAgICAgICAgICA8c3RyaW5nPmNvbS5hcHBsZS5hcHBsaWNhdGlvbmFjY2Vzczwvc3RyaW5nPg0KICAgICAgICAgICAgPGtleT5QYXlsb2FkVVVJRDwva2V5Pg0KICAgICAgICAgICAgPHN0cmluZz44ODJCMDJFRC1CQ0E3LTQxMjktODE5MC04NUZDNkNCQUNEMkM8L3N0cmluZz4NCiAgICAgICAgICAgIDxrZXk+UGF5bG9hZFZlcnNpb248L2tleT4NCiAgICAgICAgICAgIDxpbnRlZ2VyPjE8L2ludGVnZXI+DQogICAgICAgICAgICA8a2V5PmJsYWNrbGlzdGVkQXBwQnVuZGxlSURzPC9rZXk+DQogICAgICAgICAgICA8YXJyYXk+DQogICAgICAgICAgICAgICA8c3RyaW5nPmNvbS5pdHBhdGguTmV3c0FwcDwvc3RyaW5nPg0KICAgICAgICAgICAgICAgPHN0cmluZz5jb20uZmFjZWJvb2suRmFjZWJvb2s8L3N0cmluZz4NCiAgICAgICAgICAgICAgIDxzdHJpbmc+Y29tLnNreXBlLnNreXBlPC9zdHJpbmc+DQogICAgICAgICAgICA8L2FycmF5Pg0KICAgICAgICA8L2RpY3Q+DQogICAgPC9hcnJheT4NCiAgICA8a2V5PlBheWxvYWREaXNwbGF5TmFtZTwva2V5Pg0KICAgIDxzdHJpbmc+QmxhY2tsaXN0IEFwcDwvc3RyaW5nPg0KICAgIDxrZXk+UGF5bG9hZElkZW50aWZpZXI8L2tleT4NCiAgICA8c3RyaW5nPkY2MTU4M0FDLTg2NEEtNDJDMy05NTNDLTU2RjNBODhDMjMyQjwvc3RyaW5nPg0KICAgIDxrZXk+UGF5bG9hZFJlbW92YWxEaXNhbGxvd2VkPC9rZXk+DQogICAgPHRydWUvPg0KICAgIDxrZXk+UGF5bG9hZFR5cGU8L2tleT4NCiAgICA8c3RyaW5nPkNvbmZpZ3VyYXRpb248L3N0cmluZz4NCiAgICA8a2V5PlBheWxvYWRVVUlEPC9rZXk+DQogICAgPHN0cmluZz43QzI2Q0EzRC1GMTUxLTQ4QTItODJENC1DOTEyQUU5NDBGODg8L3N0cmluZz4NCiAgICA8a2V5PlBheWxvYWRWZXJzaW9uPC9rZXk+DQogICAgPGludGVnZXI+MTwvaW50ZWdlcj4NCjwvZGljdD4NCjwvcGxpc3Q+DQo="
    }
  }
}
```
[ProfileBlacklistApps (1).txt](https://github.com/micromdm/micromdm/files/4040409/ProfileBlacklistApps.1.txt)

Attached my profile file as well 

Not sure what's wrong! Nothing is gets hidden in my iphone.

Any help would be appreciated!

**Comment by tomaswallentinus** [comment]
Looks good, check the #profiles channel on macadmin slack or search Google for iPad profile info.

**Comment by rushank-shah** [comment]
@ajayp1510  Did you find any answer on how to hide the app from home screen layout?

**Comment by Lepidopteron** [comment]
> [@ajayp1510](https://github.com/ajayp1510) Did you find any answer on how to hide the app from home screen layout?

Please have a look at this comment:
[https://github.com/micromdm/micromdm/issues/638#issuecomment-572433257](https://github.com/micromdm/micromdm/issues/638#issuecomment-572433257)

**Comment by rushank-shah** [comment]
@Lepidopteron  I didn't get about to push .mobileconfig. I have already installed one .mobileconfig profile. Will this push new profile or add payload in the existing one?

**Comment by Lepidopteron** [comment]
> [@Lepidopteron](https://github.com/Lepidopteron) I didn't get about to push .mobileconfig. I have already installed one .mobileconfig profile. Will this push new profile or add payload in the existing one?

Its possible to have multiple .mobileconfig files in place.
For example we do have one for a custom home screen layout and another one for limiting the available apps.

**Comment by rushank-shah** [comment]
@Lepidopteron Ok. Thanks for the details. Another question: How can I generate a new profile from micromdm and send a command? Is there any documentation of micromdm?

**Comment by rushank-shah** [comment]
Ok. Thanks.

**Comment by rushank-shah** [comment]
@Lepidopteron, I have a question, I have distributed my profile to my customers. but how do we identify device information based on payload uuid? When I hit the API 
`curl $CURL_OPTS -X POST --data-binary {} -s -K <(cat <<< "-u micromdm:12345678") https://example.com/v1/devices`

It gives the following data :


```
{
  "devices": [
    {
      "serial_number": "C38QTGRWV",
      "udid": "39e394270ac116c9dc73cc6d05d6cfb",
      "enrollment_status": true,
      "last_seen": "2025-03-04T14:01:38.503431816Z",
      "dep_profile_status": ""
    },
    {
      "serial_number": "DX3ZKXK6",
      "udid": "00008020-001A7E83002E",
      "enrollment_status": true,
      "last_seen": "2025-03-04T14:02:18.97698203Z",
      "dep_profile_status": ""
    }
  ]
}
```

So how to identify which device has which profile installed?

**Comment by rushank-shah** [comment]
@Lepidopteron  I did try that with http POST method, but it doesn't show any profile.

**Comment by Lepidopteron** [comment]
> [@Lepidopteron](https://github.com/Lepidopteron) I did try that with http POST method, but it doesn't show any profile.

Provided Apple ressourcen clearly states 'PUT'. However, did you try the listed command?

**Comment by rushank-shah** [comment]
I think you did not get my question.  Use case - I have distributed more than 10 profiles to my users. Now, each of them has installed it. Now, I want to identify which profile is bound to which devices. Example - user 1 (serial number - 12323 is bonded with XYZ profile).
