### ISSUE TITLE
how to disabled/enabled any application of device with bundleId from micromdm?

### ISSUE THREAD

**Issue by ajayp11** [micromdm/micromdm#639]
### What version of `micromdm` are you using?
latest

# i tried with "blacklistedAppBundleIDs"  in postman but its not worked

**Comment by rkoshti** [comment]
@groob @jessepeterson Guys,  Great MDM platform Cheers!

how can black list and white list ios apps with the microMDM solution ?  apple says we can do that with the restrictions. Can we do that with the micro mdm? 

![image_2020_01_07T11_09_31_836Z](https://user-images.githubusercontent.com/19707208/72048589-251f6180-32e3-11ea-92ef-eeafa01c89e7.png)
`
https://developer.apple.com/documentation/devicemanagement/restrictions`

Do we have any request format and documentation available to achieve that feature with our MICRO MDM solution? Any help will be appreciated.

**Comment by Lepidopteron** [comment]
see this: https://github.com/micromdm/micromdm/issues/638#issuecomment-572403912

**Comment by ajayp11** [comment]
@Lepidopteron , I am using linux so how can i create profile as you sent sample profileBlackListApps.txt

**Comment by tomaswallentinus** [comment]
Just edit the file in an text editor. It's regular xml.

**Comment by rkoshti** [comment]
@tomaswallentinus We have edited the file and added blacklistedAppBundleIDs array in the xml and installed that profile in iphone by following "InstallProfile" Command

It seems profile is updated and showing in the device but nothing is happend no apps are gets hidden / black listed which we have added in the profile.

Do you have any idea what we are doing wrong here ?

**Comment by groob** [comment]
I'm sorry, but this is not a bug, it's a usage question. The github issue tracker is not the right place to ask questions about how to use MicroMDM. Please ask in slack instead.
