### ISSUE TITLE
getting Invalid-input in ABM

### ISSUE THREAD

**Issue by ajayp11** [micromdm/micromdm#644]
serial_number, source_server_name, target_server_name, operation_status, operation_substatus, timestamp
XXXXXXX,,,ISSUE,INVALID_INPUT,2020-01-30T06:15:35.508Z

we follow these steps to integrate micromdm with ABM
[https://github.com/micromdm/micromdm/blob/master/docs/user-guide/quickstart.md#configure-apple-business-manager-dep](url)
![image](https://user-images.githubusercontent.com/59654633/73432396-aa3cea00-4368-11ea-8968-4796c6c67a1a.png)

micromdm integrated but getting 0 devices .... how to enroll device to supervised it 

we want to sync devices in ABM also which are enroll with micromdm

![screenshot-business apple com-2020 01 30-14_01_53](https://user-images.githubusercontent.com/59654633/73432829-8928c900-4369-11ea-9eaf-6387f6887973.png)

**Comment by jessepeterson** [comment]
This is a problem with ABM and not with MicroMDM. Please join the MacAdmins slack in #dep #mdm or #micromdm channels to discuss further. Thanks!
