### ISSUE TITLE
Provide an ability to clear command queue

### ISSUE THREAD

**Issue by tperfitt** [micromdm/micromdm#646]
# What version of `micromdm` are you using? 
1.6.0

When I removed the com.github.micromdm.micromdm.enroll profile via a MDM command and attempted to re-enroll the mac, it was immediately unenrolled. Removing the mdm.DeviceCommands entries in the db resolved the issue. I believe the remove profile command was queue and sent but never removed since it was not acknowledged.  Deleting the device did not resolve the issue.

Feature Request:
MicroMDM should have a way to clear the queue for any pending commands (or all commands) in order to resolve any issues. Please provide a mechanism both mdmctl and the web API.

**Comment by jessepeterson** [comment]
Addressed with #692.
