### ISSUE TITLE
[Question] - How obtain MDM CSR?

### ISSUE THREAD

**Issue by badstorm** [micromdm/micromdm#660]
Hi, I registred today my company at _Apple Business Manager_, and we want to use micromdm as MDM server.
I flloweed the [Quickstart](https://github.com/micromdm/micromdm/blob/master/docs/user-guide/quickstart.md) guide but I'm stuck on _Generate MDM CSR_

If we go to _Certificates, IDs & Profiles_ section of our account I cannot find the option "MDM CSR" under _Service_. I also login with and Enterprise account but this option is not present.

What is the best way to generate the certificate?

**Comment by Lepidopteron** [comment]
Hey @badstorm checkout the Talk by @jessepeterson on Youtube: https://youtu.be/WGKT-PyHz6I?t=1727
Here he does mention that you have to request the MDM CSR option at Apple, if your Developer Account is already set up. Only Administrators of the Apple Enterprise Account can request this.

**Comment by badstorm** [comment]
Thanks @Lepidopteron.
But I don't understand on thing:  if only Apple Enterprise Account can obtain MDM  Csr, other company (with less 100 emploerys) cannot use an internal MDM solution? Or there is a way to install an MDM solution like micromdm without a mdm csr?

**Comment by badstorm** [comment]
I think i found the answer to my question:
https://github.com/micromdm/micromdm/wiki/mdmcert.download

**Comment by arnaudambro** [comment]
> Thanks @Lepidopteron.
> But I don't understand on thing: if only Apple Enterprise Account can obtain MDM Csr, other company (with less 100 emploerys) cannot use an internal MDM solution? Or there is a way to install an MDM solution like micromdm without a mdm csr?

I just ended up a call with Apple Developer support, with exactly this question, the couldn't reply.

What is your conclusion @badstorm ?

**Comment by Lepidopteron** [comment]
Dear @arnaudambro, regarding Apple's  Enterprise page: https://developer.apple.com/programs/enterprise/ yes, it does require >100 employees.
For less than 100 employees I am not quite sure, whether the effort of hosting, maintenance, management of certificates is worth it (from an economical point of view) and Apple might recommend to use an established MDM solution that is available at the market already?

**Comment by arnaudambro** [comment]
Hey @Lepidopteron 
Thanks for your answer, but here is the thing : like fleetsmith for instance, or other companies like that, I want to build a startup who can manage a fleet of computers for my clients.
As I start my company, we are not 100 yet, so I can't apply for this MDM CSR.
What solution is possible ?
