### ISSUE TITLE
[Question] How to get enrolled device UDID ?

### ISSUE THREAD

**Issue by darshanpitpath** [micromdm/micromdm#662]
### What version of `micromdm` are you using?
micromdm version 9e65297
### What `micromdm` command did you run?
- We have run micro MDM check in event to get device UDID as reference below
https://github.com/micromdm/micromdm/blob/master/docs/user-guide/api-and-webhooks.md

### What did you expect to see?
we would like to see enrolled device UDID as per check in event document.
### What did you see instead?
We are not getting device authentication message to server including device UDID.

Please find my MDM profile configuration file below 
[https://www.dropbox.com/s/irs378ewp66kt0m/microMDM_Profile.txt?dl=0
](url)

Can you guide us here to get enrolled device UDID on check in event.

**Comment by groob** [comment]
> We are not getting device authentication message to server including device UDID.

Can you show me what you ARE getting?
