### ISSUE TITLE
vulnerability in github.com/satori/go.uuid v1.2.0 pkg

### ISSUE THREAD

**Issue by dasuppu** [micromdm/micromdm#664]
micromdm is using github.com/satori/go.uuid v1.2.0 pkg for uuid generation and found that it has vulnerability.

**Comment by groob** [comment]
While there appears to be a potential problem with the library, I don't think it affects MicroMDM's usage of the UUIDs. The places we use them (device identifiers and command UUIDs) could just be auto-incremented numbers instead. 

https://github.com/satori/go.uuid/issues/73

That said, I learned that the package is no longer maintained, and will switch to a different UUID library instead. 
https://github.com/google/uuid

**Comment by dasuppu** [comment]
@groob Thank you for the change. Are you going to release new version.
