### ISSUE TITLE
Slow response of MicroMDM server after install the enrollment profile

### ISSUE THREAD

**Issue by windliyue** [micromdm/micromdm#670]
### What version of `micromdm` are you using?
v1.6.0
## What `micromdm` command did you run?
None, My issue is MIcroMDM server re
1. Enroll a client by DEP. after install the enrollment profile, it will take about one minutes at "Waiting for Management server", and some times it will fail.
2. Enroll a client by manual install enrollment profile, it may take 8 hours to kick off install profile and pgk in blueprint. the MicroMDM log show that it stucked at "ip-172-31-38-116 micromdm[325]: level=info msg="queued event for device" device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5 command_uuid=b38a69f9-fabe-4a0b-81b7-97c9253deba1 request_type=InstallProfile". 
### What did you expect to see?
1. Enroll a client by DEP, "Waiting for Management server" phase very short, and should never fail
2. Enroll a client by manual install enrollment profile, very quick to kick off install profile and pkg in the blueprint
### What did you see instead?
1. Enroll a client by DEP, "Waiting for Management server" take over one minute, and failed some times
2. Enroll a client by manual install enrollment profile, it takes hours to kick off install profile and pkg in the blueprint, after re-log on the OS.

**Comment by windliyue** [comment]
For the scenario, Enroll a client by manual install enrollment profile. it will take around 8 hours to kick off install profile and pkg in the blueprint. verified 3 time:
This is logs from my MicroMDM server for one time manual install the enrollment profile:

I manual install the enrollment profile at **May 23 01:11:36**
May 23 01:11:36 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15" path=/
May 23 01:11:36 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=404 proto=HTTP/2.0 host=218.2.208.75 user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15" path=/favicon.ico referer=https://mdm.trendmicro.com.cn/
May 23 01:11:39 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15" path=/mdm/enroll referer=https://mdm.trendmicro.com.cn/
May 23 01:11:54 ip-172-31-38-116 micromdm[325]: method=GetCACaps err=null took=1.734µs
May 23 01:11:54 ip-172-31-38-116 micromdm[325]: component=scep op=GetCACaps error=null took=35.227µs
May 23 01:11:54 ip-172-31-38-116 micromdm[325]: component=scep method=GET status=200 proto=HTTP/1.1 host=218.2.208.75 user_agent="CertificateService/1 CFNetwork/1125.2 Darwin/19.4.0 (x86_64)" path="/scep?operation=GetCACaps&message="
May 23 01:11:54 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/1.1 host=218.2.208.75 user_agent="CertificateService/1 CFNetwork/1125.2 Darwin/19.4.0 (x86_64)" path="/scep?operation=GetCACaps&message="
May 23 01:11:54 ip-172-31-38-116 micromdm[325]: method=GetCACert err=null took=2.09µs
May 23 01:11:54 ip-172-31-38-116 micromdm[325]: component=scep op=GetCACert error=null took=32.871µs
May 23 01:11:54 ip-172-31-38-116 micromdm[325]: component=scep method=GET status=200 proto=HTTP/1.1 host=218.2.208.75 user_agent="CertificateService/1 CFNetwork/1125.2 Darwin/19.4.0 (x86_64)" path="/scep?operation=GetCACert&message=Device%20Management%20Identity%20Certificate"
May 23 01:11:54 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/1.1 host=218.2.208.75 user_agent="CertificateService/1 CFNetwork/1125.2 Darwin/19.4.0 (x86_64)" path="/scep?operation=GetCACert&message=Device%20Management%20Identity%20Certificate"
May 23 01:11:58 ip-172-31-38-116 micromdm[325]: method=PKIOperation err=null took=15.989504ms
May 23 01:11:58 ip-172-31-38-116 micromdm[325]: component=scep op=PKIOperation error=null took=16.021812ms
May 23 01:11:58 ip-172-31-38-116 micromdm[325]: component=scep method=POST status=200 proto=HTTP/1.1 host=218.2.208.75 user_agent="CertificateService/1 CFNetwork/1125.2 Darwin/19.4.0 (x86_64)" path="/scep?operation=PKIOperation"
May 23 01:11:58 ip-172-31-38-116 micromdm[325]: transport=http method=POST status=200 proto=HTTP/1.1 host=218.2.208.75 user_agent="CertificateService/1 CFNetwork/1125.2 Darwin/19.4.0 (x86_64)" path="/scep?operation=PKIOperation"
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/checkin
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=debug msg="re-enrolling device" serial=C02T82EVGTFL
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/checkin
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=debug msg="applying blueprint" device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5 blueprint_name=TrendMicro-CDC
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=debug msg="creating mdm command request from blueprint" request_type=AccountConfiguration blueprint_name=TrendMicro-CDC user_uuid=be475da9-cb0c-4a37-96ef-669078c43ed9 device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=debug msg="creating mdm command request from blueprint" request_type=InstallApplication blueprint_name=TrendMicro-CDC manifest_url=https://mdm.trendmicro.com.cn/repo/InstallApplications.plist device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=debug msg="creating mdm command request from blueprint" request_type=InstallProfile blueprint_name=TrendMicro-CDC profile_identifier=com.trendmicro.kext device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=debug msg="creating mdm command request from blueprint" request_type=InstallProfile blueprint_name=TrendMicro-CDC profile_identifier=com.trendmicro.ProfileCreator.8C5E38AE-9829-4DD1-8B5C-4ED3A8E383BA device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=debug msg="creating mdm command request from blueprint" request_type=InstallProfile blueprint_name=TrendMicro-CDC profile_identifier=com.apple.syspolicy.kernel-extension-policy device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=debug msg="creating mdm command request from blueprint" request_type=InstallProfile blueprint_name=TrendMicro-CDC profile_identifier=com.trendmicro.iCoreService device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=info msg="queued event for device" device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5 command_uuid=a0803079-e681-41e1-aa82-fe3e8bc9f65e request_type=InstallProfile
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=info msg="queued event for device" device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5 command_uuid=edc2e0be-d1dc-453a-be99-994069e39f76 request_type=InstallProfile
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=info msg="queued event for device" device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5 command_uuid=6c29a638-1f1f-4227-94ed-b07603fe3308 request_type=AccountConfiguration
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=info msg="queued event for device" device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5 command_uuid=f0505845-18ee-48fb-b246-9f0968c78209 request_type=InstallApplication
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=info msg="queued event for device" device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5 command_uuid=736da425-54f6-4908-8de3-e201cfcbb694 request_type=InstallProfile
May 23 01:11:59 ip-172-31-38-116 micromdm[325]: level=info msg="queued event for device" device_udid=564D3DEF-EAC1-7EF3-E67A-B49D8CBADCF5 command_uuid=3da27ac3-f744-45cb-810c-a998cf2420ca request_type=InstallProfile

This log at **May 23 09:01:20** i think that the client start to connect the the MDM server.

May 23 09:01:20 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect

I logon the OS, then installation kick off. total 8 hours. i think that is there any timezone setting may caused this?

May 23 09:13:25 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect
May 23 09:13:25 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect
May 23 09:13:26 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect
May 23 09:13:26 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect
May 23 09:13:26 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect
May 23 09:13:27 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect
May 23 09:13:29 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect
May 23 09:13:29 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect
May 23 09:13:29 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/1.1 host=218.2.208.75 user_agent="MacAppStore/3.0 (Macintosh; OS X 10.15.4; 19E287) AppleWebKit/5609.1.20.111.8" path=/repo/InstallApplications.plist
May 23 09:13:30 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect
May 23 09:13:30 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect
May 23 09:13:31 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect
May 23 09:13:31 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect
May 23 09:13:32 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/1.1 host=218.2.208.75 user_agent="MacAppStore/3.0 (Macintosh; OS X 10.15.4; 19E287) AppleWebKit/5609.1.20.111.8" path=/repo/InstallApplications.pkg
May 23 09:13:32 ip-172-31-38-116 micromdm[325]: transport=http method=PUT status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="MDM-OSX/1.0 mdmclient/1308" path=/mdm/connect
May 23 09:13:33 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/1.1 host=218.2.208.75 user_agent="MacAppStore/3.0 (Macintosh; OS X 10.15.4; 19E287) AppleWebKit/5609.1.20.111.8" path=/repo/InstallApplications.pkg
May 23 09:13:58 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="Python/3.7.4 CFNetwork/1125.2 Darwin/19.4.0 (x86_64)" path=/repo/bootstrap.json
May 23 09:14:00 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="Python/3.7.4 CFNetwork/1125.2 Darwin/19.4.0 (x86_64)" path=/repo/deployments/DEPNotify-1.1.5.pkg
May 23 09:14:27 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="Python/3.7.4 CFNetwork/1125.2 Darwin/19.4.0 (x86_64)" path=/repo/deployments/munkitools_launchd-3.0.3265.pkg
May 23 09:14:30 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="Python/3.7.4 CFNetwork/1125.2 Darwin/19.4.0 (x86_64)" path=/repo/deployments/munkitools_core-3.6.0.3721.pkg
May 23 09:14:35 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="Python/3.7.4 CFNetwork/1125.2 Darwin/19.4.0 (x86_64)" path=/repo/scripts/root/depnotify_welcome.py
May 23 09:14:36 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="Python/3.7.4 CFNetwork/1125.2 Darwin/19.4.0 (x86_64)" path=/repo/scripts/root/caffeinate.py
May 23 09:14:37 ip-172-31-38-116 micromdm[325]: transport=http method=GET status=200 proto=HTTP/2.0 host=218.2.208.75 user_agent="Python/3.7.4 CFNetwork/1125.2

**Comment by jessepeterson** [comment]
This sounds like an APNS issue, @windliyue. For an enrolled device are you able to send commands to a device (using e.g. the [API command tools](https://github.com/micromdm/micromdm/tree/master/tools/api)) and and have the device check-in (should be seconds). If not then you might want to check-out [the troubleshooting guide](https://github.com/micromdm/micromdm/wiki/Troubleshooting-MDM#check-the-topic-for-apns). I'm going to close this issue. For help with basic MDM communication like this please join us in the Slack channel! :)
