### ISSUE TITLE
[Question] How can i get applications usage details using MDM?

### ISSUE THREAD

**Issue by darshanpitpath** [micromdm/micromdm#674]
### What version of `micromdm` are you using?
micromdm version 9e65297
### What `micromdm` command did you run?
we are looking for command to get applications usage details.
### What did you expect to see?
Using MDM solution we would like to get iOS device applications usage details.
### What did you see instead?
we need guidance to get app usage using MDM commands.

   We are able to get list of installed applications and successfully hide / show (blacklist / whitelist) using micro MDM.
  We are looking for user application usage detail using MDM. Can anyone guide me here.

Thanks
darshan panchal
darshanp@itpathsolutions.in

**Comment by jessepeterson** [comment]
What do you mean by "user application usage detail?" Which [MDM command](https://developer.apple.com/documentation/devicemanagement/commands_and_queries?language=objc) are you trying to use to get that information?

**Comment by ekaiser-uptycs** [comment]
Sounds more like they're looking to do something like JAMF's "used application for X hours on Monday, Wed, Fri" or "chrome was open for 8 hours" which... isn't really an MDMcommand featureset.

wontfix?
