### ISSUE TITLE
Help on invalid enrollment mobileconfig

### ISSUE THREAD

**Issue by zhangchn** [micromdm/micromdm#68]
In my test, the service is run as:

```
sudo ~/Downloads/micromdm/build/micromdm-darwin-amd64 \
    -tls \
    -tls-cert=~/1/cert1.pem \
    -tls-ca-cert=~/1/chain1.pem \
    -tls-key=~/1/privkey1.pem \
    -postgres='user=user password=micromdm dbname=micromdm sslmode=disable' \
    -redis='127.0.0.1:6379'  \
    -enrollment-profile=~/Enroll.mobileconfig \
    -push-cert=~/Documents/APSP_2.p12 \
    -push-password='somepassword' \
    -http-address='127.0.0.1:9000' \
    -url='https://my-mdm-service-url:9443/'

```

But I got error messages from both Safari or Mail on my phone, and on macOS I got complains about insufficient `IdentityCertificateUUID` in the payload `com.github.micromdm.mdm`.

Scrutinizing the mobileconfig downloaded from '/mdm/enroll', I confirmed that the value to `IdentityCertificateUUID` was empty.

BTW, the Enroll.mobileconfig was tested ok using Email and Apple Configurator 2.

**Comment by groob** [comment]
For some reason when you save the enroll profile using Configurator, the IdentityCertificateUUID value doesn't match the other dict. I have a section on the enrollment profile in [this blog post](https://groob.io/posts/mdm-experiments/) that might help.

Finally, if you're able to use https://github.com/micromdm/scep server, then passing the Enroll.mobileconfig file is no longer necessary.

**Comment by zhangchn** [comment]
It seems that the enrollment profile would not be loaded until DEP was enabled. However, I cannot get DEP in my use case in the first place.

**Comment by groob** [comment]
@zhangchn right now you have two options for enrollment 
1) If you have DEP you can pass an enrollment profile during setup or
2) Use SCEP and the `/mdm/enroll` endpoint to generate the enrollment profile (This does not require you to pass `Enroll.mobileconfig` anywhere, it will be generated for you. 

You can send a Pull Request to change the above behavior.
