### ISSUE TITLE
API error: /v1/dep/syncnow shows curl: (52)Empty reply from server

### ISSUE THREAD

**Issue by zcy382725** [micromdm/micromdm#689]
### What version of `micromdm` are you using?
v1.7.1

### What `micromdm` command did you run?
curl -k -u micromdm:$API_TOKEN -X POST https://mdm.xxx.xxx/v1/dep/syncnow -v
### What did you expect to see?
sync dep devices from dep-server to micromdm
### What did you see instead?
curl: (52)Empty reply from server

**Comment by jessepeterson** [comment]
Do other API endpoints give you this error or just this one? Do you have a proper DEP token configured and can you sync devices when you e.g. start the MicroMDM daemon (or wait 30 minutes)?
