### ISSUE TITLE
MicroMDM server should be able to use web proxy to connect to api.push.apple.com

### ISSUE THREAD

**Issue by meta-gitub** [micromdm/micromdm#697]
### What version of `micromdm` are you using?
current master branch (GitHub)

### What `micromdm` command did you run?
tools/api/commands/install_profile

### What did you expect to see?
Client should get a push notification and install a profile.

### What did you see instead?
No action on the managed client, because it did not get a push notification. The log of the mdmserver has the following information:

Post "https://api.push.apple.com/3/device/5eaba37c83b6262c4991f6f82b91e5c0e2085dde44afafcd4a3fcda9304265e3": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

This makes sense. Both, managed client and MDM server are running in a firewalled environment. With the latest beta 4 of Big Sur, we can receive push notifications on our clients, because the apsd process is fully proxy-aware. If the mdmserver could make use of our proxy for his post-request, we would be fine. Proxy-auth or ssl-interception are not set for our planned MDM server.

We have configured the proxy by a pac file. I also have tried setting it by environment variables (HTTP_PROXY, http_proxy), but that did not work.

MicroMDM would fit very well into our environment it it just had that feature.

**Comment by groob** [comment]
Does your proxy support HTTP2 both in and out? this is required by Apple for the server requests.

**Comment by meta-gitub** [comment]
Well, I am just a user of our proxy, but profilemanager did get push notifications out to apple's servers. So, yes, I think that the proxy is capable to do this.

**Comment by groob** [comment]
The fix might be as simple as adding http.ProxyFromEnvironment in the transport constructor here: 

https://github.com/micromdm/micromdm/blob/e01ef8a382a4fe0d7e2d707d2d1067b6fe3686c1/platform/apns/service.go#L138

```
 &Transport{
	Proxy: http.ProxyFromEnvironment,
```

and then setting the HTTP_PROXY environment variable. 

I don't have an environment where I can reliably test this, but I'll review a pull request if you make a change and it works for you.

**Comment by meta-gitub** [comment]
I can confirm that this works. I think that I need to be granted permission to push my change to the project.

**Comment by groob** [comment]
you would fork the project, push the change to your fork and then open a pull request. 

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by ppdouble** [comment]
After I set the HTTP proxy, I got an error from the push request.

Post: https://api.push.apple.com/3/device/xxxx-device-token-xxxx : dail tcp lookup api.push.apple.com on [::1]:53: read udp [::1]45034-\u003e[::1]:53: read: connection refused. Is something wrong with IPV6? I am using IPV4 on my server.

**Comment by ppdouble** [comment]
I might set HTTP_PROXY instead of HTTPS_PROXY.  It works now with HTTPS_PROXY and NO_PROXY.
