### ISSUE TITLE
Add flag for control directory listing for build-in filerepo

### ISSUE THREAD

**Issue by trekkim** [micromdm/micromdm#702]
Hi ,
I would like to ask ,
if possible add flag for control directory listing in build in
-filerepo Path to http file repo.

thank you

**Comment by jessepeterson** [comment]
The built-in file repo isn't really meant for production. There are workaround and proposed changes to address: e.g. https://www.alexedwards.net/blog/disable-http-fileserver-directory-listings 

If anyone wants to submit a PR that's great. But I'm going to close this for now: folks can either use the non-code workarounds, or (better) use another server for serving your static files.
