### ISSUE TITLE
PWD commands in ngrok scripts are written with big letters, don't work on linux

### ISSUE THREAD

**Issue by slawoslawo** [micromdm/micromdm#707]
System - Linux Ubuntu
### What version of `micromdm` are you using?
MicroMDM 1.7.1

### What `micromdm` command did you run?
./tools/ngrok/start_server

### What did you expect to see?
component=main msg=started
.......
....

### What did you see instead?
./tools/ngrok/start_server: line 4: PWD: command not found
./tools/ngrok/start_server: line 5: PWD: command not found

**Comment by comtom** [comment]
I just confirmed it's working on my envirnonment (debian linux).

**Comment by slawoslawo** [comment]
Yeah it should work right now.
Thank You for checking that out.
I will close the issue
