### ISSUE TITLE
[CI] Incorrect build status for master branch builds

### ISSUE THREAD

**Issue by comtom** [micromdm/micromdm#714]
Build status indicator in readme.md file is showing all builds as failed.

As CircleCI states: 
`This project is configured to only run builds that have open pull requests associated with them. Update the 'Only build pull requests' setting to run this build.`
So all builds in master branch are being not run (marked as `Not run`). By enabling this, we could see the health of the master branch.

### What did you expect to see?
builds running on all branches

### What did you see instead?
master branch builds are not running and thus, reporting a failure

**Comment by jessepeterson** [comment]
Thanks for the report! We've switched to GitHub Actions. :)
