### ISSUE TITLE
Unenroll / Delete device

### ISSUE THREAD

**Issue by danielerne** [micromdm/micromdm#717]
### What version of `micromdm` are you using?
1.7.1

### What `micromdm` command did you run?
DELETE /v1/devices
with JSON {"udids": ["device-udid"]}

### What did you expect to see?
Success message and deleted device from list

### What did you see instead?
Success message without any data and device is still in the list

**Comment by groob** [comment]
DELETE /devices does not un-enroll the device. It will stay in the list if it checks back in. 

Removing the enrollment profile from the device and then deleting the record should work.

**Comment by danielerne** [comment]
Thanks for the fast reply. 
I did un-enroll the device with removing the profile on the device. The enrollment_state changed to false.
With deleting the record you mean the process with DELETE / devices? It does not work. It's still in the list.

<img width="231" alt="get_devices" src="https://user-images.githubusercontent.com/546931/101388786-b8309500-38c0-11eb-858c-c575100b53b6.png">

**Comment by groob** [comment]
A sample HTTP request/response log would be useful. I don't immediately see why it wouldn't work.

**Comment by groob** [comment]
Also can you try deleting by serial instead?

**Comment by danielerne** [comment]
As described in #883 it works when adding the "Opts" field in the JSON.
