### ISSUE TITLE
[Feature Request] Drop commands that are older then X hours or days

### ISSUE THREAD

**Issue by discentem** [micromdm/micromdm#727]
I'd like to implement the ability to periodically delete commands from the command queue if they are older than X hours or days, perhaps based on a new optional flag. 

I am looking for guidance on the best place in the code base to add this. Perhaps in https://github.com/micromdm/micromdm/blob/main/platform/queue/queue.go? 

Alternatively, does this have to be a periodic function? Could we just drop a command at the time Micromdm would have otherwise executed on it if it's older than X hours/days?

**Comment by groob** [comment]
I think it's a good idea. 

As a start, I'd have you implement a method like `DeleteOlderThan(udid string, t time.Duration)` in queue.go and then we can decide the best way to call your method. 

There's a few possible ways. 

1. Call it every time the device requests a new command. It means it can be added in a single line somewhere, but has the drawback of never clearing queues for un-enrolled devices. 
2. Call it in a new goroutine that runs hourly. Probably my favorite way. 
3. Add a new /clear_queue endpoint where you could call it on your own. I don't think it's necessary to do this.

**Comment by discentem** [comment]
> I think it's a good idea.

👍  :D 
> As a start, I'd have you implement a method like DeleteOlderThan(udid string, t time.Duration) in queue.go and then we can decide the best way to call your method.

I'll get started on this. 

> Call it every time the device requests a new command. It means it can be added in a single line somewhere, but has the drawback of never clearing queues for un-enrolled devices.

Disregarding the drawback and orphaned commands for un-enrolled devices, is this more efficient or "better" for any reason vs. having a separate routine? 

> Call it in a new goroutine that runs hourly. Probably my favorite way.

I will look into this as well. If it's your favorite, that's probably the direction we should go. 

> Add a new /clear_queue endpoint where you could call it on your own. I don't think it's necessary to do this.

I'm interested in exploring this actually. I think it would be useful to pass command UUID and remove that command. 

I don't think it's feasible but it would also be cool to be able to "ask" micromdm's api "do you already have an InstallProfile command for device X with content Y" without knowing the UUID but this goal could be solved by caller's passing custom UUIDs, I think? https://github.com/micromdm/micromdm/pull/672

Would love to know your thoughts here.

**Comment by discentem** [comment]
> Call it in a new goroutine that runs hourly. Probably my favorite way.
> > I will look into this as well. If it's your favorite, that's probably the direction we should go. 

Is there a place in the code where other routines are currently defined? Where is the best place for a new one?

**Comment by groob** [comment]
There are a number of them in the code, including one in queue.go already. 

https://github.com/micromdm/micromdm/blob/4c52a283e012b37f02516451cfee14b3f68a1ae3/platform/queue/queue.go#L263

I'd follow the same pattern, which is : 

- Create a function that sets up your goroutine.
- Call it inside the NewQueue function which is invoked on server startup/when the queue gets created.

**Comment by jessepeterson** [comment]
Just curious on the desire for this feature? Are you seeing issues or problems related to this?

**Comment by discentem** [comment]
We think we are sending many duplicate commands to Micromdm for the same "task". We are just blindly sending them without being able to check if they are already in Micro's queue and, as of now, they don't get evicted. 

Eventually the bolt database grows huge (might be a different issue) and we think there are performance issues when it reaches a certain size.
