### ISSUE TITLE
Communication with apple push servers triggers x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by thomasdereyck** [micromdm/micromdm#734]
### What version of `micromdm` are you using?
1.8.0
### What `micromdm` command did you run?
No command. The issue occurs between client and server.

### What did you expect to see?
When I enroll a Mac, the webhook should trigger and some automated actions should take place. This was working on my micromdm instance for quite a while and suddenly stopped working without any obvious cause.

### What did you see instead?
The webhook is not triggered.
Micromdm reports:
```
Feb 24 16:08:47 micromdm micromdm[8668]: transport=http method=POST status=201 proto=HTTP/1.1 host=10.18.0.2 user_agent=python-requests/2.18.4 path=/v1/commands
Feb 24 16:08:47 micromdm micromdm[8668]: level=info msg="queued event for device" device_udid=E870EDA1-AE1F-5C33-9D43-D565BFB87EDC command_uuid=4f0adf33-f552-4ed3-857c-bcd5da8ca0f7 request_type=DeviceInformation
Feb 24 16:08:47 micromdm micromdm[8668]: Post "https://api.push.apple.com/3/device/c7d441ed13c29b4533bd389f6b3cfd323227efeb8bc7179cbc48db746dcd70cc": x509: certificate signed by unknown authority
Feb 24 16:08:48 micromdm micromdm[8668]: Post "https://api.push.apple.com/3/device/c7d441ed13c29b4533bd389f6b3cfd323227efeb8bc7179cbc48db746dcd70cc": x509: certificate signed by unknown authority
```
As far as I'm aware, my push cert is still valid. Is it possible that Apple is using a new authority that is not yet present in the CA store? Is there any way for me to find out what certificate it is exactly referring to and what communication is happening at that time? There does not seem to be a verbose or debug option?

Do note that I tried to access the MacAdmins slack, but the service to receive an invitation seems down. Hence I'm reporting this here.

Thanks in advance.

**Comment by jessepeterson** [comment]
You likely need to add the GeoTrust CA to your server OS's root trust store. See [Apple's announcement](https://developer.apple.com/news/?id=7gx0a2lp).

I.e. for Ubuntu-based systems:

```
$ wget https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem
$ sudo cp GeoTrust_Global_CA.pem /usr/local/share/ca-certificates/GeoTrust_Global_CA.crt
$ sudo update-ca-certificates --fresh
```

(From a comment in #723)

**Comment by thomasdereyck** [comment]
Hi Jesse,

My system was Ubuntu based, so I tried your instructions and everything is indeed working as usual again.

Thanks for your quick follow-up!
