### ISSUE TITLE
Bootstrap Token

### ISSUE THREAD

**Issue by meta-github** [micromdm/micromdm#735]
### What version of `micromdm` are you using?
1.8.0

### What `micromdm` command did you run?
On the DEP enrolled client: `profiles status -type bootstraptoken`

### What did you expect to see?
micromdm should support the bootstrap token protocol.

### What did you see instead?
`profiles: Bootstrap Token supported on server: NO`

Bootstrap token (introduced by macOS Catalina) help to get secure token to user accounts and to authorize software updates (which makes a big difference on Apple Silicon). If I currently issue a ScheduleOSUpdate command to a DEP enrolled client running macOS 11.2.3 on Apple Silicon, that commands will not get executed unless it is locally authorized by an admin account with secure token. Botstap Token support would be a great help to get **unattended software updates** on the Apple Silicon platform.

From the MDM point of view, Bootstrap Token is a set of commands the MDM server must be able to handle. It is not some kind of MDM payload or configuration. The protocol is described by Apple as part of the [Check-in](https://developer.apple.com/documentation/devicemanagement/check-in) command.

**Comment by jessepeterson** [comment]
Just a note that you can trivially fool the OS into thinking the MDM server supports bootstrap tokens by adding `com.apple.bootstraptoken` to the `ServerCapabilities` array in the MDM enrollment profile payload. But, as you noted there are specific `MessageTypes` to handle as part of the MDM check-in protocol.

_Technically_ MicroMDM may not need to "support" the tokens so much as make sure they are passed on to the Webhook (for any integrations to handle) but we may want to integrate them into the device storage for "native" support, too.

**Comment by tomaswallentinus** [comment]
The second sounds like a great idea. If micromdm doesn't recognise the endpoint or payload it could just forward it to the webhook.

**Comment by ivanhata** [comment]
I'd really much like to see this implemented way or another. So +1 defenitely.

I've been playing with the idea that I'd give this a try. Lack of go skills are holding me back a bit at least. Also my understanding of micromdm's internal design could be better :)

Anyway, what would be the best places to put the different parts of the implementation? Some would be quite obvious and copy-paste-replace could be enough, maybe. But especially the responses the server should be sending to the client. To my understanding, this is a bit different from all the previous where the server is usually the one sending requests and the client responding. Now it's the opposite. I haven't been able to find a suitable example from the existing code.

**Comment by ivanhata** [comment]
I started working with this and got that far that the client escrows the bootstrap token and it gets saved to micromdm's database.

Now I'm a bit stucked. I haven't been able to figure out what would be the best way to fetch the bootstrap token from the database and send it back to the client when it asks for it in the GetBootstrapTokenRequest (https://developer.apple.com/documentation/devicemanagement/get_bootstrap_token).

Currently, the checkin.go nor the whole mdm package has no direct access to the database. Would it be ok to just implement what is needed to access the database directly for fetching the bootstrap token? Or would something like pubsub, api or something else be more suitable and maybe more in line with micromdm's internal design? I would appreciate any advice or tips.

**Comment by jessepeterson** [comment]
Cool! I've been thinking about this, too! Would love to see the PR soon. How have you implemented things now?

Without having looked in-depth what I'd probably do is create a new interface intended for a service to implement such as (forgive the formatting/syntax - on mobile):

```
type BootstrapTokenRetriever interface {
GetBootstrapToken(ctx, checkin) (bootstrap,error)
}
```

Then I would make the device service implement that interface (reading from the device db) and pass it into the `mdm.NewService` so it could use it. This'll likely make the init code more complicated.

Token storage (setting) I'd probably run through the pub sub to keep it consistent (and to get it published to the webhook).

Again this is just initial thoughts and I'd want to see the proposed code to think about it more but I hope that helps!

Thanks for looking at this!

**Comment by ivanhata** [comment]
Sorry for the silence and the delay. It stretched longer than I meant.

Thanks for the advice! I spend some time trying to understand and find the correct places to add the code. Well, didn't get much done.

I think I just push the working code I have to my github now. Should I also make a PR even tough the implementation is yet partial?

**Comment by ivanhata** [comment]
I just pushed the code to https://github.com/ivanhata/micromdm, commit 86d5291
