### ISSUE TITLE
GET "https://micromdm.acme.com": x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by davidegurgone** [micromdm/micromdm#739]
### What version of `micromdm` are you using?
1.8.0

### What `micromdm` command did you run?
mdmctl get dep-tokens -export-public-key /tmp/DEPPublicKey.pem

### What did you expect to see?
Download DEPPublicKey.pem file here: /tmp/DEPPublicKey.pem

### What did you see instead?
Get "https://micromdm.myserver.com/v1/dep-tokens": x509: certificate signed by unknown authority

On the server I can see in logs:
ts="2021/04/16 16:19:01" caller="http: TLS handshake error from IPADDRESS:35756" msg="remote error: tls: bad certificate"

Hi, I am setupping a new micromdm server for development reasons, but I am not able to complete DEP Configuration because I cannot download the pem file to be uploaded to apple.

How can I investigate / fix this?

Thanks, Davide

**Comment by jessepeterson** [comment]
Hi David. Do other `mdmctl` actions work (like getting a list of enrolled devices or pushing, etc.)? This seems like a problem with `mdmctl` connecting to micromdm in general, rather than a specific DEP/token problem.

**Comment by molekola-io** [comment]
Hi Jesse, 
Thanks for your reply.

I tried this and have the same issue:

```sh
./mdmctl get devices
UDID  SerialNumber  EnrollmentStatus  LastSeen
Post "https://micromdm.youco.mobi/v1/devices": x509: certificate signed by unknown authority
```

**Comment by davidegurgone** [comment]
Hi Jesse, 
Thanks for your reply.

You right, I tried this and have the same issue:

```sh
./mdmctl get devices
UDID  SerialNumber  EnrollmentStatus  LastSeen
Post "https://micromdm.youco.mobi/v1/devices": x509: certificate signed by unknown authority
```

**Comment by davidegurgone** [comment]
Hi Jesse,
I fixed by adding the CA on my mac.

Why do I need this? This is a valid CA?

Anyway, it works 🎇🎆🎇👍🏻👍🏻👍🏻
Thanks for the support

**Comment by jessepeterson** [comment]
Hi @davidegurgone glad it worked for you. I'm not sure why it's needed. Go usually uses the system's certificate store even on a Mac (it reads the keychain). You'd have to find out why Golang wasn't seeing the CA. It looks like that server only presents a single cert and relies on AIA attributes to fetch the intermediates? Maybe adding the intermediate certs to the server config may help. Glad it worked out for you, though!
