### ISSUE TITLE
Database grows because of queued commands

### ISSUE THREAD

**Issue by danielerne** [micromdm/micromdm#746]
### What version of `micromdm` are you using?
1.7.1

Currently there's a problem with commands staying in the queue because devices are not connected every time. 
We fixed it by checking the last_seen param but the database is still 2gb large now.
Is there a command to clean the queue?

**Comment by korylprince** [comment]
I think the only way to remove them is via editing the database itself or through a re-enrollment. See Issue #646. I think this is one of the reasons behind PR #736.

**Comment by jessepeterson** [comment]
Ongoing I'd suggest the `-no-command-history` (from #640). BoltDB has no way to "regain" space, but for an existing database you can remove all previous saved commands in the queue: https://github.com/micromdm/micromdm/wiki/Tips-&-Tricks#remove-the-entire-command-queue

**Comment by danielerne** [comment]
Great! Thanks for the fast reply. The wiki helped a lot and it works with boltcopy.
Now the database is only 2mb
