### ISSUE TITLE
lights out management

### ISSUE THREAD

**Issue by meta-github** [micromdm/micromdm#770]
It would by quite cool to be able to use the lights out management functions (PowerON, PowerOFF, Reset) that are available on the MacPro and the M1 Mac Mini with 10 Gigabit Ethernet port.

### What version of `micromdm` are you using?
v1.8

### What `micromdm` command did you run?
I did not find the necessary support for LOMDeviceRequestCommand and LOMSetupRequestCommand in the source code, so I did not even try to run a command.

### What did you expect to see?
An implementation of these commands along with caller script for the api.

### What did you see instead?
Commands not yet implemented.

A point to start is https://9to5mac.com/2020/06/24/whats-new-with-apple-device-management/ and  https://developer.apple.com/documentation/devicemanagement/lightsoutmanagementlom.

**Comment by korylprince** [comment]
These commands were added in #839.
