### ISSUE TITLE
ApplicationAttributes command not working as expected.

### ISSUE THREAD

**Issue by NithinMD** [micromdm/micromdm#774]
### What version of `micromdm` are you using?

1.8

### What `micromdm` command did you run?

ApplicationAttributes command

source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "Settings" \
  --arg udid "$1" \
  --arg identifier "com.google.chrome.ios" \
  --arg attributes "32f47c5f-027d-4434-ac64-ff74da2e42za"} \
 '.udid = $udid 
  |.request_type = $request_type
  |.settings[0].item = "ApplicationAttributes"
  |.settings[0].identifier = $identifier
  |.settings[0].attributes["vpnUuid"] = $attributes
  '|\
  curl $CURL_OPTS -K <(cat <<< "-u micromdm:$API_TOKEN") "$SERVER_URL/$endpoint" -d@-

 
### What did you expect to see?

I expect a response with VPNUUID set to Application. 

### What did you see instead?

I'm trying to enable per-app vpn for third party apps like Google Chrome in iOS. Intially I installed Chrome app using Install Appstore application command in tools/api/commands. After that I called ApplicationAttributes command (I wrote it myself based on mdm.proto and marshal_proto class codes and Apple documentation) to set VPNUUID for Chrome app. But in device the VPN is not turning on when chrome app is opened. 

I run the above ApplicationAttributes command to set VPNUUID

For every command I run from server, I got a connect back from device with command uuid. 

**Response got from device back to server**

<plist version="1.0">
<dict>
    <key>ApplicationAttributes</key>
    <array>
        <dict>
            <key>Attributes</key>
            <key>Identifier</key>
            <string>com.google.chrome.ios</string>
        </dict>
    </array>
    <key>CommandUUID</key>
    <string>0001_ApplicationAttributes</string>
    <key>Status</key>
    <string>Acknowledged</string>
    <key>UDID</key>
    <string>00008020-000915083C80012E</string>
</dict>
</plist>

But the response don't have the VPNUUID set for the application.
I also tried changed the key to VPNUUID like this 

   |.settings[0].attributes["vpnUuid"] = $attributes

and it results **in curl (52) Empty reply from server**

For Safari Domains, per app vpn is enabled when URLs opened. I tried to debug the situation by adding some log statements in source code and build it. But none of the logs got printed. 
APNS is working fine with Micromdm server. Other commands like install profile, install application... works correctly. 

How can I fix the per-app VPN issue?

**Comment by jessepeterson** [comment]
Have you tried to run the server with the `-dubug` switch to see that the proper command that you want is delivered and run? You say it seems to work okay for Safari? Are you sure we've got the identifiers correct? Sorry, I've not played with per-app VPN so unsure how to better help.

**Comment by jessepeterson** [comment]
We closing this issue because we asked follow-up questions and didn't receive a reply. If this is still an issue for you may re-open it or feel free to join in the `#micromdm` channel on the [MacAdmins Slack](https://www.macadmins.org/). Thanks!
