### ISSUE TITLE
How are you all getting MDM CSR approval?

### ISSUE THREAD

**Issue by icanhazpython** [micromdm/micromdm#776]
### Discussed in https://github.com/micromdm/micromdm/discussions/775

<div type='discussions-op-text'>

<sup>Originally posted by **icanhazpython** September 27, 2021</sup>
Apple is saying that you need the enterprise developer account, which has a pre-req that you have 100+ employees. This is an absolutely ridiculous requirement in my opinion. I would assume that many of those working on this project aren't working in an org with 100+ employees, so can anyone enlighten me on the best way to get MDM CSR capabilities so I can implement this?!
Thanks!</div>

**Comment by icanhazpython** [comment]
I just found #660. I think the guide at https://github.com/micromdm/micromdm/blob/main/docs/user-guide/quickstart.md should be modified so that it mentions mdmcert.download. Most people will probably end up on these pages and not the wiki pages first.

I went through the trouble of trying to get this from Apple only to find out that I need to have > 100 employees, at which point I promptly proceeded to pop my top and call out Apple support in the most restrained manner that was possible for me. Now I feel relieved, yet dumb. Please update the docs!

**Comment by jessepeterson** [comment]
PRs welcome. :)

But more seriously: folks shouldn't be using mdmcert.download for production MDM certificate acquisition. It's intended more for testing, or perhaps if folks are unable to afford the Apple Developer program. I realize that puts folks in a bind, but this is what Apple has provided.

I'm gonna close this for now as, indeed, we don't want to encourage mdmcert.download usage, and rather direct folks at Apple. Good on you for having the patience to talk with Apple about it though! Also as per #775 there is some push-back you can do for Apple on the 100 employee limit.
