### ISSUE TITLE
creating new auth session for dep: establishing DEP session: 400 Bad Request

### ISSUE THREAD

**Issue by Zyuxing** [micromdm/micromdm#777]
### What version of `micromdm` are you using?
v1.8.0
### What `micromdm` command did you run?
/mdmctl apply dep-profiles -f filerepo/profile.json -filter='*'
### What did you expect to see?
define dep profile: define profile: get session for request to https://mdmenrollment.apple.com: creating new auth session for dep: establishing DEP session: 400 Bad Request

**Comment by korylprince** [comment]
Have you already done the steps [here](https://github.com/micromdm/micromdm/wiki/Connect-MicroMDM-with-DEP)?
i.e. Create a server in ABM/ASM, download the token, and upload it to micromdm? If not that's going to be your issue.

Can you run `mdmctl get dep-devices -serials <serial assigned in ABM/ASM>` successfully?

Can you post `filerepo/profile.json` (redacted if needed)? Also, does jq parse that file okay?

**Comment by Zyuxing** [comment]
> Have you already done the steps [here](https://github.com/micromdm/micromdm/wiki/Connect-MicroMDM-with-DEP)? i.e. Create a server in ABM/ASM, download the token, and upload it to micromdm? If not that's going to be your issue.
> 
> Can you run `mdmctl get dep-devices -serials <serial assigned in ABM/ASM>` successfully?
> 
> Can you post `filerepo/profile.json` (redacted if needed)? Also, does jq parse that file okay?

After MY reinstallation, there is no such exception, but there is a new problem, automatic registration does not take effect
`./mdmctl get dep-devices -serials ABM` The following results are obtained
`SerialNumber  Model  DeviceFamily  ProfileStatus  ProfileUUID`

`./mdmctl get dep-devices -serials ASN` The following results are obtained
`SerialNumber  Model  DeviceFamily  ProfileStatus  ProfileUUID`

Here is my filerepo/profile.json
>{
  "profile_name": "profile",
  "url": "https://mdm.shuzifuyu.com/mdm/enroll",
  "allow_pairing": true,
  "is_supervised": false,
  "is_multi_user": false,
  "is_mandatory": false,
  "await_device_configured": false,
  "is_mdm_removable": true,
  "support_phone_number": "",
  "support_email_address": "",
  "org_magic": "(Optional)",
  "anchor_certs": [],
  "supervising_host_certs": [],
  "skip_setup_items": ["AppleID", "Android"],
  "department": "Engineering",
  "devices": ["DMPRX6JDH1MV","F4GR4LEDGRYC"]
}

**Comment by Zyuxing** [comment]
> Have you assigned those devices in ABM/ASM to your MDM instance?
> 
> You may need to run a [DEP sync](https://github.com/micromdm/micromdm/blob/main/tools/api/sync_dep_devices) to have it pick up the changes, as that only runs periodically.
> 
> Also, you may want to redact the url and serials in your profile, so they aren't used maliciously.

I've run this command, but I still can't see any devices registered in the DEP
`curl -v -u micromdm:password -X POST https://template/v1/dep/syncnow`
I'm using Apple school Management
You can register devices manually only through the Apple Configurator 2

**Comment by Zyuxing** [comment]
Use the following command to get a result
`./mdmctl get dep-account`
OrgName            OrgPhone           OrgEmail              ServerName
xxxxx  +86 181 xxxx xxxx  school_open@xxxx.cn  DEPMDM

Should the Apple ID of OrgEmail match the domain name of Server_URL?

**Comment by Zyuxing** [comment]
> 域是否不匹配应该无关紧要。根据您之前的评论，我在理解您要完成的任务时遇到了一些麻烦。
> 
> 在 Apple 校园教务管理中，单击左栏中的设备。那两个序列号在那里吗？如果是这样，您是否将他们的设备管理编辑为您的 micromdm 实例（即与您上传到 micromdm 的令牌关联的 MDM）？
> 
> 如果它们没有出现在 Apple School Manager 中，那么您需要通过[此方法](https://www.hexnode.com/mobile-device-management/help/add-ios-11-devices-to-dep-using-apple-configurator/)添加它们[](https://www.hexnode.com/mobile-device-management/help/add-ios-11-devices-to-dep-using-apple-configurator/)

If the Apple Configurator 2 manual registration device exists, but I want to automatically register to DEP without contact, if the manual registration using the Apple Configurator 2 does not meet my expectations, will Apple allow this?

**Comment by korylprince** [comment]
I'm having trouble understanding what you're asking. Can you explain a bit more?

**Comment by Zyuxing** [comment]
After your answer, I have understood, thank you!
