### ISSUE TITLE
MDM CSR Renewing

### ISSUE THREAD

**Issue by danielerne** [micromdm/micromdm#780]
It is more a question but couldn't find a proper location to ask this and maybe someone had this too.
We reached the maximum amount of 3 MDM CSR on our account and we need to update the MDM CSR. Is it safe to revoke one without loosing any enrolled devices?
I know if we revoke one of the Distribution Certificates all Inhouse apps gets invalid. Which was a total mess.

And can we use one MDM CSR for multiple MDM instances?

**Comment by jessepeterson** [comment]
> Is it safe to revoke one without loosing any enrolled devices?

I think what you're asking is: if you revoke or remove an MDM CSR in the portal, do the resulting MDM Push certificates also get revoked? *Officially* this is a question for Apple developer relations. They'll be able to give you the definitive answer. *Unofficially* we've also reached the limit, had to revoke one of them, and been just fine.

> And can we use one MDM CSR for multiple MDM instances?

Also a question for Apple developer relations. That said: MDM CSRs sign push certificate requests. The push certs can be used by pretty much any MDM in my experience. In general Apple advises a single push certificate for each and every customer of an MDM. So if I understand your question correctly I don't think there'd be an issue with this. You can freely mix and match push certificates with MDMs, in my experience.


I'll go ahead and close this as MicroMDM doesn't have much to do with MDM CSRs directly (this is all within Apple's control). You can open a Discussion thread (or come ask about this in Slack) if you have further questions, though. Thanks!
