### ISSUE TITLE
What happened to the slack channel invite page ?

### ISSUE THREAD

**Issue by Elf36** [micromdm/micromdm#787]
The invite page for Slack has gone

### What version of `micromdm` are you using?
About to install

### What `micromdm` command did you run?
NA

### What did you expect to see?
NA

### What did you see instead?
NA

**Comment by arubdesu** [comment]
Putting aside the question 'is this really a code issue'... you're wondering about macadmins.org's Slack signup page? If you need an invite because the one on the macadmins.org website isn't working please confirm what email you want it sent to.

**Comment by macmule** [comment]
This isn't an issue with this project, but the macadmins slack (which I'm an admin of).

I cannot see any pending invites, do you know someone on the slack? Can you perhaps ask them to DM me your email and I'll sort?

**Comment by Elf36** [comment]
I will see thanks.
The invite page is Blank but I will see about DM’ing them separately

**Comment by jessepeterson** [comment]
Looks like the project is having some issues with the invite page:

> We are currently investigating issues with this invite form. If you don’t receive an invite automatically please contact us via the [Contact Us](https://www.macadmins.org/contact) page for assistance.

I'm going to close this issue as it's not directly related to the MicroMDM project. Please follow-up with the contact us form. Thanks!
