### ISSUE TITLE
I'm not getting slack invitation email. 

### ISSUE THREAD

**Issue by vinaykarora** [micromdm/micromdm#788]
I am trying to join your slack workspace by entering my email id at https://www.macadmins.org/

**Comment by macmule** [comment]
This isn't an issue with this project, but the macadmins slack (which I'm an admin of).

I cannot see any pending invites, do you know someone on the slack? Can you perhaps ask them to DM me your email and I'll sort?

I cannot see any invites for the email linked within your github account either.

**Comment by vinaykarora** [comment]
When I entered my email on this link https://www.macadmins.org/  it showed “This email already registered” but I really didn’t received any invitation email. 

Even I don’t know anyone on the slack. Can you share other way to join the slack group?

![736481A5-A9EE-4DCB-8FD6-E1B9E65567BC](https://user-images.githubusercontent.com/6479185/146069463-fdf864d3-7fb8-4201-a300-c2bfcc84b53d.png)

**Comment by vinaykarora** [comment]
I tried with new email, is showed success message but the invitation email is not received yet. Can you please see if there is any issue on “Get my invite” functionality
