### ISSUE TITLE
Does micromdm support load balancer

### ISSUE THREAD

**Issue by sunShuShu** [micromdm/micromdm#789]
I'm a newbie, can someone give me some hints

**Comment by korylprince** [comment]
MicroMDM uses BoltDB for it's underlying database, which only supports a single writing process. So to run multiple instances of MicroMDM, you'd have to find some way to actively replicate the database between instances. I'm not sure if something like that already exists.

I could also see there being issues with the DEP sync, as there would be no coordination between different micromdm instances.

@jessepeterson might have a better answer on this.

**Comment by sunShuShu** [comment]
> MicroMDM uses BoltDB for it's underlying database, which only supports a single writing process. So to run multiple instances of MicroMDM, you'd have to find some way to actively replicate the database between instances. I'm not sure if something like that already exists.
> 
> I could also see there being issues with the DEP sync, as there would be no coordination between different micromdm instances.
> 
> @jessepeterson might have a better answer on this.

It seems that the load balancer solution is not mature, so I may need a higher configuration server instead of a distributed server. Thank you very much for your reply.

**Comment by jessepeterson** [comment]
If you're looking for a horizontally scalable open source MDM solution, I'd take a look at [NanoMDM](https://micromdm.io/blog/introducing-nanomdm/). If you're asking if MicroMDM can be put behind a reverse proxy: yes, that does work.

All that said, The Q&A section of discussions might be a better forum for this: https://github.com/micromdm/micromdm/discussions/categories/q-a

Thanks!
