### ISSUE TITLE
Add suppprt for MaxUserDeferrals  in ScheduleOSUpdate

### ISSUE THREAD

**Issue by meta-github** [micromdm/micromdm#790]
Apple's documentation for ScheduleOSUpdate
(https://developer.apple.com/documentation/devicemanagement/scheduleosupdatecommand/command/updatesitem) mentions the parameter MaxUserDeferrals which sounds interesting. I'd like to play with it, but mircomdm currently does not support it.

### What version of `micromdm` are you using?
1.9.0-beta

### What `micromdm` command did you run?
ScheduleOSUpdate

### What did you expect to see?
Support for the parameter MaxUserDeferrals.

### What did you see instead?
The parameter is currently not supported.

**Comment by jessepeterson** [comment]
Should be fairly straight forward to add the newly supported keys here, for anybody who wants to give it a shot:

```diff
diff --git a/mdm/mdm/command.go b/mdm/mdm/command.go
index 5dd4e4d..3adde98 100644
--- a/mdm/mdm/command.go
+++ b/mdm/mdm/command.go
@@ -278,6 +278,8 @@ type SetAutoAdminPassword struct {
 type OSUpdate struct {
        ProductKey       string `json:"product_key"`
        InstallAction    string `json:"install_action"`
+       MaxUserDeferrals int    `json:"max_user_deferrals"`
+       ProductVersion   string `json:"product_version"`
 }
```

Then, of course, the proper JSON, Plist, and Protobuf marshalling/unmarshalling needs to happen, and for good measure a end-to-end test would be nice. :)

**Comment by meta-github** [comment]
If someone could write a step-by-step guide, I could try to implement this (and possibly fill other gaps)... I am not unable to do programming, but I am totally new in golang and its tools.

**Comment by korylprince** [comment]
This isn't really a guide, but you can take a look at my PR to see the changes. There's a lot of commands/fields already coded for, so you can just match the code. Probably the hardest part is making sure you get the right protobuf compiler versions.

Jesse really covered the whole process, though a little more succinctly:

- Add the fields to the struct in command.go
  - I also updated the struct tags to omit empty optional fields
- Add the fields to the .proto file and run go generate (this assumes you have the correct protoc and protoc-gen-go versions in your $PATH)
- Add the fields to the proto marshal and unmarshal functions, matching existing code
  - the json and plist marshal/unmarshaling just use the whole struct, so there's no changes needed here
- Add a couple of tests matching the existing tests
