### ISSUE TITLE
send_push_notification return unexpected EOF or connection reset by peer

### ISSUE THREAD

**Issue by macBerlin** [micromdm/micromdm#794]
Hello, i am able to enroll devices via DEP but i am not able to send any APNS Commands.

### What version of `micromdm` are you using?
Version 1.8

### What `micromdm` command did you run?
send_push_notification 
### What did you expect to see?
success message 

### What did you see instead?
user@myserver% ./send_push_notification 061BF70B-C320-5561-B45C-84AC072788CB
{
  "error": "Post \"https://api.push.apple.com/3/device/35aa8f2996b8c3640e793bbb88be59a0a7aa076fc8ca472902d92071672bddbf\": unexpected EOF"
}

#### Built System
MacBook Pro M1 macOS Monterey 12.1 

#### micromdm output
level=info component=apns method=Push udid=061BF70B-C320-5561-B45C-84AC072788CB err="Post \"https://api.push.apple.com/3/device/35aa8f2996b8c3640e793bbb88be59a0a7aa076fc8ca472902d92071672bddbf\": unexpected EOF" took=526.809375ms
transport=http method=GET status=500 proto=HTTP/2.0 host=84.170.155.41 user_agent=curl/7.77.0 path=/push/061BF70B-C320-5561-B45C-84AC072788CB

**Comment by korylprince** [comment]
Have you [uploaded an APNS cert signed by Apple](https://github.com/micromdm/micromdm/blob/master/docs/user-guide/quickstart.md#configure-an-apns-certificate) to MicroMDM?

**Comment by macBerlin** [comment]
yes, sorry the cert does not match to the key file. Is now fixed.
