### ISSUE TITLE
Apple Push Cert "Invalid Certificate Signing Request"

### ISSUE THREAD

**Issue by hans0801** [micromdm/micromdm#796]
### What version of `micromdm` are you using?
v1.8.0
### What `micromdm` command did you run?
mdmctl mdmcert vendor -password=mysecret -country=ID -email=myemail@email.id
mdmctl mdmcert push -password=mysecret -country=ID -email=myemail@email.id
mdmctl mdmcert vendor -sign -cert=./mdm-certificates/VendorCertificateRequest.csr -password=mysecret
### What did you expect to see?
Successful for sign VendorCertificateRequest.csr at Apple APNS , when i tried for upload and process the VendorCertificateRequest.csr  , apple said that "Invalid Certificate Signing Request. The certificate signing request you entered appears to be invalid. Make sure that request file was uploaded is in the correct format and not empty."
I'm Using Ubuntu Server 20 
### What did you see instead?
-

**Comment by tomaswallentinus** [comment]
@hans0801 You are suppose to select "MDM CSR" on https://developer.apple.com/account/resources/certificates/list and upload the file? Not APNS.

**Comment by jessepeterson** [comment]
There doesn't seem to be any follow-up after clarifications have been asked for. Closing this issue.
