### ISSUE TITLE
Use "trusted certificates." Sign mobileconfig display Unverified,in mobile.

### ISSUE THREAD

**Issue by chengziqing** [micromdm/micromdm#806]
use cmd:
./mdmctl apply profiles -cert ./1.p12 -password 12345678 -sign -f temp.mobileconfig -out m.mobileconfig
1.p12 is "The Developer ID certificates from Apple are examples of trusted certificates." 

But  m.mobileconfig display Unverified,in mobile.
![image](https://user-images.githubusercontent.com/1002998/155665626-0fe6a44d-b624-4fb1-a1f0-31e3cc7f1fae.png)

**Comment by chengziqing** [comment]
use cmd:
usr/bin/security cms -S -N 'Your KeyChain Cert' -i profile.mobileconfig -o signed.mobileconfig

mobileconfig is verify

**Comment by jessepeterson** [comment]
It looks like your device doesn't trust the certificate that you used to sign the profile. I'm not sure why. Try another certificate perhaps?

**Comment by jessepeterson** [comment]
We closing this issue because we asked follow-up questions and didn't receive a reply. If this is still an issue for you may re-open it or feel free to join in the `#micromdm` channel on the [MacAdmins Slack](https://www.macadmins.org/). Thanks!
