### ISSUE TITLE
How to know the webhook is running

### ISSUE THREAD

**Issue by 0xC4m3l-jiang** [micromdm/micromdm#808]
### What `micromdm` command did you run?
sudo ./micromdm serve \
  -server-url=https://mdm.example.org \
  -api-key Axxxxxx0 \
  -filerepo ./filerepo \
  -tls-cert ./mdm-certificates/server.crt \
  -tls-key  ./mdm-certificates/server.key \
  -command-webhook-url http://12.0.0.1:8888/webhook
### What did you expect to see?
i build webhook  
```bash
> python webhook.py
 * Serving Flask app "webhook" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:8888/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 142-395-790
 ```
and i use command ./tools/api/get_devices
but the webhook dont get information
### What did you see instead?
how to know the webhook is running?

**Comment by jessepeterson** [comment]
The webhook calls back to the URL every time an enrolled device communicates to the MDM server. When you directly query MicroMDM's API no webhook activity happens (as this is not from a client enrolled in MDM). Hope that helps!

**Comment by jessepeterson** [comment]
We closing this issue because we asked follow-up questions and didn't receive a reply. If this is still an issue for you may re-open it or feel free to join in the `#micromdm` channel on the [MacAdmins Slack](https://www.macadmins.org/). Thanks!
