### ISSUE TITLE
Issue unique SCEP challenges per device.

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#81]
Right now the embedded SCEP server does not issue any challenge passwords for SCEP. 
MicroMDM should create (and keep track of) a unique password for each enrollment and only allow a single use. 

Alternatively create a short lived token which would expire in <1 minute( but this would cause issues with enrollment profiles which need to be emailed to a user).

**Comment by jessepeterson** [comment]
I think the 'each-enrollment-token' would work very well. As an option an admin can "bless" one of the tokens with an expiry of >1min for re-usable enrollment profile scenarios.

**Comment by loyaltyarm** [comment]
What about in "non-user" scenarios, where devices need to be enrolled but users are arbitrary in the case of kiosk devices. Blessing the token would be the best option here, would the token be set within the enrollment `.mobileconfig`?

**Comment by groob** [comment]
Yes, if you look at what is being returned by /mdm/enroll, a SCEP payload is there, and it should container the scep challenge for that device.

**Comment by Beanow** [comment]
There's a related need we have coming from SimpleMDM, which is including a single use code in the checkin url to know who initiated the enrolment. This allows a kind of invite token metadata to be added to the enrolment process.

**Comment by WardsParadox** [comment]
Did not meant to reference this issue and accidentally close it. Sorry @groob

**Comment by jessepeterson** [comment]
Resolved with #642. Also I think server parameter passing through to the webhook fulfills some of this, too.
