### ISSUE TITLE
error on parsing private key.

### ISSUE THREAD

**Issue by cybercoder** [micromdm/micromdm#812]
### What version of `micromdm` are you using?
1.9.0
### What `micromdm` command did you run?
mdmctl mdmcert upload \                                                                                                                          
    -cert mdm-certificates/MDM_XXX.pem \
    -private-key mdm-certificates/PushCertificatePrivateKey.key \
    -password=PASSWD
### What did you expect to see?
upload successful
### What did you see instead?
load push certificate: parse push certiificate private key mdm-certificates/PushCertificatePrivateKey.key: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:73 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} int @2
### How you've generated push csr and key?
```openssl req -newkey rsa:2048 -keyout PushCertificatePrivateKey.key -out csr.csr```

**Comment by jessepeterson** [comment]
Have you tried using `mdmctl` tool to generate the CSR and private key instead of `openssl`?

**Comment by cybercoder** [comment]
> Have you tried using `mdmctl` tool to generate the CSR and private key instead of `openssl`?

Yes, you right, but that part is missing in the documentation and I found that inside codes.
Thanks.
