### ISSUE TITLE
Question: how to update wallpapers?

### ISSUE THREAD

**Issue by Displee** [micromdm/micromdm#820]
This is a question, not an issue.

How do I update the wallpaper of the lock or home screen using MicroMDM?

**Comment by Displee** [comment]
Are you sure about that? I do see a `WallpaperSetting` in the mdm proto buffers and also just stumbled upon this thread: https://developer.apple.com/forums/thread/9008

I also found this:
https://developer.apple.com/documentation/devicemanagement/settingscommand/command/settings/wallpaper

So according to the Apple docs there seems to be a wallpaper setting I guess?

**Comment by tomaswallentinus** [comment]
In that case you use the following syntax:

`curl --location --request POST 'https://*******/v1/commands' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic ********' \
--data-raw '{
    "request_type": "Settings",
    "udid": "********",
    "settings" : [
        {"Image":"*********","Where":"*******","item":"Wallpaper"}
    ]
}'`

**Comment by Displee** [comment]
That works perfectly, thanks a lot!

Maybe a stupid question but, is it possible to put settings like these in the profile?

**Comment by ayush5harma** [comment]
> That works perfectly, thanks a lot!
> 
> Maybe a stupid question but, is it possible to put settings like these in a configuration profile @tomaswallentinus ?

Through configuration profile we can only set restrictions, the one related to wallpaper being allowWallpaper
Modification but there isn't anyway to apply wallpaper using it.
