### ISSUE TITLE
MDM CSR - Unable to find the CSR Option

### ISSUE THREAD

**Issue by Elf36** [micromdm/micromdm#822]
### What version of `micromdm` are you using?
This one

### What `micromdm` command did you run?
NA

### What did you expect to see?
NA

### What did you see instead?
NA

We are just having issues actually finding the CSR option in the Apple Enterprise Developer Portal - has it moved ?

**Comment by jessepeterson** [comment]
You'll want to reach out to Apple Developer Support https://developer.apple.com/contact/ to make sure your MDM CSR option is available. I'm not aware of the option moving.
