### ISSUE TITLE
How to install/update apps silently or without the Apple ID?

### ISSUE THREAD

**Issue by colin1994** [micromdm/micromdm#825]
I am using the **InstallApplication** command to install an app from the **App Store**. But it requires the user to enter an Apple ID to complete. I have a few questions and hope to get help:

1. How to install apps silently or without the Apple ID?
2. Does **InstallApplication** work with **Update**?
3. Does MicroMDM support **VPP**?

Thanks.

**Comment by jessepeterson** [comment]
There's a number of things required to get silent app installs. Check out https://simplemdm.com/install-apps-silently/

MicroMDM has no built-in support for VPP at this time. There's a few PRs and issues open for that feature (#563, #516 for example).
