### ISSUE TITLE
Installed application has broken code signature after MDM installation

### ISSUE THREAD

**Issue by keehun** [micromdm/micromdm#826]
### What version of `micromdm` are you using?
1.9.0

### What `micromdm` command did you run?
I am `POST`-ing the following payload 
```
{
    'udid': udid,
    'request_type': "InstallEnterpriseApplication",
    'manifest_url': manifest_url,
}
```
to the following endpoint: `https://mdm-server.com/v1/commands`

### What did you expect to see?
I expected my application to install without any alteration to the application contents in the package.

### What did you see instead?
The resulting application that is installed is DIFFERENT than the application that is installed when I double click on the `.pkg` file in the GUI. Code signing has changed (specifically `_CodeSigning/CodeResources` file). This is a big problem for me as the application contains a system extension with the endpoint security entitlement, and the system extension will not load anymore due to failing code signing/missing entitlement issues.

I can see that specifically that in the `CodeResources` file, hashes for the system extension files are missing.

Does MicroMDM re-sign or alter the package in any way? Why would the resulting application be different whether it was installed via MDM or via double clicking on it in the GUI?

Should I be wrapping my installer package in another package?

**Comment by jessepeterson** [comment]
How are you serving your package?

MicroMDM can sign your package for your as you upload it if you want using the `mdmctl apply app` command's settings. But if you want to serve the package as-is (or host it where you want) you can do that, too. If you've not signed it during upload then MicroMDM doesn't modify the app in any way.

How are you verifying that the code signature files have changed? MicroMDM doesn't actually have insight into the app that is fetched (it's just a URL provided to the device) unless you're having MicroMDM _host_ the package as well using the `-filerepo` switch (which is just a vanilla HTTP file server — again MicroMDM doesn't modify the files there).

**Comment by keehun** [comment]
I am using `-filerepo` switch for the MDM server to host the package. Let me make sure I didn't sign it although I do recall running an `mdmctl apply app` command. Also, I am realizing based on what you're saying that I don't have the host the pkg with the MDM server. Thanks for the help so far and let me come back after reviewing this.

**Comment by keehun** [comment]
So upon reviewing my terminal logs, I ran `mdmctl apply app -pkg installer.pkg > installer.manifest.plist` to generate the manifest for me. I don't believe that actually uploaded anything because I then had to copy `installer.pkg` into the `filerepo` location.

The hashes in the manifest match exactly what I would expect from a fresh copy of `installer.pkg` that isn't from the server. I don't think the server is modifying anything? When I download the pkg directly from the MDM server, the pkg file is unmodified.

Can something change when the installer package is downloaded by macOS's MDM processes?

**Comment by jessepeterson** [comment]
Just checking on this - were you able to get to the bottom of this?

**Comment by keehun** [comment]
Apple is looking into it, I think. I have a feedback open on this.

**Comment by jessepeterson** [comment]
Roger that. I'll close this issue since I don't believe this is related to MicroMDM. Please re-open if you have reason to think otherwise. Thanks!
