### ISSUE TITLE
DEP profile not assigning to newly added devices.

### ISSUE THREAD

**Issue by neilrooney** [micromdm/micromdm#829]
### What version of `micromdm` are you using?

version v1.9.0

### What `micromdm` command did you run?

1. `mdmctl get dep-tokens -export-public-key DEPPublicKey.pem`
2. `mdmctl apply dep-profiles -f dep-files/dep.json -filter='*'`
3. `mdmctl get dep-devices -serials xxxxxxxxx`
4. `mdmctl apply dep-tokens -import /pathc/to/token`

**Content of the dep.json file**: 

> {
>   "profile_name": "Mobile Device Management for XXXXX",
>   "url": "https://xxx.xxx.xxx/mdm/enroll",
>   "support_email_address": "xxx@xxx.xxx",
>   "allow_pairing": true,
>   "auto_advance_setup": false,
>   "await_device_configured": true,
>   "is_supervised": true,
>   "is_multi_user": false,
>   "is_mandatory": true,
>   "is_mdm_removable": false,
>   "anchor_certs": [],
>   "supervising_host_certs": [],
>   "skip_setup_items": [
>     "AppleID",
>     "Diagnostics",
>     "Restore",
>     "Siri",
>     "TOS",
>     "ScreenTime"
>   ],
>   "devices": []
> }

### What did you expect to see?

DEP profile assigning to all newly assigned devices. Devices enrolling via DEP to MicroMDM instance. 

### What did you see instead?

- Created a new MDM server in Apple Business Manager.
- Retrieved DEPPublicKey.pem from MicroMDM server. `mdmctl get dep-tokens -export-public-key DEPPublicKey.pem`
- Uploaded to Apple Business Manager. 
- Installed token from Apple Business Manager in MicroMDM. `mdmctl apply dep-tokens -import` /path/to/token`
- Uploaded the dep.json configuration file (see content above) to MicroMDM. `mdmctl apply dep-profiles -f dep-files/dep.json -filter='*'`
- Changed the MDM server for 5 devices from Jamf Pro to the new MicroMDM server in Apple Business Manager. 
- Forced a sync using: `curl $CURL_OPTS -v -u "micromdm:$API_TOKEN" -X POST "$SERVER_URL/v1/dep/syncnow`
- Checked if the devices had the dep.json configuration applied: `mdmctl get dep-devices -serials xxxxxxxxx`
- Result: ProfileStatus / Empty
- Checked if enrolment with sudo profiles -N was possible. 
- Result: _Error:  Renewing DEP enrolment failed. The device no longer has a Device Enrolment Configuration Profile assigned. (MDMClientError 103)_
- Moved devices back to Jamf Pro in Apple Business Manager. 
- Deleted devices from MicroMDM, ensuring `mdmctl get devices` and `mdmctl get dep-devices -serials xxxxx` was empty. 
- Moved devices back to MicroMDM in Apple Business Manager. 
- Forced a sync using: `curl $CURL_OPTS -v -u "micromdm:$API_TOKEN" -X POST "$SERVER_URL/$endpoint"`
- Result: ProfileStatus / Empty

Logs showing MicroMDM is getting the call from Apple, but marking it as device known. 

> level=debug msg="updating devices from DEP" device_count=5
> level=debug msg="updating devices from dep sync" op_type=modified serial=XXXXXXXXX previously_known=true
> level=debug msg="updating devices from dep sync" op_type=modified serial=XXXXXXXXX previously_known=true
> ....

**Comment by neilrooney** [comment]
> We solved the auto-assignment issue. We found that when we moved devices from our existing jamf server to MicroMDM in Apple business manager, DEP sync would always return "op_type" : "modified" for those devices. No matter how many times we tried re-assigning between them and running force syncs. However, If we set up another "dummy" MDM server in ABM, moved the devices from jamf to there, and then to MicroMDM we get the "added" value and auto-assigner is working.

@stilljake

> We spent the weekend just doing a ton of trial and error. Switching the device from one MDM to another didn't allow for the response we needed. In the end tricking ABM into thinking something was different triggered the auto-assigner.
> Un-assigning and reassigning, this worked also.

@neilrooney

**Comment by machinas-achim** [comment]
Hello! Despite the topic being marked as closed, I think there is some smoke and hence maybe a (little) fire.

We detected a similar situation where MacBooks added by Apple Configurator on iOS show up on ABM correctly as expected.

However, even after assigning to the MicroMDM instance, the dialog "Device Enrollment, ACME can automatically configure your Mac." shows an error that it cannot obtain the initial certificate/profile. 

Only repeatedly un-assigning, syncing (SYNCNOW), then re-assigning and SYNCNOW again will eventually bring success as you can see from the logs below (I promise to capture better logs during the next enrolments, these are already a couple of days old).

So the process itself works, but it seems that sometimes it gets "stuck" and only removing and re-adding into MicroMDM instance with several SYNCNOW leads to the desired behaviour.

Perhaps this sheds some light on the initial issue?

```
# Need to unassign from MicroMDM and then call syncnow
Jun 21 15:32:47 micromdm: transport=http method=POST status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent=curl/7.79.1 path=/v1/dep/syncnow
Jun 21 15:32:47 micromdm: level=info component=depsync msg="explicit DEP sync requested"
Jun 21 15:32:48 micromdm: level=info component=depsync msg="DEP sync" phase=sync cursor=XXXXX fetched=2022-06-21T13:32:11Z devices=1 more=false
Jun 21 15:32:48 micromdm: level=debug msg="updating devices from DEP" device_count=1
Jun 21 15:32:48 micromdm: level=debug msg="updating devices from dep sync" op_type=deleted serial=XXXXXXXXXXXX previously_known=true

# Call "Syncnow" it again, just to be sure
Jun 21 15:34:26 micromdm: transport=http method=POST status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent=curl/7.79.1 path=/v1/dep/syncnow
Jun 21 15:34:26 micromdm: level=info component=depsync msg="explicit DEP sync requested"
Jun 21 15:34:27 micromdm: level=info component=depsync msg="DEP sync" phase=sync cursor=XXXXX fetched=2022-06-21T13:32:11Z devices=1 more=false
Jun 21 15:34:27 micromdm: level=debug msg="updating devices from DEP" device_count=1
Jun 21 15:34:27 micromdm: level=debug msg="updating devices from dep sync" op_type=deleted serial=XXXXXXXXXXXX previously_known=true

# Then reassign to MicroMDM and then call syncnow
Jun 21 15:35:21 micromdm: transport=http method=POST status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent=curl/7.79.1 path=/v1/dep/syncnow
Jun 21 15:35:21 micromdm: level=info component=depsync msg="explicit DEP sync requested"
Jun 21 15:35:21 micromdm: level=info component=depsync msg="DEP sync" phase=sync cursor=XXXXX fetched=2022-06-21T13:34:55Z devices=2 more=false
Jun 21 15:35:21 micromdm: level=debug msg="updating devices from DEP" device_count=2
Jun 21 15:35:21 micromdm: level=debug msg="updating devices from dep sync" op_type=modified serial=XXXXXXXXXXXX previously_known=true
Jun 21 15:35:21 micromdm: level=debug msg="updating devices from dep sync" op_type=modified serial=XXXXXXXXXXXX previously_known=true

# Didn't work ("cannot obtain the initial certificate/profile"), so unassign from MicroMDM and then call syncnow again
Jun 21 15:35:38 micromdm: transport=http method=POST status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent=curl/7.79.1 path=/v1/dep/syncnow
Jun 21 15:35:38 micromdm: level=info component=depsync msg="explicit DEP sync requested"
Jun 21 15:35:38 micromdm: level=info component=depsync msg="DEP sync" phase=sync cursor=XXXXX fetched=2022-06-21T13:35:31Z devices=1 more=false
Jun 21 15:35:38 micromdm: level=debug msg="updating devices from DEP" device_count=1
Jun 21 15:35:38 micromdm: level=debug msg="updating devices from dep sync" op_type=deleted serial=XXXXXXXXXXXX previously_known=true
Jun 21 15:35:43 micromdm: transport=http method=POST status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent=curl/7.79.1 path=/v1/dep/syncnow
Jun 21 15:35:43 micromdm: level=info component=depsync msg="explicit DEP sync requested"
Jun 21 15:35:43 micromdm: level=info component=depsync msg="DEP sync" phase=sync cursor=XXXXX fetched=2022-06-21T13:35:31Z devices=1 more=false
Jun 21 15:35:43 micromdm: level=debug msg="updating devices from DEP" device_count=1
Jun 21 15:35:43 micromdm: level=debug msg="updating devices from dep sync" op_type=deleted serial=XXXXXXXXXXXX previously_known=true

# Then reassign to MicroMDM and then call syncnow
Jun 21 15:35:58 micromdm: transport=http method=POST status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent=curl/7.79.1 path=/v1/dep/syncnow
Jun 21 15:35:58 micromdm: level=info component=depsync msg="explicit DEP sync requested"
Jun 21 15:35:59 micromdm: level=info component=depsync msg="DEP sync" phase=sync cursor=XXXXX fetched=2022-06-21T13:35:31Z devices=2 more=false
Jun 21 15:35:59 micromdm: level=debug msg="updating devices from DEP" device_count=2
Jun 21 15:35:59 micromdm: level=info component=depsync msg="DEP auto-assigned" profile=OURPROFIÑE success=1 not_accessible=0 failed=0
Jun 21 15:36:07 micromdm: transport=http method=POST status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent=curl/7.79.1 path=/v1/dep/syncnow
Jun 21 15:36:07 micromdm: level=info component=depsync msg="explicit DEP sync requested"
Jun 21 15:36:07 micromdm: level=info component=depsync msg="DEP sync" phase=sync cursor=XXXXX fetched=2022-06-21T13:35:59Z devices=2 more=false
Jun 21 15:36:07 micromdm: level=debug msg="updating devices from DEP" device_count=2
Jun 21 15:36:07 micromdm: level=debug msg="updating devices from dep sync" op_type=modified serial=XXXXXXXXXXXX previously_known=true
Jun 21 15:36:07 micromdm: level=debug msg="updating devices from dep sync" op_type=modified serial=XXXXXXXXXXXX previously_known=true
Jun 21 15:36:09 micromdm: transport=http method=POST status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent=curl/7.79.1 path=/v1/dep/syncnow
Jun 21 15:36:09 micromdm: level=info component=depsync msg="explicit DEP sync requested"
Jun 21 15:36:09 micromdm: level=info component=depsync msg="DEP sync" phase=sync cursor=XXXXX fetched=2022-06-21T13:35:59Z devices=1 more=false
Jun 21 15:36:09 micromdm: level=debug msg="updating devices from DEP" device_count=1
Jun 21 15:36:09 micromdm: level=debug msg="updating devices from dep sync" op_type=modified serial=XXXXXXXXXXXX previously_known=true
Jun 21 15:36:14 micromdm: transport=http method=POST status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent=curl/7.79.1 path=/v1/dep/syncnow
Jun 21 15:36:14 micromdm: level=info component=depsync msg="explicit DEP sync requested"
Jun 21 15:36:14 micromdm: level=info component=depsync msg="DEP sync" phase=sync cursor=XXXXX fetched=2022-06-21T13:35:59Z devices=1 more=false
Jun 21 15:36:14 micromdm: level=debug msg="updating devices from DEP" device_count=1
Jun 21 15:36:14 micromdm: level=debug msg="updating devices from dep sync" op_type=modified serial=XXXXXXXXXXXX previously_known=true

# AND NOW it finally works and the MacBook gets past the "Device Enrollment, ACME can automatically configure your Mac." because now it finallyt receives the enrolment profile
Jun 21 15:39:06 micromdm: got DEP enrollment request from XXXXXXXXXXXX
Jun 21 15:39:06 micromdm: transport=http method=POST status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent=CloudConfiguration-OSX/1.0 path=/mdm/enroll
Jun 21 15:39:07 micromdm: method=GetCACaps err=null took=942ns
Jun 21 15:39:07 micromdm: component=scep op=GetCACaps error=null took=39.995µs
Jun 21 15:39:07 micromdm: component=scep method=GET status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent="CertificateService/1 CFNetwork/1333.0.4 Darwin/21.5.0" path="/scep?operation=GetCACaps&message="
Jun 21 15:39:07 micromdm: transport=http method=GET status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent="CertificateService/1 CFNetwork/1333.0.4 Darwin/21.5.0" path="/scep?operation=GetCACaps&message="
Jun 21 15:39:11 micromdm: method=PKIOperation err=null took=9.318845ms
Jun 21 15:39:11 micromdm: component=scep op=PKIOperation error=null took=9.35907ms
Jun 21 15:39:11 micromdm: component=scep method=POST status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent="CertificateService/1 CFNetwork/1333.0.4 Darwin/21.5.0" path="/scep?operation=PKIOperation"
Jun 21 15:39:11 micromdm: transport=http method=POST status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent="CertificateService/1 CFNetwork/1333.0.4 Darwin/21.5.0" path="/scep?operation=PKIOperation"
Jun 21 15:39:12 micromdm: transport=http method=PUT status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent="MDM-OSX/1.0 mdmclient/1550" path=/mdm/checkin
Jun 21 15:39:12 micromdm: level=debug msg="enrolling new device" serial=XXXXXXXXXXXX
Jun 21 15:39:12 micromdm: transport=http method=PUT status=200 proto=HTTP/1.0 host=127.0.0.1 user_agent="MDM-OSX/1.0 mdmclient/1550" path=/mdm/checkin
Jun 21 15:39:12 micromdm: level=debug msg="applying blueprint" device_udid=xxxxx blueprint_name=OurBlueprint


```

**Comment by machinas-achim** [comment]
Just as a follow-up, it is indeed the same devices with the same serial on both lines (same as above)

```
Jun 21 15:36:07 micromdm: level=debug msg="updating devices from DEP" device_count=2
Jun 21 15:36:07 micromdm: level=debug msg="updating devices from dep sync" op_type=modified serial=SAMESERIALINBOTHLINES previously_known=true
Jun 21 15:36:07 micromdm: level=debug msg="updating devices from dep sync" op_type=modified serial=SAMESERIALINBOTHLINES previously_known=true
```

**Comment by jessepeterson** [comment]
FYI I added a note about the oddities of moving devices between MDM servers here: https://github.com/micromdm/micromdm/wiki/DEP-auto-assignment#reassignment-oddities

**Comment by machinas-achim** [comment]
As a confirmation in case you add devices with iOS Apple Configurator:

1. After device becomes visible in ABN, you need to "Unassign from current [i.e.  Apple Configurator] MDM"
2. Wait for completion, then "Assign to following MDM: MicroMDM"
3. Force DEP sync via "/v1/dep/syncnow" which in turn will result in successul "op_type=added" and "component=depsync" msg="DEP auto-assigned"
