### ISSUE TITLE
Update MicroMDM on Docker Hub

### ISSUE THREAD

**Issue by ben221199** [micromdm/micromdm#835]
Hello there, this project seems very nice.
However, on Docker Hub (https://hub.docker.com/r/micromdm/micromdm) it seems updated 5 years ago.
Is there something possible to get an updated version there, so that I don't have to build it myself locally?

**Comment by jessepeterson** [comment]
Hello! We've switched from Dockerhub to GHCR: ghcr.io/micromdm/micromdm

Thanks!
