### ISSUE TITLE
iOS: mdm profile installation failed.

### ISSUE THREAD

**Issue by hiepnh0** [micromdm/micromdm#836]
### What version of `micromdm` are you using?
micromdm version v1.9.0-11-g3d3a51b-dirty
### What `micromdm` command did you run?
Install mdm profile on iOS 15.5
### What did you expect to see?
mdm profile installed successfully.
### What did you see instead?
iOS: Profile installation failed.
macOS: mdm profile installed successfully.
![install_mdm_profile_failed](https://user-images.githubusercontent.com/63147410/178232258-8194bde7-fbed-44e7-b8a4-725216afe828.PNG)

**Comment by korylprince** [comment]
That message indicates the the iPad does not trust the certificate that MicroMDM is presenting is valid for "testpod-nuc7i3bnh.local". It appears you're using a self-signed certificate, so [this wiki page](https://github.com/micromdm/micromdm/wiki/Using-MicroMDM-with-self-signed-certificates) should be helpful. The last section is especially relevant to the issue you're having.

If you need further help, join #micromdm on the [MacAdmins Slack](https://www.macadmins.org/).

**Comment by hiepnh0** [comment]
`mdmctl apply dep-profiles -f dep-profile.json`

output: 
`define dep profile: define profile: unexpected dep response. status=500 DEP API Error: Internal Server Error`
How can i fix this issue, thanks.
