### ISSUE TITLE
Need more device information

### ISSUE THREAD

**Issue by Alanko5** [micromdm/micromdm#837]
### What version of `micromdm` are you using?
MicroMDM 1.9

### What `micromdm` command did you run?
DeviceInformation

### What did you expect to see?
More information of deviace.
iOS/iPadOS/tvOS/macOS version, device model etc..

### What did you see instead?
```
{
    "payload": {
        "command_uuid": "xxxxxxxxxxx",
        "command": {
            "request_type": "DeviceInformation"
        }
    }
}
```

**Comment by korylprince** [comment]
DeviceInformation (like most MDM commands) is an asynchronous command. The payload you got was MicroMDM's acceptance of the command. To see how the device replies, you need to set up [MicroMDM's Webhook](https://github.com/micromdm/micromdm/wiki/Webhooks).
