### ISSUE TITLE
Download enrollment profile timeout

### ISSUE THREAD

**Issue by milkiweed** [micromdm/micromdm#840]
I`m trying to follow this readme: https://github.com/micromdm/micromdm/blob/main/docs/user-guide/enrolling-devices.md to download the enrollment profile, but got server timeout error instead:
```
curl -o enroll.mobileconfig https://mdm.acme.co/mdm/enroll
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to mdm.acme.co port 443 after 75206 ms: Operation timed out
```

### What did you expect to see?
Download enrollment profile

### What did you see instead?
Server timeout error

**Comment by jessepeterson** [comment]
This sounds like some sort of proxy problem. Are you able to talk to your MicroMDM instance using `mdmctl` or at any other URL?

**Comment by jessepeterson** [comment]
This issue is being closed because we asked follow-up questions and didn't receive a reply. If this is still an issue for you you may re-open it or even better join us in the #micromdm channel on the [MacAdmins Slack](https://www.macadmins.org/).
