### ISSUE TITLE
The device is unmanaged after RemoveApplication

### ISSUE THREAD

**Issue by weiyong** [micromdm/micromdm#841]
### What `micromdm` command did you run?
POST /v1/commands
with JSON {"udid":"device-udid","request_type":"RemoveApplication","identifier":"device-identifier"}
### What did you expect to see?
Success message and uninstall application in device
### What did you see instead?
Success messages and devices are not managed
{"CommandUUID":{"content":"xxxxx-xxxx"},"ErrorChain":{"array":[{"ErrorCode":{"boolean":false,"integer":true,"real":false},"ErrorDomain":{"content":"MDMErrorDomain"},"LocalizedDescription":{"content":"App“device-identifier”不受管理。"},"USEnglishDescription":{"content":"The app “device-identifier” is not managed."}}]},"Status":{"content":"Error"},"UDID":{"content":"device-udid"}}

**Comment by jessepeterson** [comment]
If you're able to see the device response then the device is still enrolled. This sounds like you're trying to remove an app that was not installed by MDM. Sounds a bit like an iOS app maybe? I'm not sure the semantics here but it seems like the _MDM protocol_ (and thus MicroMDM) is working fine. I'd suggesting joining the [Slack](https://www.macadmins.org/) and asking in either #micromdm or #mdmdev channels.

**Comment by jessepeterson** [comment]
This issue is being closed because we asked follow-up questions and didn't receive a reply. If this is still an issue for you you may re-open it or even better join us in the #micromdm channel on the [MacAdmins Slack](https://www.macadmins.org/).
