### ISSUE TITLE
How to install ABM apps with micromdm?

### ISSUE THREAD

**Issue by Gaoxichao** [micromdm/micromdm#845]
How to install ABM apps with micromdm?

**Comment by jessepeterson** [comment]
VPP (now Apps & Books) is not directly supported by MicroMDM. If you can communicate with the [Apps & Books APIs](https://developer.apple.com/documentation/devicemanagement/app_and_book_management) using your own code then you can probably use the `InstallApplication` MDM commands to get them installed.

See also #544 & #563 for the (very old) PRs considering adding this support. Thanks!

**Comment by Visput** [comment]
Currently MicroMDM sends such command for App installation to Apple Server:
```
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
  <dict>
    <key>Command</key>
    <dict>
      <key>iTunesStoreID</key>
      <string>1096834193</string>
      <key>RequestType</key>
      <string>InstallApplication</string>
    </dict>
    <key>CommandUUID</key>
    <string>71f86323-f193-4b5e-aa36-92b7c922d9c3</string>
  </dict>
</plist>
```

Based on Apple documentation for Books and Apps, it should look like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
    <key>Command</key>
    <dict>
        <key>ManagementFlags</key>
        <integer>0</integer>
        <key>Options</key>
        <dict>
            <key>PurchaseMethod</key>
            <integer>1</integer>
        </dict>
        <key>RequestType</key>
        <string>InstallApplication</string>
        <key>iTunesStoreID</key>
        <integer>1096834193</integer>
    </dict>
    <key>CommandUUID</key>
    <string>71f86323-f193-4b5e-aa36-92b7c922d9c3</string>
</dict>
</plist>
```

Is that all is needed to make it work? If yes, is there an easy way to do that via MicroMDM? Or is there more complexity with assigning licenses to devices? (Our Apple Business Manager account is connected to MicroMDM server and has licenses for the apps I need to install silently with no Apple ID).

**Comment by petarov** [comment]
> Or is there more complexity with assigning licenses to devices?

Yes, you need to assign an app license to the device's serial number before the installation takes place. But you'll need to find a way to do that as @jessepeterson already mentioned above.

For example, the [v1 API call](https://developer.apple.com/documentation/devicemanagement/managevpplicensesbyadamidrequest?changes=latest_major&language=objc) with `adamIdStr` for the iTunesStoreID and `associateSerialNumbers` with the device's serial number.

You should generally be able to accomplish this with `curl`. I need to prep a gist about this.

**Comment by Visput** [comment]
@petarov thanks. If you have that code handy, please share.

**Comment by petarov** [comment]
@Visput You can assign a license by executing the following:

```bash
curl -X POST -H "Content-Type: application/json" \
    -d '{ "sToken": "<your ABM server token>", "adamIdStr": "<iTunesStoreID>", "associateSerialNumbers": ["<device serial number 1>, "<device serial numbe 2>"]}' \
    "https://vpp.itunes.apple.com/mdm/manageVPPLicensesByAdamIdSrv"  | jq
```

So, first you need to download your token from ABM > Preferences and then adjust the command above with the token, app id and one or more devices serial numbers you need the app license assigned to.

You can fetch the state of the assignments for a given app by using something like:

```bash
curl -X POST -H "Content-Type: application/json" \
    -d '{ "sToken": "<your ABM server token>", "adamIdStr": "<iTunesStoreID>" }' \
    "https://vpp.itunes.apple.com/mdm/getAssignments" | jq
```

Note that I've used [jq](https://github.com/stedolan/jq) for better JSON formatting on the command line.
I hope this helps!
