### ISSUE TITLE
Webhooks Error 404

### ISSUE THREAD

**Issue by belerovon** [micromdm/micromdm#847]
Hi Community
hope you can help me.

I set up my micromdm and can enroll my devices correctly.

Now I try to push a profile with the API (from use the API from same Server with IP 192.168.255.110)
./tools/api/commands/install_profile 00008110-00011XXXXX1E   profiles/test_signed.mobileconfig 

And I see some output from script:
{
  "payload": {
    "command_uuid": "544d5532-166a-4f77-ac45-460ddab3482c",
    "command": {
      "request_type": "InstallProfile",

But nothing happened.

In the logs I can see:
transport=http method=POST status=201 proto=HTTP/2.0 host=192.168.255.110 user_agent=curl/7.74.0 path=/v1/commands
level=info msg="queued event for device" device_udid=00008110-00011034118B801E command_uuid=544d5532-166a-4f77-ac45-460ddab3482c request_type=InstallProfile
transport=http method=POST status=404 proto=HTTP/2.0 host=192.168.255.110 user_agent=Go-http-client/2.0 path=/webhook
level=info msg="post webhook event" err="received unexpected HTTP status 404 404 Not Found"
transport=http method=PUT status=200 proto=HTTP/2.0 host=192.168.101.64 user_agent=MDM/1.0 path=/mdm/connect
transport=http method=POST status=404 proto=HTTP/2.0 host=192.168.255.110 user_agent=Go-http-client/2.0 path=/webhook
level=info msg="post webhook event" err="received unexpected HTTP status 404 404 Not Found"
transport=http method=PUT status=200 proto=HTTP/2.0 host=192.168.101.64 user_agent=MDM/1.0 path=/mdm/connect

So as I understand it is an error with the web hook URL (see error 404).

But it as I understand, everything is correct defined:
/usr/bin/micromdm serve \
  -server-url=https://mdm.XYZ123.link \
    -filerepo /home/mdm/pkg \
    -tls-cert /etc/ssl/mdm.crt \
    -tls-key  /etc/ssl/mdm.key \
    -command-webhook-url https://mdm.321ZYX.de/webhook \
    -api-key TOKEN \
    -http-proxy-headers true

cat env  
export API_TOKEN=TOKEN
export SERVER_URL=https://321ZYX

in hosts: cat /etc/hosts
192.168.255.110    mdm.XYZ123.link  mdm.321ZYX.de
127.0.0.1	               localhost 

Any hint or idea?

**Comment by tomaswallentinus** [comment]
Can you curl "https://mdm.321zyx.de/webhook" from the micromdm host? Is the output 404 there aswell? Then you need to solve the dns resolution.

**Comment by belerovon** [comment]
Here the output::

curl https://mdm.321ZYX.de/webhooks
404 page not found

curl --insecure https://127.0.0.1/webhooks
404 page not found

**Comment by belerovon** [comment]
got it - my failure: misunderstood but found a solution with MDMDirector
