### ISSUE TITLE
New Enrolement Profile doesn't work?

### ISSUE THREAD

**Issue by JTzLinux** [micromdm/micromdm#849]
### What version of `micromdm` are you using?
mdmctl version v1.9.0
### What `micromdm` command did you run?
mdmctl apply profiles -f /root/enroll.mobileconfig
### What did you expect to see?
Diffrent enrolement profile
### What did you see instead?
No changes

I tried to use a diffrent Enrolement profile what I created with the help of a software called: "iMazing Profile Editor" but it doesn't change the enrolement

(This is the output:
`root@debian:~# mdmctl apply profiles -f /root/enroll.mobileconfig    
applied profile id 10.40.41.101 from /root/enroll.mobileconfig    
root@debian:~#`

**Comment by jessepeterson** [comment]
The profile has to maintain the same profile identifier to be counted. What happens when you list it with `mdmctl get profiles`?

**Comment by JTzLinux** [comment]
> The profile has to maintain the same profile identifier to be counted. What happens when you list it with `mdmctl get profiles`?


Helloe @jessepeterson,


Sorrry for the late reply I was in the hospital, anyway! after I typed "mdmctl get profiles" I received the following error: 
`root@debian:~# mdmctl get profiles
Post "https://mdm.sim.local/v1/profiles": dial tcp: i/o timeout
`

(Before that I used `root@debian:~# mdmctl apply profiles -f /root/enroll.mobileconfig
applied profile id 10.40.41.101 from /root/enroll.mobileconfig)`

**Comment by jessepeterson** [comment]
Hello @JTzLinux. Your enrollment profile has to keep the same profile identifier (that is, `com.github.micromdm.micromdm.enroll`). Please check out the documentation here: https://github.com/micromdm/micromdm/blob/main/docs/user-guide/enrolling-devices.md#replacing-the-default-enrollment-profile

Please join us in the `#micromdm` channel on the [MacAdmins Slack](https://www.macadmins.org) to discuss issues like this. Thanks!
