### ISSUE TITLE
micromdm : command not found

### ISSUE THREAD

**Issue by HansSamu** [micromdm/micromdm#853]
### What version of `micromdm` are you using?
Version 1.10
### What `micromdm` command did you run?
sudo MicroMDM serve -h
### What did you expect to see?
informations about the command
### What did you see instead?
"micromdm : command not found"

Hello, 
I'm really lost here to be honest, I just downloaded the "build" file available on the download link, I then launched the micromdm file in the Darwin folder (I'm working on MacOS), the file is available in the $PATH, but for some reason that I don't know, when I open a second terminal window, when I try to use the "micromdm serve", the only thing I get in return is "micromdm : command not found".
It's possible that I didn't do something important before actually trying to use it, but I have read and followed the guide on here to the letter so...

May someone help me, thank you I advance to anyone that could help.

**Comment by tomaswallentinus** [comment]
Have you made the files executable? Or are they by default?
Can you run it from the darwin-folder "cd whatever folder", "./micromdm serve -h"?

**Comment by HansSamu** [comment]
Files are still by default, I actually tested ./micromdm serve -h but I wasn't in the folder, when I'm in the folder, it's actually working, guess I made a mistake in my $PATH

Ty anyway, now I have another error, but I'll see if it didn't happened already before burdening you.

Have a good day and ty again
