### ISSUE TITLE
unauthorized enrollment client

### ISSUE THREAD

**Issue by meta-github** [micromdm/micromdm#854]
### What version of `micromdm` are you using?
1.10.0
### What `micromdm` command did you run?
No command, DEP client tries to enroll.
### What did you expect to see?
Enrollment should succeed.
### What did you see instead?
On the server:
```
transport=http err="unauthorized enrollment client: not signed by Apple Device CA"
transport=http method=POST status=500 proto=HTTP/1.1 host=16.181.2.145 user_agent=CloudConfiguration-OSX/1.0 path=/mdm/enroll
```
On the client:
```
2023-01-23 09:47:14.548520+0100 0x3e16     Default     0x0                  336    0    mdmclient: (ConfigurationProfiles) [com.apple.ManagedClient:ManagedClient] CloudConfig: Get activation profile returning error after 0.25 secs
2023-01-23 09:47:14.548640+0100 0x3e16     Default     0x0                  336    0    mdmclient: (ConfigurationProfiles) [com.apple.ManagedClient:ManagedClient] CloudConfig: Error returning activation profile.   Error = 500; Datasize = 0
```
Then, no DEP enrollment.

I have no idea what the server is checking and how I can turn it off or make it successful.

Client and server are running macOS 13.1.

Switching back to my older micromdm binary (1.9.0, compiled about a year ago; eventually patched regarding ScheduleOSUpdate) has fixed the issue.

**Comment by meta-github** [comment]
Maybe, the problem is caused by a more recent go library? The documentation of [CheckSignatureFrom](https://pkg.go.dev/crypto/x509#Certificate.CheckSignatureFrom) mentions, that SHA1WithRSA and ECDSAWithSHA1 signatures are not supported. Could it just be that? We are currently using v1.19.3 of the go compiler.

**Comment by korylprince** [comment]
I think you're correct. An easy way to test for this and temporarily bypass the issue is to run with `GODEBUG=x509sha1=1` set, or compile with go 1.18. Longer term, we'll need to find a different way to verify sha1 signatures, as that flag is planned to be removed.

**Comment by jessepeterson** [comment]
Yeah, so I mocked this up with this test:

```go
package crypto

import (
	"testing"
)

func TestVerifyFromAppleDeviceCA(t *testing.T) {
	cert, _ := ReadPEMCertificateFile("testdata/appleca_signed.pem")

	err := VerifyFromAppleDeviceCA(cert)
	if err != nil {
		t.Error("received error verifying Apple Device CA", err)
	}
}
```

And the result is:

```
--- FAIL: TestVerifyFromAppleDeviceCA (0.00s)
    apple_test.go:12: received error verifying Apple Device CA x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)
FAIL
coverage: 31.5% of statements
FAIL	github.com/micromdm/micromdm/pkg/crypto	0.185s
FAIL
```

I'm not sure it's worth adding as a test because it will always fail on Go >=1.8 I think. The test does pass if I `export GODEBUG=x509sha1=1`.

Yes, as @korylprince said we'll need to explore somehow verifying this signature somehow else.

**Comment by jessepeterson** [comment]
See also #989 for a similarly-erroring issue on newer devices.
