### ISSUE TITLE
Redundant "Opts" field in the request body of the device delete endpoint

### ISSUE THREAD

**Issue by desobolevsky** [micromdm/micromdm#883]
### What version of `micromdm` are you using?
v1.10.1-18-g1f01f70

### What `micromdm` command did you run?
Made a DELETE request to `/v1/devices` endpoint with the following body:
```json
{
    "serials": [
      "<SERIAL_OF_ENROLLED_DEVICE>"
    ]
}
```

### What did you expect to see?
The device IS DELETED and NOT PRESENT in the results of POST request to `/v1/devices`.

### What did you see instead?
The device IS NOT deleted and PRESENT in the results of POST request to `/v1/devices`.

However, if I make the DELETE request with the previous body contents wrapped in "Opts" object, like that:
```json
{
   "Opts": {
    "serials": [
      "<SERIAL_OF_ENROLLED_DEVICE>"
    ]
  }
}
```
I get the expected result (the device is deleted and not present in devices list).

### Description
It happens [here](https://github.com/micromdm/micromdm/blob/v1.10.1/platform/device/remove_devices.go#L37) in the code:
```go
type removeDevicesRequest struct{ Opts RemoveDevicesOptions }

func decodeRemoveDevicesRequest(ctx context.Context, r *http.Request) (interface{}, error) {
	var req removeDevicesRequest
	err := httputil.DecodeJSONRequest(r, &req)
	return req, err
}
```

This function decodes json request with the `removeDevicesRequest` structure, which contains original body within the `Opts`field and that's why the request works if we wrap the original body in "Opts" field.

I believe this code should be corrected to something like this, similiar to how it's done everywhere in the decodeRequest functions in other modules/packages:
```go
func decodeRemoveDevicesRequest(ctx context.Context, r *http.Request) (interface{}, error) {
	var opts RemoveDevicesOptions
	err := httputil.DecodeJSONRequest(r, &opts)
	req := removeDevicesRequest {
	     Opts: opts,
	}
	return req, err
}
```

I've also found the same problem in the `/v1/apps` (list apps) endpoint, so I believe it should be corrected as well.

Any ideas about this issue?

If everything is alright, I can make a PR on this matter.

**Comment by desobolevsky** [comment]
I also believe it's the case of the  #717 bug.

**Comment by jessepeterson** [comment]
The device removal code was added in #444. Since this *works* using `mdmctl` (i.e. `mdmctl` submits a request using the working JSON structure with "Opts"):

```json
{"Opts":{"udids":null,"serials":["ZVFYMWQ31M3E"]}}
```

I'm inclined to think this a documentation bug *as implemented*. However the "Opts" does seem a little odd and I'm not sure how that came about. Perhaps options for limiting or targeting devices was planned? Maybe @knightsc could shed some light. :)

I'd be open to changing it to drop the "Opts" if you want to submit a PR if I'm not missing anything here.

**Comment by korylprince** [comment]
(Copied from my comment on MacAdmins Slack)

* The Opts wrapper looks weird to me, but it's used in a few other endpoints (get blueprints, get devices, get users, get profiles, etc)
  * The request structure doesn't appear to be documented anywhere other than the code
* Perhaps for this particular (DELETE) endpoint, it would be useful to return an error (400 bad request?) if no uuids or serials are included in the request (e.g. they used the wrong structure) That would at least indicate that their request isn't valid

**Comment by desobolevsky** [comment]
@jessepeterson @korylprince
Thank you for your response. I apologize for the delayed reply from my end.
"Opts" wrapper seems perfectly suitable for me when used in the code. However, for the `DELETE /v1/devices` and `POST /v1/apps` endpoints, it is necessary to explicitly include the "Opts" wrapper in the JSON request sent to these endpoints, as shown below
```json
{
   "Opts": {
    "serials": [
      "<SERIAL_OF_ENROLLED_DEVICE>"
    ]
  }
}
```
While all the other endpoints, including the ones you have mentioned (get blueprints, get devices, get users, get profiles), function perfectly without "Opts" wrapper, for instance `POST /v1/devices`:
```json
{
    "page":0,
    "per_page":0
}
```
It appears weird to me that only two out of all the endpoints require the request to be structured in this manner, despite the fact that the same URL with different HTTP method does not require the "Opts" wrapper. I believe it's just a "typo" or "code misspeling" in the decoding functions of these endpoints, which is why I raised the issue.

I hope I made my explanation clear enough :)

I'm using MicroMDM as a third-party integration in some microservice architecture, that's why it's much more convinient to request MicroMDM server directly, without mdmctl. Most of the MicroMDM endpoints have a similar body structure, except for the two endpoints I mentioned earlier.

However, if you believe it is preferable for the project to refrain from modifying these specific endpoints, I am completely fine with that :)

So, what do you think about it?

**Comment by desobolevsky** [comment]
Additionally, I would like to ask about the preferred platform for discussing such issues: GitHub or MacAdmins slack?

**Comment by korylprince** [comment]
@jessepeterson and I discussed this. We definitely don't want to modify the existing endpoints, even though it's a bit strange. We're going to leave everything as is.

It's likely used in existing code in the wild, and we don't want to break API compatibility or older versions of mdmctl.

If anyone else encounters this "issue", hopefully they'll find this issue which documents everything pretty well.

To answer your last question, #micromdm on MacAdmins Slack is probably more active, and is always a good starting place.
