### ISSUE TITLE
How to open the activation lock?

### ISSUE THREAD

**Issue by Gaoxichao** [micromdm/micromdm#884]
I'm trying to understand the flow of some device activation locks, and right now the concept of how MicroMDM is associated with DEP is a bit confusing, how to open the activation lock, preventing users from restoring regulatory devices

**Comment by jessepeterson** [comment]
You may want to see (and join) the discussion in #878. I'm going to close this issue because it's a general question (see the discussion) and not a technical issue with MicroMDM. Thanks!
