### ISSUE TITLE
What is "error retrieving device certificate: CMS verify MDM Signed Message" and how to fix it?

### ISSUE THREAD

**Issue by GregOriol** [micromdm/micromdm#886]
### What version of `micromdm` are you using?
v1.11.0

### What `micromdm` command did you run?
micromdm serve
then trying to enroll a device

### What did you expect to see?
The same device used for my tests did enroll before many times, but after an erase command and a new set up today, enrolling fails with this error

### What did you see instead?
In micromdm's logs, I get exactly this:
```
err="error retrieving device certificate: CMS verify MDM Signed Message: pkcs7: signing time \"2023-05-31T11:51:17Z\" is outside of certificate validity \"2023-05-31T11:51:19Z\" to \"2024-05-30T11:51:19Z\""
transport=http method=PUT status=500 proto=HTTP/1.0 host=127.0.0.1 user_agent=MDM/1.0 path="/mdm/checkin"
```

It looks like there are a few seconds of difference somewhere causing the issue, but I don't understand where and how to fix this.

The iPad is freshly reset up and is set to automatic time.
The server is time synced with ntp.

Could you help?

**Comment by hslatman** [comment]
Hey @GregOriol, a similar issue was recently discussed on the `micromdm` channel in the MacAdmins Slack workspace. One user reported that ensuring the device and the server had its time set correctly to resolve the issue. You mention you've done that, so I suspect a difference between the NTP servers in use. Not sure if it's possible to make it such that both point to the same NTP server?

A PR was also opened: https://github.com/micromdm/micromdm/pull/871 that discussed this, but not all of its changes were merged. Here is a branch that still has the option for a configurable clock skew: https://github.com/korylprince/micromdm/tree/pkcs7-skew.

**Comment by hslatman** [comment]
Great, @GregOriol 😄 

I guess it makes sense to have this option for a (slight) skew available.

**Comment by korylprince** [comment]
I've opened a [new PR](https://github.com/micromdm/micromdm/pull/887) to add this flag. I was never able to replicate this issue, but it's obvious it's happening to multiple people. For now, you can build and test against https://github.com/korylprince/micromdm/tree/pkcs7-skew. I'm going to reopen this issue until that PR is closed.
