### ISSUE TITLE
Update of  enroll.mobilconfig after change of TLS certificate

### ISSUE THREAD

**Issue by z3ky** [micromdm/micromdm#894]
### What version of `micromdm` are you using?
1.11.0

### What `micromdm` command did you run?
Download enroll.mobileconfig from /mdm/enroll after updating TLS certificate and restarting micromdm.

### What did you expect to see?
I expected an updated enroll.mobilconfig with the expiry date of the new certificate.

### What did you see instead?
The old enroll.mobileconfig with expired dates from the old certificate.

**Comment by korylprince** [comment]
The signature of the enrollment profile is not tied to the TLS certificate MicroMDM uses for HTTPS, though I suppose you could have signed the profile with the same cert.

MicroMDM doesn't manage the signature of the enrollment profile; you'll need to update it yourself:

You'll need to download the profile from https://\<your server\>/mdm/enroll

Then strip the existing signature:

`openssl cms -inform der -in <profile from above> -verify -nosigs -noverify -out unsigned.mobileconfig`

Finally, sign with new signature and upload to MicroMDM:

`mdmctl apply profiles -cert ../signing_cert.p12 -sign -f "unsigned.mobileconfig"`

**Comment by Gaoxichao** [comment]
@korylprince However, the previously installed device will prompt that it has not yet been verified. The file after replacing the new signature will only be effective for the newly registered device. What should I do with the previous device?

**Comment by korylprince** [comment]
@Gaoxichao I'm not following. Can you create a new issue with more information about the problem you're facing (i.e. what did you try, what did you see, and what did you expect to see?)
