### ISSUE TITLE
Enroll devices profile

### ISSUE THREAD

**Issue by Gaoxichao** [micromdm/micromdm#896]
How to install the other profiles at the same time when installing the enrollment profile. I wish the enrollment profile included wifi and some limit , no additional commands(eg `install_profile`) are required.

**Comment by jessepeterson** [comment]
Typically the enrollment profile only contains the minimum payloads to enroll the device. Any management settings you want applied to the device (such as a WiFi or restrictions payloads) would usually come in a separate Configuration Profile installed via an `InstallProfile` command (which can use the `./tools/api/commands/install_profile` script). This also allows you to de-couple the installation of management profiles from the enrollment profile — i.e. you can update the WiFi profile without having to re-enroll the device. If you really want to I suppose you could add WiFi and restrictions payloads to the enrollment profile ... but why would you?

You might want to look into [Blueprints](https://github.com/micromdm/micromdm/wiki/Provisioning-Users-with-Blueprints) — which can install profiles when a device enrolls. You can also integrate something like [mdmdirector](https://github.com/mdmdirector/mdmdirector) or [NanoCMD](https://github.com/micromdm/nanocmd).

**Comment by luanyongji** [comment]
> 
Hello, I have encountered a problem here. The enroll.moblieconfig file can be installed normally, and information can also be obtained through get devices, but the file cannot be pushed through install_profile. I would like to ask why this is the case

**Comment by korylprince** [comment]
@luanyongji I believe your question has been answered in #903.

@jessepeterson answered the original question thoroughly, so I'm closing this.
