### ISSUE TITLE
How to support com.apple.applicationaccess

### ISSUE THREAD

**Issue by pallassgj** [micromdm/micromdm#901]
### What version of `micromdm` are you using?

micromdm 1.11

### What `micromdm` command did you run?

The com.apple.applicationaccess payload type is configured via AppleConfigurator2.

### What did you expect to see?

The error "MicroMDM does not allow payload type com.apple.applicationaccess" was reported.

### What did you see instead?

How can the payload type com.apple.applicationaccess be supported？

**Comment by jessepeterson** [comment]
Please try to install the profile using MicroMDM (e.g. using the `./tools/api/commands/install_profile` script). I'm not sure why Apple Configurator doesn't support that payload type. MicroMDM supports any Profile Payload type.

**Comment by jessepeterson** [comment]
Now that I think about it: are you trying to add that Payload to the enrollment profile? I'm not sure why that wouldn't work with Apple Configurator. In any case this doesn't seem to be a problem with MicroMDM.

**Comment by pallassgj** [comment]
Thank you so much. I will try it.
