### ISSUE TITLE
Install_profile enroll.mobileconfig  fail but no error

### ISSUE THREAD

**Issue by luanyongji** [micromdm/micromdm#903]
Hello, I have encountered a problem here. The enroll.moblieconfig file can be installed normally, and information can also be obtained through get devices, but the file cannot be pushed through install_profile. I would like to ask why this is the case

### What version of `micromdm` are you using?
may be 1.9
### What `micromdm` command did you run?
install_profile xxxx ~/enroll.mobileconfig
### What did you expect to see?
The enroll.mobileconfig file will be pushed normally
### What did you see instead?
not

**Comment by luanyongji** [comment]
> MicroMDM 可以将注册配置文件推送到设备。这通常用于使设备更新其设备身份证书。
> 
> 但是，注册配置文件有几个字段必须保持不变，设备才能安装它。如果您尝试更改注册配置文件中的某些字段，这可能就是您遇到问题的原因。
> 
> 您尚未提供任何信息（对 mdmctl 命令的响应、micromdm 日志、webhook 上的设备响应、设备日志），因此很难推测问题的原因。

According to your suggestion, I checked the relevant logs. When the mac client installs enroll.mobileconfig, it can be installed successfully. mircomdm executes mdmctl get devices to view related udid and time information. But executing the /tools/api/commands/install_profile command for that udid after that returns {
  "payload": {
    "command_uuid": "2cb6cd38-9075-428a-b8d8-a2822d8c4a3f",
    "command": {
      "request_type": "InstallProfile",
      "payload": "base64contentXXX"
    }
  }
}
At the same time, I check the background log of micromdm, it shows level=info msg="queued event for device" device_udid=4815DADA-C1B6-59D3-A30C-C7C8EB160819 command_uuid=688e983e-2505-4c81-837f-9f36141eb4ea request_ type=InstallProfile
I'm not sure if it has something to do with the following two logs
1. Post "https://api.push.apple.com/3/device/44747261f75b0f17574f551fab2e851094028b0f2a886e638a90c2d63b43fb3e": remote error: tls: error decrypting message error
2.Post "https://api.push.apple.com/3/device/44747261f75b0f17574f551fab2e851094028b0f2a886e638a90c2d63b43fb3e": net/http: request canceled while waiting for connection (Client.Timeout exceeded ed while awaiting headers)
Thanks again for your reply.

**Comment by korylprince** [comment]
> remote error: tls: error decrypting message error

Yes, this indicates that your APNS certificate is invalid, of there is is something between MicroMDM and Apple's servers that's causing an issue.

Make sure you follow the [user guide](https://github.com/micromdm/micromdm/blob/main/docs/user-guide/quickstart.md#configure-an-apns-certificate) to request and upload an APNS certificate.

**Comment by luanyongji** [comment]
> 

Hello, my situation here is a bit special, and I can't go through the APNS configuration again. Execute the last step directly mdmctl mdmcert upload xx.pem -private-key xx.key -password ... Will there be any problems?

**Comment by luanyongji** [comment]
> > 远程错误：tls：解密消息错误时错误
> 
> 是的，这表明您的 APNS 证书无效，因为 MicroMDM 和 Apple 服务器之间存在问题。
> 
> 请务必按照[用户指南](https://github.com/micromdm/micromdm/blob/main/docs/user-guide/quickstart.md#configure-an-apns-certificate)请求并上传 APNS 证书。

Hello, my situation here is a bit special, and I can't go through the APNS configuration again. Execute the last step directly mdmctl mdmcert upload xx.pem -private-key xx.key -password ... Will there be any problems?

**Comment by luanyongji** [comment]
> > remote error: tls: error decrypting message error
> 
> Yes, this indicates that your APNS certificate is invalid, of there is is something between MicroMDM and Apple's servers that's causing an issue.
> 
> Make sure you follow the [user guide](https://github.com/micromdm/micromdm/blob/main/docs/user-guide/quickstart.md#configure-an-apns-certificate) to request and upload an APNS certificate.

By the way, if I migrate the microMDM server, do I still need to re-upload your push certificate after migrating the files from the old server?
execute mdmctl mdmcert upload \
    -cert mdm-certificates/MDM_\ Acme\,\ Inc._Certificate.pem\
    -private-key mdm-certificates/PushCertificatePrivateKey.key \
    -password=secret

**Comment by korylprince** [comment]
`mdmctl mdmcert upload...` is the correct command to upload the APNS certificate to MicroMDM. It looks like you followed that step correctly, assuming that the certificate is a valid, unexpired APNS certificate from Apple.

Is there something hijacking the connection between your MicroMDM server and Apple (e.g. firewall, content filter, proxy, etc)?

The APNS certificate is stored in the MicroMDM database, so as long as the database get's migrated, the APNS certificate will go with it.

**Comment by luanyongji** [comment]
> `mdmctl mdmcert upload...`是将 APNS 证书上传到 MicroMDM 的正确命令。假设该证书是来自 Apple 的有效且未过期的 APNS 证书，您似乎正确地执行了该步骤。
> 
> 是否有什么东西劫持了您的 MicroMDM 服务器和 Apple 之间的连接（例如防火墙、内容过滤器、代理等）？
> 
> APNS 证书存储在 MicroMDM 数据库中，因此只要数据库迁移，APNS 证书就会随之迁移。

Thank you very much for your above reply. I have solved the problem of migrating the server, but I found a phenomenon that whenever I execute install_profile to push the description file, the file will not be sent immediately, only when the client calls the mdm_authenticate of web_hook The registration interface file will be pushed, why is this?

**Comment by korylprince** [comment]
The MDM process works like this:

1. You send (queue) a command for a device to MicroMDM
2. MicroMDM sends a push notification (APNS) to Apple for the device
3. The device receives the push message from Apple, prompting a check-in
4. The device checks in with MicroMDM, retrieves the command from the queue, and (possibly) issues a response
5. If the webhook is configured, the response is sent to the webhook

Devices also usually check in when rebooted, so they can get commands at that time without APNS working.

As you can see, the process is very asynchronous, and especially step 3 can delay the process. As I mentioned before, the errors you posted indicated your APNS certificate is invalid, or you're having issues communicating with Apple's APNS servers. If APNS is not working, then you're going to have lots of issues.

**Comment by zxyzhouxiaoyun** [comment]
install profile指令不能用吗

**Comment by zxyzhouxiaoyun** [comment]
> > MicroMDM 可以将注册配置文件推送到设备。这通常用于使设备更新其设备身份证书。
> > 但是，注册配置文件有几个字段必须保持不变，设备才能安装它。如果您尝试更改注册配置文件中的某些字段，这可能就是您遇到问题的原因。
> > 您尚未提供任何信息（对 mdmctl 命令的响应、micromdm 日志、webhook 上的设备响应、设备日志），因此很难推测问题的原因。
> 
> According to your suggestion, I checked the relevant logs. When the mac client installs enroll.mobileconfig, it can be installed successfully. mircomdm executes mdmctl get devices to view related udid and time information. But executing the /tools/api/commands/install_profile command for that udid after that returns { "payload": { "command_uuid": "2cb6cd38-9075-428a-b8d8-a2822d8c4a3f", "command": { "request_type": "InstallProfile", "payload": "base64contentXXX" } } } At the same time, I check the background log of micromdm, it shows level=info msg="queued event for device" device_udid=4815DADA-C1B6-59D3-A30C-C7C8EB160819 command_uuid=688e983e-2505-4c81-837f-9f36141eb4ea request_ type=InstallProfile I'm not sure if it has something to do with the following two logs
> 
> 1. Post "https://api.push.apple.com/3/device/44747261f75b0f17574f551fab2e851094028b0f2a886e638a90c2d63b43fb3e": remote error: tls: error decrypting message error
>    2.Post "https://api.push.apple.com/3/device/44747261f75b0f17574f551fab2e851094028b0f2a886e638a90c2d63b43fb3e": net/http: request canceled while waiting for connection (Client.Timeout exceeded ed while awaiting headers)
>    Thanks again for your reply.
下面两条请求日志 怎么查看的啊

**Comment by zxyzhouxiaoyun** [comment]
> > MicroMDM 可以将注册配置文件推送到设备。这通常用于使设备更新其设备身份证书。
> > 但是，注册配置文件有几个字段必须保持不变，设备才能安装它。如果您尝试更改注册配置文件中的某些字段，这可能就是您遇到问题的原因。
> > 您尚未提供任何信息（对 mdmctl 命令的响应、micromdm 日志、webhook 上的设备响应、设备日志），因此很难推测问题的原因。
> 
> According to your suggestion, I checked the relevant logs. When the mac client installs enroll.mobileconfig, it can be installed successfully. mircomdm executes mdmctl get devices to view related udid and time information. But executing the /tools/api/commands/install_profile command for that udid after that returns { "payload": { "command_uuid": "2cb6cd38-9075-428a-b8d8-a2822d8c4a3f", "command": { "request_type": "InstallProfile", "payload": "base64contentXXX" } } } At the same time, I check the background log of micromdm, it shows level=info msg="queued event for device" device_udid=4815DADA-C1B6-59D3-A30C-C7C8EB160819 command_uuid=688e983e-2505-4c81-837f-9f36141eb4ea request_ type=InstallProfile I'm not sure if it has something to do with the following two logs
> 
> 1. Post "https://api.push.apple.com/3/device/44747261f75b0f17574f551fab2e851094028b0f2a886e638a90c2d63b43fb3e": remote error: tls: error decrypting message error
>    2.Post "https://api.push.apple.com/3/device/44747261f75b0f17574f551fab2e851094028b0f2a886e638a90c2d63b43fb3e": net/http: request canceled while waiting for connection (Client.Timeout exceeded ed while awaiting headers)
>    Thanks again for your reply.

下面两个log  在哪可以看到啊

**Comment by korylprince** [comment]
@zxyzhouxiaoyun MicroMDM outputs all of it's logging to stdout. It's going to depend how you to deploy MicroMDM on where you can view the logs.

@luanyongji from everything you've posted, it appears you're having issues with APNS that you need to work out. I'm going to go ahead and close this issue.
