### ISSUE TITLE
How to update the APNs certificate without affecting normal business

### ISSUE THREAD

**Issue by Gaoxichao** [micromdm/micromdm#904]
How to update the APNs certificate without affecting normal business?
There are mainly two situations:
1. The APNs certificate has expired, and the certificate must be renewed
  2. The APNs certificate is damaged, replace the certificate

Will these two situations have an impact on the device? Will the device disconnect? If the certificate is renewed

**Comment by jessepeterson** [comment]
1. Yes, you can replace an APNs push certificate with `mdmcdl` and continue to push to the existing devices. You may need to restart MicroMDM after the replacement.
   * Notably the `Topic` for the certificate can never change for the lifetime of a device's enrollment. You do this by using the same login for https://identity.apple.com and choosing the 'Renew' option.
3. I have no idea what 'damaged' means here. But the same procedure for replacing a certificate in #1 is possible.

**Comment by Gaoxichao** [comment]
What I mean is, when the certificate expires and some devices have been registered on my side, besides replacing the certificate in `mdm-certificates/`, do I need to give each old device that has been registered Send config file to re-register?

But what I understand is that after the certificate is replaced, the topic of the registration file will change. Will this not affect the connection between the MDM and the device?

https://github.com/micromdm/micromdm/wiki/Device-Identity-Certificate-Expiration
https://github.com/micromdm/micromdm/wiki/Renew-MDM-CSR-Certificate

**Comment by korylprince** [comment]
If you **Renew** the APNS certificate, the topic will not change, so the device's MDM enrollment won't be affected, and you won't need to send a new enrollment profile.

That's really the only good option. Like @jessepeterson said, the APNS topic is tied to the enrollment; you can't change it. If you can't renew your existing APNS certificate, you will need to unenroll the device and enroll it with the new APNS certificate.

**Comment by Gaoxichao** [comment]
> If you **Renew** the APNS certificate, the topic will not change, so the device's MDM enrollment won't be affected, and you won't need to send a new enrollment profile.
> 
> That's really the only good option. Like @jessepeterson said, the APNS topic is tied to the enrollment; you can't change it. If you can't renew your existing APNS certificate, you will need to unenroll the device and enroll it with the new APNS certificate.

@korylprince @jessepeterson 

how to unenroll the device and enroll it with the new APNS certificate？

**Comment by korylprince** [comment]
There's a few (possible) ways you can unenroll a device:

- If the MDM profile is marked as removable (this isn't usually suggested), you can manually remove the profile from the device
- If MDM commands are still working, send the RemoveProfile command for your enrollment profile to the device
- If the APNS is not working, but the device still otherwise trusted the MDM server, you can still queue the RemoveProfile command, and rebooting the device should cause it to check in and see the command
- If all else fails, you'll have to erase the device

**Comment by jessepeterson** [comment]
Don't forget the 401 unenroll response. In MicroMDM this is the "block" functionality.

**Comment by Gaoxichao** [comment]
@jessepeterson  @korylprince 
You are talking about first canceling and then reinstalling the registration file to re-associate, but how to replace the registration silently, without active operation of the device

**Comment by korylprince** [comment]
If you can renew the APNS certificate used for the existing enrollment, you don't have to do anything other than upload the new certificate to MicroMDM.

If you can't renew the APNS certificate, you're out of luck. Apple doesn't allow switching the MDM APNS topic without removing the old enrollment and enrolling with the new topic. On macOS, you might be able to make the unenroll/enroll smoother by utilizing [umad](https://github.com/macadmins/umad) or a similar tool, but there's no way to silently switch MDMs (with separate APNS topics).

**Comment by Gaoxichao** [comment]
What if the apns-cert is no longer valid?  Is there no way to change to a new topic? The devices is maybe already know in the hands of the user, really bad news...

**Comment by korylprince** [comment]
There is no way to change change to a new topic without going through what we outlined above.

Apple usually has a grace period after the certificate expires to still allow you to renew the original certificate. If that's already passed, I'd suggest contacting Apple support to see if they can manually process a renewal for you.

However, I'd neither of those options work out, the **only** option is to unenroll/re-enroll.
