### ISSUE TITLE
Manage Ios devices 

### ISSUE THREAD

**Issue by guptaabhinav1512** [micromdm/micromdm#91]
Can this be used for Managing iPhones?

**Comment by arubdesu** [comment]
The very first line of the readme says this project is _primarily_ for Macs, there's also a specific mention that iOS devices are not the priority.

**Comment by guptaabhinav1512** [comment]
Thanks for the confirmation :)

**Comment by jessepeterson** [comment]
@guptaabhinav1512: just wanted to add that iOS enrollment & DEP deployment does work. While its not the priority there the MDM protocol is sufficiently similar on both platforms to work.

**Comment by guptaabhinav1512** [comment]
@jessepeterson : So I'll be able to add IPhone devices? Is any command supported for the phone as the protocol is similar?

**Comment by jessepeterson** [comment]
@guptaabhinav1512: Yes, you can enroll iOS devices. The protocol is the same between macOS and iOS. Some commands are different for iOS and support for which may (more like probably) not be present or supported yet.

**Comment by guptaabhinav1512** [comment]
Cool. Will the enrollment procedure be the same too?

Yeah, I'll probably fork it and extend it to include phone commands.

**Comment by jessepeterson** [comment]
Enrollment is done the same. Whether that be plain profile enrollment, OTA, or DEP. If you do end up forking and extending let us know — we'd be open to adding more support for iOS. Just right now our priority is on macOS.

**Comment by guptaabhinav1512** [comment]
Thanks a lot for all the help. Yeah, sure. I was experiencing issues with
commandment (python server you built) so thought of using this instead.
Thanks
