### ISSUE TITLE
Setting up iOS MDM service

### ISSUE THREAD

**Issue by cherimo** [micromdm/micromdm#912]
Ticket is not an issue as its more a question that I cant find any answer to it.

I am currently in the process of setting up my own MDM service through the open source project micromdm.
The way I read and understood it is that you need an MDM server with an Enptrise license to have a working MDM server. But when I see what the requirements are for such a license, I should already have an existing company with more than 100 employees, unfortunately this is not feasible for me.

Is it also possible to set up an MDM service with a normal developer account? For me it's just about managing iOS devices?

**Comment by jessepeterson** [comment]
Firstly for just testing, you can get a free push certificate at https://mdmcert.download

Secondly, as of late to get a MDM CSR cert you can have a normal paid developer account to request the MDM CSR option.

Please see the docs here for more: https://github.com/micromdm/micromdm/blob/main/docs/user-guide/quickstart.md and feel free to join us on Slack to discuss general things like this. :)
