### ISSUE TITLE
about VPNs

### ISSUE THREAD

**Issue by Gaoxichao** [micromdm/micromdm#914]
Do I need a company type developer account to use mdmcert. download 'vpns, and do I have to pay a fee of $99?

**Comment by korylprince** [comment]
You will need an Apple Developer account to get an APNs certificate. There is an annual cost of $99 for a developer account in the US; I would expect something similar in other countries.

Here's some recommended reading on getting an MDM CSR (or using an alternative) and getting an APNs cert:

- https://github.com/micromdm/micromdm/discussions/775
- https://micromdm.io/blog/certificates/
- https://github.com/micromdm/micromdm/blob/main/docs/user-guide/quickstart.md#configure-an-apns-certificate
