### ISSUE TITLE
Can I carry the client request header on webhook

### ISSUE THREAD

**Issue by axing21cn** [micromdm/micromdm#916]
### What version of `micromdm` are you using?
micromdm 1.11
### What `micromdm` command did you run?
webhook
### What did you expect to see?
I want to obtain the IP address of the mobile device accessing the MDM server in the webhook interface

### What did you see instead?
I don't know how to transmit the client's request header to webhook

**Comment by korylprince** [comment]
This is not something currently supported by MicroMDM (or NanoMDM).

An alternative might be to put some middleware in front of MicroMDM's endpoints and capture the headers there. You could either save the headers to a database to be referenced by your webhook, or just use the webhook logic directly in your middleware.
