### ISSUE TITLE
Declarative Management  why adding the ManagedAppleID key to an MDM enrollment profile

### ISSUE THREAD

**Issue by zxyzhouxiaoyun** [micromdm/micromdm#925]
### What version of `micromdm` are you using?
1.11
### What `micromdm` command did you run?
https://micromdm.io/blog/wwdc21-declarative-management/
### What did you expect to see?
Can't find the document. I want to know why. Thank you.

**Comment by korylprince** [comment]
The ManagedAppleID key is documented (and deprecated) [here](https://developer.apple.com/documentation/devicemanagement/mdm).

Declarative Management (DDM) has grown quite a bit since that blog post was written, so some information might be outdated. If you're interested in experimenting with DDM, you should check out [kmfddm](https://github.com/jessepeterson/kmfddm), whose docs are more up to date with respect to the current state of DDM.

**Comment by zxyzhouxiaoyun** [comment]
> The ManagedAppleID key is documented (and deprecated) [here](https://developer.apple.com/documentation/devicemanagement/mdm).
> 
> Declarative Management (DDM) has grown quite a bit since that blog post was written, so some information might be outdated. If you're interested in experimenting with DDM, you should check out [kmfddm](https://github.com/jessepeterson/kmfddm), whose docs are more up to date with respect to the current state of DDM.


That's it. I filled in the -dm parameter in 1.11, but I didn't find any information reporting the device status. Later I saw this article saying that I need to add the ManagedAppleID parameter to the description file. I'm still researching it. I don't know. Is there something wrong with the profile?

**Comment by jessepeterson** [comment]
> That's it. I filled in the -dm parameter in 1.11, but I didn't find any information reporting the device status. Later I saw this article saying that I need to add the ManagedAppleID parameter to the description file. I'm still researching it. I don't know. Is there something wrong with the profile?

Originally Declarative Management was only possible with User Enrollments. But that was two years ago. Now you can use it on most modern Apple OSes which does not require the `ManagedAppleID` key — any type of enrollment should work fine provided the device is supported (iOS 16, Ventura, etc.). Check out the [KMFDDM QuickStart](https://github.com/jessepeterson/kmfddm/blob/main/docs/quickstart.md) to get started.

I'd suggest then asking questions in the #nanomdm or #micromdm channels on the  [MacAdmins Slack](https://www.macadmins.org) or the [KMFDDM project Discussion](https://github.com/jessepeterson/kmfddm/discussions) area.
