### ISSUE TITLE
How to start APP automatically after booting in MDM?

### ISSUE THREAD

**Issue by Gaoxichao** [micromdm/micromdm#931]
Hey ! Do you know how to start APP automatically after booting in MDM?

**Comment by ppdouble** [comment]
You might need to check if there are corresponding commands to do this first.

https://developer.apple.com/documentation/devicemanagement/commands_and_queries

And then check `AccessRights`. https://developer.apple.com/documentation/devicemanagement/mdm#properties

**Comment by korylprince** [comment]
This is going to depend on what OS you're trying to use. For iOS/iPadOS, you can configure Single App Mode using the [AppLock](https://developer.apple.com/documentation/devicemanagement/applock) profile payload.

For macOS, you can configure [LoginItemsManagedItems](https://developer.apple.com/documentation/devicemanagement/loginitemsmanageditems) or [LoginWindowScripts](https://developer.apple.com/documentation/devicemanagement/loginwindowscripts) profile payloads, which may or may not do what you want. I would generally configure this sort of thing via an installed pkg (InstallApplication command, or, preferably, something like Munki), which would set up system services (e.g. launchd).
