### ISSUE TITLE
send a bash &  send a file

### ISSUE THREAD

**Issue by AmberHan** [micromdm/micromdm#932]
### What did you expect to see?
Can I send a bash command to the registered device and have it execute it? In addition, can I send a file directly to the device?

**Comment by jessepeterson** [comment]
This was recently answered on the Slack channel. On macOS you can install a .pkg installer with the InstallApplication and InstallEnterpriseApplication MDM commands. .pkg installers can have scripts embedded in them.

That said - Running bash scripts from MDM doesn't sound like a great idea. :)

**Comment by jessepeterson** [comment]
This is an operational question so I'm going to close this issue. Please either open a Discussion or join the slack channel to discuss.
