### ISSUE TITLE
Variables in device certificate obtained by SCEP like %HardwareUUID%

### ISSUE THREAD

**Issue by pdbs** [micromdm/micromdm#934]
### What version of `micromdm` are you using?
1.11
### What `micromdm` command did you run?
mdmctl apply profiles -f enroll.mobileconfig
### What did you expect to see?
According to https://support.apple.com/en-mz/guide/deployment/dep04666af94/web one can use system variables like %HardwareUUID% in the CN common name field. This works fine with enroll.mobileconfig under MacOS X - but not on iOS.

Not a microMDM bug, but maybe somebody has a solution or explanation?

### What did you see instead?
%HardwareUUID% as a string instead of the device‘s UUID

Did somebody manage to use system variables under iOS in SCEP context?

**Comment by jessepeterson** [comment]
If you want these attributes in the profile you'll have to gather them yourself and inject them yourself into a dynamic mobile profile.

**Comment by pdbs** [comment]
Thank you for the quick response!
