### ISSUE TITLE
failed when compile the source code

### ISSUE THREAD

**Issue by Jackyuan999** [micromdm/micromdm#937]
### What version of `micromdm` are you using?
1.11
### What `micromdm` command did you run?
compile source code
### What did you expect to see?
compile OK
### What did you see instead?
![1698659283318](https://github.com/micromdm/micromdm/assets/7939663/db54a477-ba91-45fa-98d2-3dc022798f8d)

**Comment by jamesez** [comment]
You're running `go run` from the wrong path. You need to be in the root of then project, `d:\code\go\micromdm-main` in your example, then `go run ./cmd/micromdm`.

(Windows may need you to type in `go run .\cmd\micromdm`, I don't know)

**Comment by korylprince** [comment]
In addition to what @jamesez said, you might want to read https://go.dev/doc/tutorial/compile-install for information on how to compile Go code.

There's also a [Makefile](https://github.com/micromdm/micromdm/blob/main/Makefile) in the repo root, so you can run `make build` to build mdmctl and micromdm.
