### ISSUE TITLE
How to use micromdm in combination with kmfddm

### ISSUE THREAD

**Issue by zxyzhouxiaoyun** [micromdm/micromdm#938]
### What version of `micromdm` are you using?
1.11.0  micromdm
### What `micromdm` command did you run?
 /opt/micromdm/build/linux/micromdm serve -server-url=*** -api-key  **** -tls-cert bundle.crt -tls-key  *.cn.key  -filerepo  ***  -command-webhook-url  **  -dm=127.0.0.1:9002

./kmfddm-linux-amd64 -micromdm -debug

**Comment by jessepeterson** [comment]
Hello @zxyzhouxiaoyun. The KMFDDM project has a nice Quickstart guide that walks you through it: https://github.com/jessepeterson/kmfddm/blob/main/docs/quickstart.md Let us know if there's any problems with it. KMFDDM is out of scope for MicroMDM, so you probably want to seek help there (or the #nanomdm channel on Slack).
