### ISSUE TITLE
persist configuration passed by flags. 

### ISSUE THREAD

**Issue by groob** [micromdm/micromdm#94]
Right now micromdm has a bunch of flags passed at startup, like `-server-url` or `-filerepo`
These should be persisted in a configuration bucket (and updated when the daemon is restarted in case they change). 

Persisting the configuration of the running daemon will allow the other subcommands to take advantage of the config. For example the `-import-pkg` mentioned in #93 could use the server-url.

**Comment by jessepeterson** [comment]
Note some configuration options (e.g. server URL) need to be handled sensitively as they cannot ever change once devices started enrolling.

**Comment by groob** [comment]
You're right. This is a big gotcha that should be documented. 
If we do persist the value we can throw a huge WARNING if the user changes it.

**Comment by Beanow** [comment]
:-1: imho. We plan on running in docker and require every single run to behave predictably. Requiring the flags on every run is how it should work.

**Comment by Beanow** [comment]
Note, the docker mindset is that configuration is not state, rather it's part of the environment.

Lastly when running in a docker swarm, it's preferred not to have secrets in the command or env vars, but use secrets instead. These are exposed in the docker container as files, which under the hood are stored as an encrypted ram disk. https://docs.docker.com/engine/swarm/secrets/

So rather than persisting flags, I would much prefer having a config file.

**Comment by groob** [comment]
I moved the APNS certificate storage to the DB and you can now use `mdmctl` to upload/replace a MDM certificate. The reason for this change is twofold: 
- many users would try to start the server, then realize they don't actually have a certificate, and would have to start using `mdmctl mdmcert` to create a certificate, then come back. Today the server can be started with a minimal set of configuration (no apns at startup) and then the cert can be managed separately. 
- the APNS certificate is not a server configuration dependency, but rather a configuration of the application. In the future, a micromdm server could have 2+ APNS certs for different business units (for example). 

I agree with @Beanow about `-server-url` and `-tls` configuration should be flag/env vars. 

Closing this issue as I'm satisfied with the current flag/db config segregation.
