### ISSUE TITLE
If my ssl certificate expires is not my device will not receive my command

### ISSUE THREAD

**Issue by zxyzhouxiaoyun** [micromdm/micromdm#950]
My ssl certificate is about to expire and I don't know what to do now

If my ssl certificate expires is not my device will not receive my command

apns can be renewed should have no problem

**Comment by korylprince** [comment]
If by "ssl certificate" you mean the certificate you pass to `-tls-cert` and `-tls-key`, you just need to replace it with a new cert trusted by your devices (e.g. signed by a trusted CA). Just replace the cert and key files or point the flags to the new file locations.

If you mean the certificate you used to sign your profiles (including your enrollment profile), you'll need to sign the profiles with a new certificate and use the InstallProfile command to send the newly signed version to your devices.

Your APNs certificate is separate from these, and must be _renewed_ via Apple. You would then upload the new certificate with the `mdmctl mdmcert ...` command and restart MicroMDM (not sure if this is still necessary) to take effect.

**Comment by zxyzhouxiaoyun** [comment]
> If by "ssl certificate" you mean the certificate you pass to `-tls-cert` and `-tls-key`, you just need to replace it with a new cert trusted by your devices (e.g. signed by a trusted CA). Just replace the cert and key files or point the flags to the new file locations.
> 
> If you mean the certificate you used to sign your profiles (including your enrollment profile), you'll need to sign the profiles with a new certificate and use the InstallProfile command to send the newly signed version to your devices.
> 
> Your APNs certificate is separate from these, and must be _renewed_ via Apple. You would then upload the new certificate with the `mdmctl mdmcert ...` command and restart MicroMDM (not sure if this is still necessary) to take effect.

If my SSL certificate expires, does my device need to be re-registered?

**Comment by korylprince** [comment]
No. The only thing that would cause your device to need to be reregistered is changing some of the fields in the MDM payload (e.g. your enrollment profile). Mainly, setting a new server URL or a new APNs topic.

**Comment by zxyzhouxiaoyun** [comment]
> No. The only thing that would cause your device to need to be reregistered is changing some of the fields in the MDM payload (e.g. your enrollment profile). Mainly, setting a new server URL or a new APNs topic.

https://developer.apple.com/documentation/devicemanagement/implementing_device_management/managing_certificates_for_mdm_servers_and_devices

This is the document I read from Apple,

Warning
If any certificate in the SSL trust chain expires, the device can’t connect to the MDM server to receive its commands. When this occurs, you lose the ability to manage that device.
But I can't verify this now

**Comment by zxyzhouxiaoyun** [comment]
> Right, so if your HTTPS certificate expires, your devices won't be able to receive commands from MicroMDM. Replace your certificate with a new one and your devices will be able to receive commands again.
> 
> So you will "lose the ability to manage that device", but only temporarily while the certificate is not replaced.

I don't understand. So I replaced the old certificate ,Can devices with old certificates still receive i commands again?

**Comment by zxyzhouxiaoyun** [comment]
> Right, so if your HTTPS certificate expires, your devices won't be able to receive commands from MicroMDM. Replace your certificate with a new one and your devices will be able to receive commands again.
> 
> So you will "lose the ability to manage that device", but only temporarily while the certificate is not replaced.

Hello, my dep-token has expired. I replaced it and uploaded it, but my command failed. I always thought that command had nothing to do with dep-token. What shall I do now, thank you

**Comment by korylprince** [comment]
That's correct. The DEP token has nothing to do with your APNS certificate or MicroMDM's ability to queue commands.
