### ISSUE TITLE
binding to port 80 cannot be altered or turned off when using builtin tls

### ISSUE THREAD

**Issue by meta-github** [micromdm/micromdm#963]
### What version of `micromdm` are you using?
micromdm version v1.11.0

### What `micromdm` command did you run?
Just started the server without turning off the tls functionality, i.e. **not** using `-tls=false`.

### What did you expect to see?
The server should not bind to port 80.

### What did you see instead?
The server binds to port 80 and that is neither optional nor configurable. There should be an option to turn off that http-bind or it should be eliminated completely.

**Comment by groob** [comment]
FWIW we only bind to port 80 if you choose to bind to port 443. This is done to force an HTTPs redirect for publicly configured servers. 

You can have built-in TLS on a different port and we won't bind to port 80. I think just use a proxy and terminate TLS there if you want to work around the defaults.

**Comment by meta-github** [comment]
We run micromdm in our intranet and the internal tls is perfectly fine for us. I'd like to avoid running a different software as tls endpoint. Switching the port would also mean to run additional software that forwards the requests from 443, since we do not want to re-enroll our devices. An option to turn off port 80 seems like the cleanest and best solution.
