### ISSUE TITLE
Upgraded from 1.11 to 1.12 and now it won't start 

### ISSUE THREAD

**Issue by cph-jh332** [micromdm/micromdm#969]
### What version of `micromdm` are you using?
1.12.0

### What `micromdm` command did you run?
micromdm serve -api-key ${API_TOKEN} -config-path /app/config -tls=false -server-url https://localhost:8080 -command-webhook-url http://localhost:3333/api/webhook -tls=false -no-command-history=true -queue inmem

### What did you expect to see?
A running service like with 1.11

### What did you see instead?
//micromdm: line 1: ELF0@@8@@@@PPddHHIJJ: not found
//micromdm: line 2: syntax error: unexpected ")"

**Comment by jamesez** [comment]
Did you download a binary for the wrong architecture? What are the outputs from running `file micromdm` and also `uname -a`?

**Comment by cph-jh332** [comment]
![image](https://github.com/micromdm/micromdm/assets/22742804/642627f0-6f55-4a69-bddf-c19b44535e23)

From the commands

**Comment by korylprince** [comment]
That's my bad. Looks like our Makefile doesn't set the arch, and since I built the release on Apple Silicon, it defaulted to arm64. I didn't notice that until your issue, so thanks for letting us know!

I've uploaded a new release with the x86-64 version.

**Comment by cph-jh332** [comment]
Thanks for the quick answer hand handling of the issue.
