### ISSUE TITLE
MDM “RestartDevice” is not a valid request type.

### ISSUE THREAD

**Issue by yida-chen-uid** [micromdm/micromdm#970]
The iphone restarts

MDM command request is as follows :

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN""http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
   <dict>
      <key>Command</key>
      <dict>
         <key>RequestType</key>
         <string>RestartDevice</string>
      </dict>
      <key>CommandUUID</key>
      <string>67e4a33d-f093-450c-b45e-d27d9d577569</string>
   </dict>
</plist>
```

I am getting following response：
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
   <dict>
      <key>CommandUUID</key>
      <string>67e4a33d-f093-450c-b45e-d27d9d577569</string>
      <key>ErrorChain</key>
      <array>
         <dict>
            <key>ErrorCode</key>
            <integer>12021</integer>
            <key>ErrorDomain</key>
            <string>MCMDMErrorDomain</string>
            <key>LocalizedDescription</key>
            <string>“RestartDevice” is not a valid request type.</string>
            <key>USEnglishDescription</key>
            <string>“RestartDevice” is not a valid request type.</string>
         </dict>
      </array>
      <key>Status</key>
      <string>Error</string>
      <key>UDID</key>
      <string>22c4e464e01a3343123ac47634fa9e081f045ff9</string>
   </dict>
</plist>

```
I am getting this kind of error for some other request type also like ShutDownDevice, EnableLostMode, etc.

I make sure that device's OS version is above required OS version.

Can anyone please let me know what is wrong here?

**Comment by korylprince** [comment]
What device model and OS are the target device(s)?

**Comment by yida-chen-uid** [comment]
> 目标设备是什么设备型号和操作系统？

IOS 17.2.1

**Comment by korylprince** [comment]
Looking at the [metadata for the command](https://github.com/apple/device-management/blob/release/mdm/commands/device.restart.yaml):

- The device must not be enrolled with user enrollment
- The device must be supervised
- The MDM must have ["Allow device lock and passcode removal" Access Rights](https://developer.apple.com/documentation/devicemanagement/mdm) for the enrollment

I'm guessing your device's enrollment doesn't meet one of these criteria.

**Comment by yida-chen-uid** [comment]
> * The device must be supervised

How is this achieved？

**Comment by jessepeterson** [comment]
> How is this achieved？

https://support.apple.com/guide/deployment/about-device-supervision-dep1d89f0bff/web

**Comment by yida-chen-uid** [comment]
iOS devices can be placed under supervision by two different methods:
- Automatic (using ADE)
- Manual (using Apple Configurator for iOS)

My IOS device has been managed by MDM. Can I enable supervision mode by installing a profile file？

**Comment by jessepeterson** [comment]
The only two supported ways are what you listed: ADE or manual (Configurator).
