### ISSUE TITLE
failed to parse private key (use ParsePKCS8PrivateKey instead for this key format)

### ISSUE THREAD

**Issue by dstmath** [micromdm/micromdm#994]
### What version of `micromdm` are you using?
1.12.1
### What `micromdm` command did you run?
./mdmctl mdmcert upload -cert xxx.pem -private-key xxxMDMPKCS8PrivateKey.pem -password=password
### What did you expect to see?
upload success.

### What did you see instead?
load push certificate: parse push certiificate private key xxxMDMPKCS8PrivateKey.pem: x509: failed to parse private key (use ParsePKCS8PrivateKey instead for this key format)

I alreay hava a p12 file. And I used the command to convert a p12 file:
```
openssl pkcs12 -in xxxMDMPush.p12 -out xxxMDMCertificate.pem -clcerts -nokeys
openssl pkcs12 -in xxxMDMPush.p12 -out xxxMDMPrivateKey.pem -nocerts -nodes
openssl pkcs8 -topk8 -inform PEM -outform PEM -in xxxMDMPrivateKey.pem -out xxxMDMPKCS8PrivateKey.pem -nocrypt
```

but i got an error.

**Comment by jessepeterson** [comment]
Hello @dstmath You may need to convert your private key if you're doing this with a modern OpenSSL: `openssl rsa -in key.pem -out key.pem -traditional` - this should convert from a P#8 key to a P#1 PEM key.

**Comment by dstmath** [comment]
It's solved.thanks!
